### ISSUE TITLE
[QUESTION] Port exult to libretro

### ISSUE THREAD

**Issue by dmorilha** [exult/exult#107]
First of all let me tell this project is simply awesome! Ultima 7 was the one great game that I vividly remember from when I was growing up, and Exult let it live on!

With the well deserved compliments aside, how difficult would it be to port Exult as a libretro core? I was browsing through the code and it looks like SDL is poured all over the place, would it be too difficult to get the engine rewritten into the libretro constrains found here https://github.com/libretro/libretro-samples?

I really would like to play it on a TV...

**Comment by marzojr** [comment]
It would take far too much work. There is also many other issues with playing on TVs, some of which are mentioned in [this issue](https://github.com/exult/exult/issues/46) (although some of it may be specific to Apple TVs).
