### ISSUE TITLE
Moving mouse to other monitor causes Exult to minimize (X Window System)

### ISSUE THREAD

**Issue by jharrison03** [exult/exult#108]
In a configuration with two monitors positioned side-by-side, moving the mouse from a maximized Exult off the screen edge to the other monitor will cause Exult to minimize itself.  This behavior is not observed under a single monitor X configuration.  This makes navigation difficult, since the mouse cursor is usually at the peripheries of the screen when moving your party.

**Comment by DominusExult** [comment]
Are you using the latest version of SDL2 (not necessarily the latest from your package manager but really the latest version released)?
This sounds like an issue of SDL2 with X not necessarily something Exult does wrong.

**Comment by jharrison03** [comment]
I am, but I'm also on Debian 8, with it's X libraries and everything else.  So, feel free to close this, and when I upgrade, I'll report back into this ticket if the problem persists.

**Comment by jharrison03** [comment]
This is no longer happening for me now with latest Exult.
