### ISSUE TITLE
Mouse cursor on iOS

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#110]
The cursor was disabled on purpose as it didn't make sense to show it while you could only use touch on iOS.
But now you can also use a mouse with an iPad. 
So bringing the mouse cursor back as an mobile device option is the best way forward.

I guess you can probably poll if there is a mouse connected and then display the cursor but that is not proper as one might still play per touch even though a mouse is connected

**Comment by wench** [comment]
If the API lets you, something you could try is automatically showing the mouse cursor if there is mouse movement and hiding the mouse cursor if there is a touch event

**Comment by DominusExult** [comment]
Good idea, I'll investigate what SDL2 has to offer there

**Comment by DominusExult** [comment]
Just taking notes from my question in the SDL forums:
- SDL_TOUCH_MOUSEID to identify the pseudo mouse that sends events
- Since SDL 2.0.10 there’s SDL_HINT_MOUSE_TOUCH_EVENTS and SDL_HINT_TOUCH_MOUSE_EVENTS but I’m not sure if they work in iOS. They also seem to be completely undocumented!
Supposedly, if you set both those hints to “0” you will receive only touch events from touch (no synthesized mouse events), and only mouse events from the mouse (no synthesized touch events). If they work, you could enable your cursor whenever there’s a mouse event and disable it whenever there’s a touch event.

**Comment by DominusExult** [comment]
ok, need to polish the code but it works like this:
when SDL_MOUSEMOTION is detected as a real mouse (not SDL_TOUCH_MOUSEID) the cursor is shown and sets SDL_HINT_TOUCH_MOUSE_EVENTS.
To get back from this is a bit tricky as SDL_HINT_TOUCH_MOUSE_EVENTS messes with the detection but SDL_FINGERMOTION or even SDL_FINGERDOWN works. Which better to use is still to be decided through testing. Testing only works with a real iPAd + mouse as the iOS simulator is not ideal for that.

**Comment by DominusExult** [comment]
This is now working. The biggest clue that I (and the SDL devs) didn't know was to add UIApplicationSupportsIndirectInputEvents to the info.plist file. Additionally there were some fixes in current SDL2 development code to better synchronize the iOS cursor with the SDL cursor.
