### ISSUE TITLE
Mordra disappears after black mass in Skara Brae

### ISSUE THREAD

**Issue by jharrison03** [exult/exult#111]
After freeing Horance, Mordra is nowhere to be found in Skara Brae (so I'm not able to ask her about the sacrifice).  She's not in or near her house or the cemetery or in the castle.  I've explored the area thoroughly, tried sleeping, and re-played Skara Brae a number of times.  I can a provide a save, but I'm not sure which file(s) I should attach.

**Comment by DominusExult** [comment]
Yes, please attach a savegame. In the savegame dialog you can see the savegaeme file and you can look at http://exult.info/docs.php#path_config_nt5 for an example where to find them on Windows (and further down where on macOS or Linux)

**Comment by DominusExult** [comment]
Worked for me when I played it right now.
And unless we get a savegame to look things up, we can't help.
