### ISSUE TITLE
Exult 1.7.0git with SIfixes hides monks

### ISSUE THREAD

**Issue by bliznik** [exult/exult#113]
I'm playing using the latest version of exult with sifixes. I'm near the end of the game and I'm trying to find Xenka, but she is nowhere to be found. All of the monks seem frozen in front of the podium and don't really move. Thoxa is nowhere to be found.

I looked into the NPC code, and it looks like the schedules for the monks were reset. I'm unsure when, but Xenka is placed in a faraway "location" and is just told to wait all day long. This should not be the case since I've freed my companions from the Banes and I had a conversation with Xenka after I was teleported to Monk Isle.

This places the game in an unwinnable state without cheating.

**Comment by bliznik** [comment]
I played with the cheat menu some more, and it seems like Xenka was in the area where "dead" NPCs are stored? The only way I was able to proceed with the quest was to teleport into that building, talk to Xenka to learn that I need to sacrifice myself, and then teleport out of that building.

**Comment by DominusExult** [comment]
can you add the savegame?

**Comment by bliznik** [comment]
Here you go, this is a savegame right after I got the serpent tooth from Xenka. Now I can't talk to her anymore...

[exult43si.zip](https://github.com/exult/exult/files/6687707/exult43si.zip)
