### ISSUE TITLE
SI: mage banquet breaks rejoin of partymembers if they are invisible

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#118]
The banquet scene (as many scripted scenes in SI) throws out the party members and then rejoins them after the scene. But if the members are invisible at the time of the auto rejoin, Exult messes it up and they are not rejoined and stay hidden (because invisible).
Curiously, as @ungesundes-halbwissen tested in DOSBox, the original behaves the same. So we follow the original game but the behavior is not correct, IMO.

In the savegame walk around a bit until the magelord summons you to the banquet. Rename zip to exult147si.sav.

[exult147si.sav.zip](https://github.com/exult/exult/files/7405855/exult147si.sav.zip)

**Comment by DominusExult** [comment]
I think the relevant bits in the debugging output of the end of this scene is 

```
[0x41]: find_nearby(fe9c, ffff, 002d, 0004) = [ 7fd456071528, 7fd456004098, 7fd45606d438, 7fd456076ac8 ]
Running usecode 098d () with event 2, depth 1
Returning ([ ffff, fffe, fffd, ff6b, ffe4, ffe6, ffd3, ffde, ffd4, ff68, ff58 ]) from usecode 098d
...back into usecode 032e
    [0xbc]: get_npc_id(7fd456071528) = 0000
    [0x47]: get_npc_number(7fd456071528) = fff6
    [0xbc]: get_npc_id(7fd456004098) = 0000
    [0x47]: get_npc_number(7fd456004098) = fe9c
    [0xbc]: get_npc_id(7fd45606d438) = 000b
    [0x47]: get_npc_number(7fd45606d438) = fffe
    [0x26]: add_to_party(7fd45606d438) = 0000
    [0xbc]: get_npc_id(7fd456076ac8) = 0000
    [0x47]: get_npc_number(7fd456076ac8) = ffea
    [0xa5]: clear_item_flag(fe9c, 0010) = Setting Shape to 1028
```
Seems usecode 098d finds all NPCs nearby that are not the avatar nearby but usecode 032e only checks visible results, so ffff (Dupre) and fffd (Iolo) are not even looked at...

**Comment by marzojr** [comment]
Note that this is not a bug in Exult, but in the original usecode: the last parameter of find_nearby is a mask that can enable/disable special matching functions. In this case, it is 0x0004, which corresponds to NPCs -- but not invisible NPCs. It ought to have been 0x0024 to allow it to match NPCs whether they are invisible or not.

I guess this could go into SI Fixes?

**Comment by DominusExult** [comment]
Yes, then it is a SI Fixes item

**Comment by marzojr** [comment]
For reference: this is the original usecode that gets everyone back into the party:
```dart
		var near_npcs = AVATAR->find_nearby(ANY_SHAPE, 0x002D, MASK_NPC);
		var joinables = getJoinableNpcIds();
		for (npc in near_npcs) {
			if (npc->get_npc_id() == 11 && (npc->get_npc_number() in joinables)) {
				npc->add_to_party();
			}
		}
```
The NPC ID gets set to 11 by the function that starts the banquet when it removes the NPCs from the party. So if the find_nearby call is changed to also search for invisibles, it basically becomes equal to
```dart
		var joinables = getJoinableNpcIds();
		for (npc in joinables) {
			if (npc->get_npc_id() == 11) {
				npc->add_to_party();
			}
		}
```
