### ISSUE TITLE
In SI with SIFixes, reloaded save unplayable

### ISSUE THREAD

**Issue by tdahlstrom** [exult/exult#133]
So, I reloaded a save while playing through SI with SIFixes installed.  Upon reloading the cursor is the pointing hand instead of the green arrow.  I am not allowed to perform any other actions besides interacting with the Main Menu and associated sub-menus.  I wasn't sure if this belonged on the Exult or SIFixes bug tracker, so I'm starting here.  I have included a save file that has the issue
[exult00si.zip](https://github.com/exult/exult/files/7876350/exult00si.zip)
.  The save file is in a zip file, as I couldn't add it with the typical .sav extension.  Also, I am using the latest version of Exult 1.6 and the latest version of SIFixes.

I did have to change the accepted minimum version number in SIFixes to work with Exult 1.6, so this may be related to the issue.

**Comment by DominusExult** [comment]
I'm taking a look later.
BUT the version check is there for a reason. The version of SIFixes is to be used with the latest snapshot of Exult, not the latest release.

**Comment by DominusExult** [comment]
I wonder if there was a usecode script running at the time of saving. If there was it could be that something is going to be off.

To get out of this you need to clear the 'dont_move' flag:
Enter Cheat screen with F2, then n for npc tool, 0 for Avatar, n for NPC flags,  * for advanced, 16 for the don't move flag, u to unset it. Then a couple of times x to exit the cheat screen.

**Comment by tdahlstrom** [comment]
That worked.  Thank you for saving my game.  If there is a log or something I can include to help prevent this from happening again, please let me know.

**Comment by DominusExult** [comment]
Unfortunately we only log the current instance, so when you restart Exult and run into such a problem we can't go back and read the log of the previous run ;(
