### ISSUE TITLE
Reordering of the options menus

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#135]
I'm thinking of reordering our options menus, and would like your input of what to group together and how to order them.

Currently it is:
| Gameplay  | Misc  | Input  | 
|---|---|---|
| Status bars  |Scroll game mouse   | Item Helper Menu  | 
| Text Background  | Skip Intro  | D-pad location  | 
| Fullscreen Fast Mouse  | Skip scripted first scene (BG)  | Long Touch pathfind  |
| Use Middle button  | Alternate d'n'd  |   |
|Doubleclick closes Gump   | Allow Autonotes  |   |
| Right click closes Gump  | Use Shortcutbar: trans  |   |
|Right click pathfind   | Use Shortcutbar outline  |   |
| Gumps pause game  |Use Shortcutbar hide missing   |   |
| Cheats  |   |   |
| Speed   | Combat options  |   |
| Smooth Scrolling  | Difficulty  |   |
| Paperdolls (BG) |show hits  |    |
|   |mode  |    |
|   |Charmed diff  |    |

My proposal is a bit radical but moves all mouse stuff to the input options (which are newish and only held options that are helpful for touch screens) along with Smooth scrolling (that could also go into Misc Options). 
What do you think of this? Please anybody feel free to comment and make suggestions (I'd also like to hear from @malignantmanor whose input I miss :)) 
| Gameplay  | Misc  | Input  | 
|---|---|---|
| Text Background  | Skip Intro  |  Doubleclick closes Gump | 
|  Status bars   | Skip scripted first scene (BG)  | Right click closes Gump  | 
| Use Shortcutbar: trans  |   | Right click pathfind |
| Use Shortcutbar outline  |   | Scroll game mouse |
| Use Shortcutbar hide missing  | | Use Middle button |
| Take Autonotes (Renamed) |   | Fullscreen Fast Mouse  |
| Gumps pause game  | Combat options | Smooth Scrolling  |
| Alternate d'n'd | Difficulty | Item Helper Menu  |
| Speed  | show hits | D-pad location  |
|Cheats | mode  |  Long Touch pathfind    |
| Paperdolls (BG)  | Charmed diff  |    |
|   |   |    |
|   |   |    |

**Comment by DominusExult** [comment]
After some chats there were more issues raised about our options (all of them):
- make all options coherent: all of them should look the same. *Cancel* is not at the same gump spot related to the right edge. The Video options only has *apply*, which only makes some sense. It should have *ok* and *cancel* as well. In this case *ok* should work somewhat like *apply* only that it closes the video options gump when the new changes are ok.
- The gumps should have the same size
- the options don't necessarily make sense/are not descriptive enough (e.g. *Allow Autonotes* should probably renamed to *Take automatic notes*).
- This cannot be helped in all cases as we just don't have the necessary space, but it might be useful to have a third button (or in the Video options a fourth one) named *HELP* that opens our online documentation 
through `SDL_OpenURL("http://exult.info/docs.php#video_gumps");` (available in SDL2 2.0.14)
- don't abbreviate (*misc options*) and don't use winks (*allow drag'n'drop*...)
- rename the options categories (*Configure Video*, *Configure Audio*, *Options*, *More Options* (maybe another name here :)... )
- more space between Load/Save as it isn't an option or something to configure and maybe rename it to *Save/Load Game* as you must first save to be able to load

**Comment by Dragon-Baroque** [comment]
Some questions, please, first, to figure out the amount of freedom :

1. Would it be acceptable to increase the display size of the Option menus, vertically - so as to split the «Misc Options» page into the «Gameplay Options» and the «Input Options», for example -, or horizontally - to provide space for more meaningful option labels, or both, or none - if constrained by small sized targets, ie Smart Phones, Tablets - ?
2. Is it a correct statement that the Option menus use a proportional font, since using a fixed size font would cause the central «d» of the Options «Audio» and «Video» to be vertically aligned, which is obviously not the case ?
3. Instead of fully meaningful option labels, would it be feasible to provide tooltips for the option labels _and_ for the button labels, providing a generic explanation of the meaning of the option, as well as a specific explanation of the meaning of a choice of an option value ? That would mean that the tooltip on the button label would be tracking the current value of button label.

**Comment by DominusExult** [comment]
1. I think we are running out of space. The default resolution, as in the original to not give away too much of the land, is 320x200. If you set that and then open the options gumps you see that we just don't have enough space unless we dumb every label down.
2. we are using the fonts provided by the game
3. since we are using 2. we don't have a font that looks good when you hover it (we could use the font used in book and the notebook but there have been complaints about the readability already)


-> For a good solution I see the need:
- a "decoupled", independent from the game files, option "gumps" system
- or adding support for actual font files
- and/or rendering *all* gumps (as they are now) independent from the screen rendering, so they fit in the constraints of the window size but don't change their visible size depending on how the game is rendered (very big at 320x200, very tiny on "auto" at a very big window size). This is something that we would really need anyway in the future but someone would need to do it. The person who undertook stuff like this was usually @wench :)

**Comment by Dragon-Baroque** [comment]
Proposition, starting from your proposition :
- Menu titles : «Gameplay Options» -> «Game Display», «Misc Options» -> «Game Engine», «Input Options» -> «Game Input».
- Menu items : move Autonotes & Gumps pause & Speed & Cheats to Game Engine.
- Menu items : move Skip intro & Skip first scene to Game Display.
- Menu items : remove label «Combat Options» and factorize «Combat» in front of «Difficulty» & «Show Hits» & «Mode» & «Charmed Difficulty».
- Master menu order : «Game Engine», then «Game Display», then «Game Input». 

Net result : «Game Display» = 9 items, «Game Engine» = 8 items, «Game Input» = 10 items.

Could also merge «SFX Options» and «SFX», removing the label «SFX Options» without a button, and factorize «SFX» in front of «pack» & «conversion».

Same with «Speech Options» and «speech».

Nitpicking :
- Video Options menu : There are two blank lines between «Scaler» and «Game Area» although only one is needed for Scalers Point or Interlaced of Bilinear new «Scaling» option,
- Audio Options menu : The Midi driver button overflows the frame when «UnixSeqDevice» is displayed ( Linux only ? ) ,
- Gameplay Options menu : The Text Background button displays «Dark Green» twice giving 17 colors - 1 too many - and displays «Dark gray» not «Dark Gray»,
- By the way, Shortcut bar outline color displays only 7 colors, not 8. Expected ?
- Hesitation about «Pathfind» being a verb or a noun, suggest front verb : «Pathfind with Right click» & «Pathfind with Long touch».
- Decide whether the words in menu labels & option labels should be all with an uppercase first letter or only the first word.

**Comment by DominusExult** [comment]
Good points! I've moved *Alternative drag and drop* to Game Engine and *smooth scrolling* to Game Display. Drag and Drop doesn't effect what you see, while smooth scrolling does (and it's not an Input Option, I made a mistake there with my first draft). With the result of having 9 options per screen :)
I've put the two "Skip..." options at the bottom of Game Display as both *Skip scripted first scene* and *Paperdolls* will only show in the BG game (right now *Skip scripted first scene* is always shown but it does nothing on SI and thus shouldn't be displayed there).

I'm not sure about the master order, yet, but the more I look at it the more I prefer your idea. As I am too lazy to change the markup table again, it is still in the old order:

| Game Display  | Game Engine  | Game Input  | 
|---|---|---|
| Status Bars  | Take Autonotes  |  Doubleclick closes Gumps | 
|  Use ShortcutBar: transparent   | Gumps pause game  | Right click closes Gumps  | 
| Use outline color: colors | Alternative drag and drop | Pathfind with Right click |
| Hide missing items  | Speed | Scroll game view with mouse |
| Text Background:  colors  | Combat Difficulty | Use Middle Mouse Button |
|  Smooth scrolling | Combat show Hits  | Fullscreen Fast Mouse  |
| Skip intro  | Combat Mode | Item helper Menu |
| Skip scripted first scene (only BG) | Combat Charmed difficulty | D-Pad screen location  |
| Paperdolls (only BG) | Cheats | Pathfind with Long Touch  |

I'm also in favor of your proposed changes for the Audio options, especially as I wanted to wedge an extra speech option in there for the *Speech with Subtitles* cfg option we have but no button for it yet.

Your nitpickings are good to keep in mind. I decided to go with Pathfind as a verb.
As for capitalization, maybe we need to go with headline way, and capitalize first word and all nouns?

**Comment by DominusExult** [comment]
I'm not a big fan of putting the verb into the button but we'd probably need to test how that looks - *I* really need to see it and press the buttons in person to get a feel for it. Problem is that this forces us to give the buttons a bigger size to keep a consistent look (having one or two really large buttons is not great but one can overlook it, if all buttons are different sizes... ugh :)
It *does* open up interesting ways, as you point out.

Greyed out label, I don't think we have an option for that, as in I have no idea how to present that. But it could be an idea as that would look better than just not existing lines (for example we have some ifdef iphoneos that disable lines and buttons).

Proper is MT-32 AFAICS on the net.


I'm currently already working on the reorder.

**Comment by wench** [comment]
> 1. I think we are running out of space. The default resolution, as in the original to not give away too much of the land, is 320x200. If you set that and then open the options gumps you see that we just don't have enough space unless we dumb every label down.
> 2. we are using the fonts provided by the game
> 3. since we are using 2. we don't have a font that looks good when you hover it (we could use the font used in book and the notebook but there have been complaints about the readability already)
> 
> -> For a good solution I see the need:
> 
> * a "decoupled", independent from the game files, option "gumps" system
> * or adding support for actual font files
> * and/or rendering _all_ gumps (as they are now) independent from the screen rendering, so they fit in the constraints of the window size but don't change their visible size depending on how the game is rendered (very big at 320x200, very tiny on "auto" at a very big window size). This is something that we would really need anyway in the future but someone would need to do it. The person who undertook stuff like this was usually @wench :)

Being able to  render a gump highres unscaled seems like it would be a useful addition. 320x200 has been an annoying limitation for a long time. I'll look into it. Might need to impose a minimum window size

**Comment by Dragon-Baroque** [comment]
Thank you, @DominusExult.
Now, the `.exult.cfg` option database uses the old locations and old names.
Do you intend to align it onto the new locations ?

**Comment by malignantmanor** [comment]
The options menus definitely needed updated. I remember adding misc, because there was no room.

**Comment by DominusExult** [comment]
@Dragon-Baroque I don't think we should touch exult.cfg. Except for audio, video, shortcutbar and touch settings, every setting is just lumped in <gameplay>. For compatibility with old cfgs we should just keep that, IMO
I fixed some other nitpicks (UnixSeq device overflow, Alsa capitalization, Text background names (Dark Green was a misnamed green). 
I did not fix MT32 as that would mess with the midi conversion "fakemt32" - causing that button to overflow.

I did not understand:
- By the way, Shortcut bar outline color displays only 7 colors, not 8. Expected ? <- what is the problem there?
- Video Options menu : There are two blank lines between «Scaler» and «Game Area» although only one is needed for Scalers Point or Interlaced of Bilinear new «Scaling» option <- When a scaler has the option for scaling there is an extra button row and thus only one blank line which is a good way to keep that gump more readable IMO. Moving everything up or down depending on whether the scaling line is there would not look good

@malignantmanor great to hear from you

@wench thanks. I kind of envision it like this:
Game area and window sizes still free to configure.
Two or three different gump sizes: normal (rendered as if the game area were 320x200), small (400x300 perhaps), smallest (some other resolution that is still readable).
That way, even if you have a game area of 320x200 you could have smaller gumps.

**Comment by Dragon-Baroque** [comment]
@DominusExult, you are right on all points.
My observation of 17 colors and 7 colors was some assumption that the number of colors should be a power of two ( 8, 16 ) because of some old CGA / EGA compatibility : I had forgotten that Ultima 7 uses VGA mode 13 with 256 colors, instead.
My mistake. Apologies.

**Comment by Dragon-Baroque** [comment]
Thanks for attaching Help to the Options Gumps.
One does not work : `game_engine_gump` Help from `MiscOptions_gump.cc`, because it uses `docs.php`**##**`game_engine_gump` instead of `docs.php`**#**`game_engine_gump`.**

**Comment by Dragon-Baroque** [comment]
Working on issue #88 and the Audio Options gump, I have two suggestions :

- The `conversion` label for MIDI SFX overlaps the `Speech` label, because it is set at line 11 should be 10 at `gumps/AudioOptions_gump.cc:575`.
- When `digital music` is enabled, using the OGG files, shouldn't you clear the rows `music driver`, `device type` and `effects` ?

**Comment by DominusExult** [comment]
- MIDI SFX conversion text fixed
- digital music now also toggles music drivers

- UnixSeqDevice: I'll change the online help. But what about the driver code? Do you think I should shorten it everywhere, too?
Downside is that we break older cfgs. So I guess, I shouldn't :)

**Comment by DominusExult** [comment]
I have to rethink the digital music toggle a tiny bit:
- when sfx & midi sfx is enabled it shouldn't hide the midi driver options, as this is needed for the sfx.
- for now it *only* hides the midi driver options but doesn't disable the midi driver. So even though you enable digital music it still loads the midi driver. This was done this way that you can quickly change between digital and midi music without having to toggle through the midi drivers when you disable digital music. Probably should keep it that way.

**Comment by Dragon-Baroque** [comment]
Isn't the combination `Music as Digital` but `SFX as MIDI` a bit weird ?

- Digital Music [ high quality with OGG rerecorded ]
- MIDI SFX [ recorded from MT32 instead of Digital SFX recorded from SB, if I understand correctly ]

Of course, once `SFX as MIDI` is active, it would be violent to revert it back to `SFX as Digital` when you set `Music as Digital`, but as a user I would not be surprised. It would seem logical.

**Comment by DominusExult** [comment]
@Dragon-Baroque only now realized that there was one misunderstanding to clear up:
MIDI SFX is playing back the sfx by sending MIDI commands to your MIDI device. The semi correct thing to do would be to force disable MIDI SFX when digital music is enabled. I'm not sure about this though.
We have a prerecorded MT32 digital sfx pack, btw.

@drcode1, @marzojr, @Dragon-Baroque: should I rename the gump files to keep the gump folder consistent? GameplayOptions_gump.* to GameDisplay_gump.* and MiscOptions_gump.* to GameEngine_gump.*?

**Comment by marzojr** [comment]
> @drcode1, @marzojr, @Dragon-Baroque: should I rename the gump files to keep the gump folder consistent? GameplayOptions_gump.* to GameDisplay_gump.* and MiscOptions_gump.* to GameEngine_gump.*?

Sure, why not.

**Comment by Dragon-Baroque** [comment]
`MIDI SFX is playing back the sfx by sending MIDI commands to your MIDI device.`

From the code, the `MIDI SFX` uses the `midisfx.flx` a collection of XMIDI tracks.
The `Digital SFX` use either `jm[si]sfx.flx` for recorded SoudBlaster or `sqsfx{bg,si}.flx` for recorded MT32,
both are a collection of digital tracks.
Is this correct ?

Surprisingly enough, the MIDI SFX works even when the Music is disabled, or when the Music is enabled but as Digital.
In both cases, I would have expected that the Midi driver be inactive, thus preventing the MIDI SFX to be produced.

`The semi correct thing to do would be to force disable MIDI SFX when digital music is enabled.`

Or when Music is fully disabled, too.

`OTOH MIDI SFX is by default not even built as it just doesn't sound nice most of the times, so we could just neglect it.`

It just happens that my builds are almost full ( minus the Gimp plugin ), they contain the MIDI SFX.
Since MIDI SFX works even when Music is Off or Digital, there is no real need of propagating the Music state to the SFX state in the Audio Gump.
You are right, we may stop bothering about this.

**Comment by Dragon-Baroque** [comment]
`should I rename the gump files to keep the gump folder consistent?`

Sure, but won't you rename the Gump classes in the gump files too ?

**Comment by DominusExult** [comment]
I think with a54c3f1 and follow ups, I can close this. Thanks for all of your input, especially @Dragon-Baroque, it really helped getting a clear picture of what needed to go where. Much better and orderly looking, though muscle memory is still a bit hard to overcome :)
