### ISSUE TITLE
SI SS: Vibrate destroys the keys the target person has (at least Aram-Dol's) 

### ISSUE THREAD

**Issue by psavola** [exult/exult#142]
Using exult 1.7.0git Jan 24/2022. 

Using Vibrate spell on the lich Aram-Dol in SS appears to be one of the recommended strategies to deal with this opponent (to disable his spell casting). The spell should cause the target to drop the items (and spells as an implementation by-product) and Aram-Dol has two keys. If you cast Vibrate on him, something resembling the spells are indeed dropped, but keys are not, and if you kill him, the corpse doesn't have the keys either. So the keys disappear completely and you can't finish the quest. This was the only time I tried using Vibrate, and I suspect this is a more general problem with the exult implementation of the spell losing plot-essential items.

Attached is a save game before the fight, which is probably the most difficult one in the game.
[exult10si.zip](https://github.com/exult/exult/files/8009877/exult10si.zip)

**Comment by DominusExult** [comment]
I'll take a look later today. Is it with plain SS or with SIfixes?

**Comment by psavola** [comment]
This was with plain SS. I also have SIfixes installed, but apparently it didn't get used automatically and didn't feel like restarting the game when I noticed it missing.

**Comment by DominusExult** [comment]
I just tried and the keys are dropped along with the other stuff.
BUT other problems shoed up (when I hit b for the spellbook animations are stopping, Aram Dol ist stopped in his tracks...)

**Comment by psavola** [comment]
Doesn't work here with my version. See screenshot. Everything else is dropped, but no keys to be found?
![screenshot](https://user-images.githubusercontent.com/95160994/152683870-91c28ff7-3c2f-47a7-a3db-63fefd9441e0.png)

Exult version 1.7.0git
Built at: Jan 24 2022 23:40:32
Compile-time options: USE_TIMIDITY_MIDI, USE_FMOPL_MIDI, USE_ALSA_MIDI, HAVE_ZIP_SUPPORT
Compiler: GCC 8.5.0 20210514 (Red Hat 8.5.0-4)

Platform: Linux version 4.18.0-358.el8.x86_64

**Comment by DominusExult** [comment]
![image](https://user-images.githubusercontent.com/3313896/152684178-5fa32cf9-41cd-4ec2-b64f-a7af3439f863.png)
I'm pretty sure that's a key right there

**Comment by psavola** [comment]
Indeed, the original issue doesn't exit. I retried and some times saw keys or pieces of them, depending on where the lich is running.

But just to confirm, is it intentional that it takes quite a long time for the items to get dropped (the spell to take effect)? When I target the spell, the lich stands at the front of the throne. After the spell the lich starts running toward the border of the room. Items apparently get dropped one by one while the lich is moving because they are more or less scattered depending on on the movement and usually not in the same location. Also another thing is that if the key happens to be dropped below a "spell", it's impossible to get the key until the spell has disappeared (e.g. by moving sufficiently far offscreen and coming back).

**Comment by DominusExult** [comment]
I think that is all controlled by usecode and the same thing happens in the original. The upside of it is that this most of the times prevents the keys being buried under the spells.
 It might be something to fix in SIFixes. But OTOH one could argue that the vibrate spell shouldn't be able to vibrate spells out of a liche, to begin with :)
IMO a proper fix should keep that in mind.

**Comment by wench** [comment]
Makes me wonder how frequently people have issues with things getting hidden behind walls. It shouldn't happen often but i can think of  at least 2 occasions where it could happen. Obviously the vibrate spell but also corpses could be inaccessible if a monster/npc dies while hidden behind a wall might be other situations but i can't think of any. Thinking it might be useful to have a key to highlight obscured objects and allow interacting with them when it would be otherwise impossible
