### ISSUE TITLE
iOS exult version : telescope 

### ISSUE THREAD

**Issue by rekom** [exult/exult#144]
At the Lycaeum, if you use the telescope there is no way to exit the view.

**Comment by DominusExult** [comment]
The ESC button should be there in left bottom - at least with the latest TestFlight built 55.
But I noticed that the virtual joystick is flickering there while it should be completely invisible (about to fix that).

**Comment by DominusExult** [comment]
hmm... do you remember what you did before using the telescope? You might have activated something that hid the ESC button so it wasn't there anymore.
I'll see if I can add a check before using the telescope to make sure that the ESC button is there.

**Comment by rekom** [comment]
I'll try it tonight again. I can send you a save game and the spec of my iPad.

**Comment by DominusExult** [comment]
I uploaded a new version to TestFlight that explicitly makes sure that there is an ESC button!

**Comment by rekom** [comment]
You were right, it's flickering, the esc button is present!
