### ISSUE TITLE
dont_pause_game broke UI_close_gumps when Gumps do pause games - since 17 years

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#153]
Copied from our old tracker:
When @wench  implemented that you can have gumps open without pausing the game, he slightly broke UI_close_gumps. Since then it only works when Gumps don't pause the game. When gumps pause the game it doesn't trigger.
For example BG when you have to place the items in front of Penumbra's house. You place the hammer, gumps close, party member reacts.
So a 17 years old regression found.
See this forum thread http://exult.info/forum/viewtopic.php?f=1&t=1774248
and the commit to blame: https://github.com/exult/exult/commit/26847f52bbb7b43097e394da5fd91f0a8fb3a533 (big commit that most code is not about this).
In the forum @drcode1 expressed interest in solving this.

Looking at it again, I *think* I solved it by the following patch
```
diff --git a/objs/egg.cc b/objs/egg.cc
index 102eecc7..43fde7f1 100644
--- a/objs/egg.cc
+++ b/objs/egg.cc
@@ -790,6 +790,7 @@ bool Egg_object::is_active(
 			return area.has_world_point(tx, ty) && deltaz == 0 &&
 			       obj->get_flag(Obj_flags::in_party);;
 	case something_on:
+		gumpman->close_all_gumps();
 		return          // Guessing.  At SI end, deltaz == -1.
 		    deltaz / 4 == 0 && area.has_world_point(tx, ty) && !obj->as_actor();
 	case external_criteria:
```
This makes it work like it does with the original. Placing *ANY* item near an egg that reacts on `something_on` will close the gumps (not only on the correct item). Taking an item from such an egg will trigger and close the gumps again (same in the original). Tested at Penumbra's house and the final black gate scene where you have to place the blackrock items.
it could be placed in a `if ( !gumpman->gumps_dont_pause_game())` but I think it's better to properly closing the gumps even when not in `gumps don't pause game` (even though most (all?) usecode that runs will close the gumps anyway.

**Comment by marzojr** [comment]
Looks good to me, and seems to match what the originals did. Tests in the original do show evidence of a similar special case for this mode that forces gumps to close.

**Comment by wench** [comment]
Let this be a lesson don't be like me and implement a feature without proper testing
