### ISSUE TITLE
UCC: catch error when global flag is not numbered

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#161]
If you make the mistake of forgetting to add a number in the middle of a global flag enumeration, ucc segfaults. It would be nicer if it caught the error. 

Example:
```
enum serpents_hold_flags
{
	STARTED_HOLD_INVESTIGATION = 0x25E,		//Got the mission from John-Paul to find who defaced the statue
	FINISHED_HOLD_INVESTIGATION = 0x261,	//Finished the statue investigation properly, pinning Sir Pendaran as the culprit
	HEARD_ABOUT_RIKY	= 0x277,			//Heard that Tory's baby son was kidnapped by harpies
	RESCUED_RIKY		= 0x278				//Player has rescued Riky (prevents conversation from coming up again)
};
```
if you leave `FINISHED_HOLD_INVESTIGATION` "empty" like this
`FINISHED_HOLD_INVESTIGATION = 	//Finished the statue investigation properly, pinning Sir Pendaran as the culprit`
ucc segfaults. The user who reported it didn't even see the segfault error for some reason. It just silently failed.

**Comment by marzojr** [comment]
I can't seem to reproduce it; I get error messages instead of segfaults.

**Comment by DominusExult** [comment]
I guess it fixed itself or both the reporting user and me used an old ucc.
