### ISSUE TITLE
Schedule Grow_crops is adding wrong frames

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#163]
When you watch the farming you can see that the wrong crops are regrown.
Example Camille in Paws (from 6am until 3pm).
https://github.com/exult/exult/blob/master/schedule.cc#L1802
I'm assigning it to @drcode1, maybe you want to take a look again.

**Comment by drcode1** [comment]
Looking at this today, I see that when you start a new game, some of the 
crops (look for the shortest ones) are of lower frame (< 24), so they 
end up 'growing' into the different-looking plants. Do you know of any 
other areas where a farm is growing different plants?  The corn is of 
frames 24-27.

One thought is that I could examine the crop shapes and see which are 
the most common frames, then only apply the schedule to those.  But I 
suspect the original wasn't that complicated.

**Comment by drcode1** [comment]
I think it's fixed now.
