### ISSUE TITLE
Can't travel to Shrine of Spirituality

### ISSUE THREAD

**Issue by fermix42** [exult/exult#165]
I've already traded information with the wisps and witnessed Alagner's murder.  When I try using the orb of moons to the far southwest, I keep getting a dialogue that says "No Avatar.  Let thyself enter."  I can't figure out how to resolve this issue.  Using the v.1.7.0 snapshot.

**Comment by DominusExult** [comment]
I‘m pretty sure you need to get rid of one of the generators, probably the cube one.

**Comment by psavola** [comment]
At least a couple of walkthroughs mention using the orb to the northwest, not southwest. That may be relevant.

According to the walkthroughs, at least if you follow the story, you are supposed to contact the Time Lord before destroying the sphere generator. Indeed, the path to the sphere generator is supposed to blocked by a teleporter and you need to talk to the Time Lord to gain info how to enchant the hourglass, which in turn requires destroying the tetrahedron generator first. Destroying the sphere generator disables the orb travel completely. The cube generator is last.
