### ISSUE TITLE
[GNU/Linux] Exult creates directories on the user home dir: how to avoid this?

### ISSUE THREAD

**Issue by vanfanel** [exult/exult#166]
Hi there,

I have noticed, time ago, that Exult creates some unwanted directories on my home dir everytime it's run. These are called:

```
blackgate
forgeofvirtue
serpentbeta
serpentisle
silverseed

```

How can I avoid Exult creating these, please?

I simply have all my Ultima 7: Black Gate data in ~/ultima7/blackgate (where I have **static**, **gamedat** and **savegame** from my Ultima 7 install), and I don't need or want any directories outside ~/ultima7.

Can you help, please?

Thanks!

**Comment by DominusExult** [comment]
That's kind of odd as Exult should only create these in the folder .exult in your HOME.
Maybe your .exult.cfg was edited at some point with these folders?
Do you compile Exult from git or are you getting it from a package manager? Maybe the exult PPA for Ubuntu, maintained by Paulo not us, changed something there...

But anyway you can edit .exult.cfg to point at your folders. See http://exult.info/docs.php#path_config_nix

**Comment by vanfanel** [comment]
@DominusExult Thanks for trying to help me :)

The ~/.exult dir has not been created, only exult.cfg was created first time I launched the game, and I didn't edit it.
Note I am not doing a "make install" after building: I am simply copyig exult executable to ~/ultima7/.
Maybe that's the cause? I only run "portable" games, I don't want them putting things in /usr/local/share, etc..

**Comment by Dragon-Baroque** [comment]
Are you building and using a 1.6 Exult instead of a 1.7git ?

I can testify that I build 1.7git on my Linux, that I definitely use `make install`, but I use a rather rich `./configure` so that Exult knows about the target path, with the `--prefix` option :
```./configure --prefix /home/.../Projects/Exult/Reference.gcc.master --enable-pedantic-errors --enable-compiler --enable-mods --enable-exult-studio --enable-exult-studio-support --enable-mt32emu --enable-gimp-plugin        --enable-gnome-shp-thumbnailer --enable-midi-sfx           --enable-nonreadied-objects --with-usecode-debugger=yes --enable-usecode-container --enable-shared```

Could you be missing the `--prefix` option at `./configure` ?

**Comment by vanfanel** [comment]
@Dragon-Baroque Thanks for the detailed instruction and the information.
I am now configuring like this, after adding the missing `--prefix` parameter:

```
./configure --disable-all-hq-scalers --disable-nxbr --disable-tools --disable-timidity-midi --disable-alsa \
--enable-lto --with-optimization=normal --prefix=$HOME/ultima7
```

Then I install it via `make install`, and I end up with the `~/ultima7/bin` and `~/ultima7/share` directories.

Then I copy ultima7's `gamedat`  and  `static` directories into `~/ultima7/share/exult/forgeofvirtue` (I also tried   `~/ultima7/share/exult/blackgate`), but when I run exult in  `~/ultima7/bin , it doesn't seem to be able to find them:
```

Exult path settings:
Data          : /home/manuel/ultima7/share/exult
Digital music : /home/manuel/ultima7/share/exult/music

Looking for 'blackgate' at './blackgate'... but it wasn't there.
Could not open file './blackgate/static/mainshp.flx
Looking for 'forgeofvirtue' at './forgeofvirtue'... but it wasn't there.
Could not open file './forgeofvirtue/static/mainshp.flx
Looking for 'serpentisle' at './serpentisle'... but it wasn't there.
Could not open file './serpentisle/static/mainshp.flx
Looking for 'silverseed' at './silverseed'... but it wasn't there.
Could not open file './silverseed/static/mainshp.flx
Looking for 'serpentbeta' at './serpentbeta'... but it wasn't there.
Could not open file './serpentbeta/static/mainshp.flx
Black Gate   : not found (<BLACKGATE_STATIC>/)
Forge of Virtue   : not found (<FORGEOFVIRTUE_STATIC>/)
Serpent Isle   : not found (<SERPENTISLE_STATIC>/)
Silver Seed   : not found (<SILVERSEED_STATIC>/)

``` 

Do you know what could I be missing, please?

**Comment by Dragon-Baroque** [comment]
With
```
Data          : /home/manuel/ultima7/share/exult
Digital music : /home/manuel/ultima7/share/exult/music
```
Exult begins well, the paths are correct. But then Exult searches the game in the wrong place, it should be
```
 /home/manuel/ultima7/share/exult/forgeofvirtue
```
like it does on my install, not
```
./forgeofvirtue
```

Please try to find all the `exult.cfg`, or the `~/.exult.cfg` and remove them, I guess that they are still holding the paths you complained about first. If this persists anyway, please post the console output of exult from the beginning.
And no, you are right, the uppercase / lowercase does not matter.

Finally, like @DominusExult, I find strange that you do not find `~/.exult.cfg` and that you find a `~/ultima7/config.cfg`. I come back to the first question of my previous post : are you using Exult 1.7.0git ?

**Comment by vanfanel** [comment]
@Dragon-Baroque Thanks for your continued support on this!

I have no `~/.exult.cfg`, I only have `~/ultima7/bin/exult.cfg`, no other exult.cfg files on my `$HOME` dir, that's for sure.
In fact, I deleted `~/ultima7/bin/exult.cfg` and let `~/ultima7/bin/exult` recreate it. 
And it does, but those strange directories on my `$HOME` are still created everytime I run `~/ultima7/bin/exult` .

This is the complete execution log, as you can see I am running version 1.7git:
```

manuel@vader:~/ultima7/bin$ ./exult 
Exult version 1.7.0git
Built at: Mar 30 2022 20:30:10
Compile-time options: USE_FMOPL_MIDI, HAVE_ZIP_SUPPORT
Compiler: GCC 10.2.1 20210110

Platform: Linux version 5.10.0-12-amd64 
Exult path settings:
Data          : /home/manuel/ultima7/share/exult
Digital music : /home/manuel/ultima7/share/exult/music

Looking for 'blackgate' at './blackgate'... but it wasn't there.
Could not open file './blackgate/static/mainshp.flx
Looking for 'forgeofvirtue' at './forgeofvirtue'... but it wasn't there.
Could not open file './forgeofvirtue/static/mainshp.flx
Looking for 'serpentisle' at './serpentisle'... but it wasn't there.
Could not open file './serpentisle/static/mainshp.flx
Looking for 'silverseed' at './silverseed'... but it wasn't there.
Could not open file './silverseed/static/mainshp.flx
Looking for 'serpentbeta' at './serpentbeta'... but it wasn't there.
Could not open file './serpentbeta/static/mainshp.flx
Black Gate   : not found (<BLACKGATE_STATIC>/)
Forge of Virtue   : not found (<FORGEOFVIRTUE_STATIC>/)
Serpent Isle   : not found (<SERPENTISLE_STATIC>/)
Silver Seed   : not found (<SILVERSEED_STATIC>/)
Checking rendering support
 Windowed
 640x480         8 bpp ok 16 bpp ok 32 bpp ok
 800x600         8 bpp ok 16 bpp ok 32 bpp ok
 1024x768        8 bpp ok 16 bpp ok 32 bpp ok
 1280x720        8 bpp ok 16 bpp ok 32 bpp ok
 1366x768        8 bpp ok 16 bpp ok 32 bpp ok
SDL Reports 640x400 16 bpp and 32 bpp windowed surfaces are not OK. Windowed scalers may not work properly.
Creating AudioMixer...
Audio opened using format: 22050 Hz 2 Channels
Timbers Precached: On play only
OGG Vorbis Digital Music: Disabled
Trying: `FMOpl'
Success!
Midi Output: Enabled
Destroying AudioMixer...
Destroying MidiDriver...
```

**Comment by Dragon-Baroque** [comment]
@vanfanel, I think I have an idea.

Since you run `./exult` from its `bin` folder and that is the place where you find the `exult.cfg,` in other words, since the `exult.cfg` is created in the current directory, that might mean that Exult was built without a proper recognition of your _operating system_.
Normally `./configure` detects properly the operating system and sets a variable called `WINDOWING_SYSTEM`.
It should take the value `-D_WIN32` on Windows, `-DMACOSX` on MacOS and iOS, and `-DXWIN` on Linux.

The variable `$(WINDOWING_SYSTEM)` is present in all Makefiles, to be passed as a C++ #define to the gcc compiler.
At the end of ./configure, the value of this variable, along with many others, is written into all Makefiles.

You could take a look into any Makefile just after the build has completed, and you normally should find
```
WINDOWING_SYSTEM = -DXWIN
```
around line 400 in any Makefile.

In fact I suspect that what you have is 
```
WINDOWING_SYSTEM = 
```
meaning Operating System not recognized.

To proceed further if that is indeed the case, I am logging here the frst three messages of ./configure on my Linux, dealing with the recognition of the Operating System :
```
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
```
Would you please compare with a run of ./configure on your PC ?

**Comment by vanfanel** [comment]
@Dragon-Baroque I think you solved the mistery (and it was my fault, because I didn't think that my custom build process would be causing this).

Now, the explanation:

I forgot to mention that, before I run `autogen.sh` or `configure`, I have to edit `configure.ac` and manually change `WINDOWING_SYSTEM="-DXWIN"` to `WINDOWING_SYSTEM=""`

Then I do:
```
./configure --disable-all-hq-scalers --disable-nxbr --disable-tools --disable-timidity-midi --disable-alsa \
--enable-lto --with-optimization=normal --prefix=$HOME/ultima7

```
...which results on:

```
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu

```
Which looks fine, apparently, BUT is somehow causing that the resulting `exult` executable creates these strange directories at `$HOME` and not being able to find de game data files.

SO, after rebuilding with the original configure.ac, the resulting executable doesn't create the strange directories anymore, and is able to find the game data:
```

Data          : /home/manuel/ultima7/share/exult
Digital music : /home/manuel/ultima7/share/exult/music

Looking for 'blackgate' at '/home/manuel/ultima7/share/exult/blackgate'... but it wasn't there.
Could not open file '/home/manuel/ultima7/share/exult/blackgate/static/mainshp.flx

```

BUT there is a motivation for me to edit configure.ac and disable `WINDOWING_SYSTEM="-DXWIN"`: the system on which I play my GNU/Linux games does NOT have an X11 or Wayland server, it works with SDL2 on KMS/DRM.
That means I can't let the buildsystem link exult agains X11, hence I disable it with `WINDOWING_SYSTEM="-DXWIN"`.

So, I believe that the problem is that the exult buildsystems considers linux=X11, and that's not true (it has never been true, in fact). KMS/DRM does not have any linking requeriments: exult links against SDL2 and that's all.

So, could that be fixed so I can build a Linux version without having to disable  `WINDOWING_SYSTEM="-DXWIN"`?
The game shouldn't know about windowing system: that's SDL2 point.

**Comment by wench** [comment]
Unless I'm mistaken the XWin stuff is used for exult studio support. There should be a configure option to disable exult studio support. I'd suggest trying that and seeing if it removes the xwin dependency.

**Comment by Dragon-Baroque** [comment]
@wench, There is indeed an option to _enable_ Exult Studio build, this is `--enable-exult-studio` and there is an option to _enable_ the binding of Exult to Exult Studio, this is `--enable-exult-studio-support`. @vanfanel uses neither.

@vanfanel, I think the final word should reside in @DominusExult. But unless he contradicts me, the following sentence is true, and has been a work in tandem between him and me the past year :

On Linux, XWIN no longer requires X11 and other libs, _unless you enable the binding of Exult to Exult Studio_.

So @vanfanel I beg you to try to build and run Exult with the regular `configure.ac`, it will claim `XWIN`, but this no longer requires X11. I have just tested an Exult build with and without the support to Studio, and indeed, without the support, the `libX11` is no longer required by `exult.`

**Comment by Dragon-Baroque** [comment]
@DominusExult @vanfanel @wench : 
In fact XWIN has become a synonym for non MacOS Unix : Linux, Open + Free + Net BSD, Solaris ...
On Linux it no longer implies X11 although on the other Unixes it still does.

@DominusExult :
The X11 dependency on Linux when building the Studio support into Exult was added by you in 2010 by commit d6722ab22 to fix some linking problems on some Linuxes.
Well, I have rebuilt a full Exult + Studio + Exult Studio support on my Linux with this dependency removed, and the link step passes, then Exult and Studio work.
Do you recall what Linuxes were affected by the problem, back then ? Could we remove that dependency ?

@vanfanel :
This is a fine observation that SDL can reach the DRM hardware directly.
What is your experience - ease of use, performance, user input, window [ if ever ] management, or is it full screen only - of using Exult or actually any SDL application over the SDL to KMS DRM driver, please ?
And is there a relationship between this variant of SDL and your disabling the HQ scalers in Exult ?

**Comment by DominusExult** [comment]
Found it! No thanks to SF for changing bug/patch id numbers at some point ;(

https://sourceforge.net/p/exult/patches/82/

I have no opinion on this ;)

**Comment by vanfanel** [comment]
@Dragon-Baroque 
I will try to answer the best I can :)

-Ease of use: Same as on any GNU/Linux system, but a small code change has to be made manually to avoid segfault on quit:
You have to modify exult.cc, commenting out the line
`std::atexit(SDL_Quit);`
..and adding `SDL_Quit();` at the end of the `Play()` function, just before `return(0);`

That's because `atexit(SDL_Quit);` doesn't work well at all without X11, as has been reported a lot of times in different places:
https://github.com/dosbox-staging/dosbox-staging/issues/336
It's NOT specific to KMS/DRM, since it fails with Wayland too, so it will sooner or later hit exult massively and not only on my usercase.

Using KMS/DRM, things are only fullscreen, no winding manager at all. 
Performance is the same as it would be on X11 given the same hw/exult configuration. Less laggy, but performance-wise it's the same.

On the Raspberry Pi 4, however, CPU usage is a bit high if the interlaced scaler at 2x is used, but it's to be expected I guess. 
My only complain (not Pi4 specific) is that using 1280x720 display mode (fullscreen ON) and game area set to AUTO, the initial menu, logos and intro screen are confined to a small area on the center of the screen. I guess that's because they are raster bitmaps and the engine is not scaling them.

As for relationship between this variant of SDL and disabling the HQ scalers, no, there's not relationship, I just dislike artificial scalers because they manipulate how the game arts look AND are slow to build, so I leave them out to save time and get an smaller executable with only feautures I use.

As for the pictures, it's late here and artificial light won't look very good with my camera, so I will upload them wgen I can, during day :)

**Comment by vanfanel** [comment]
The Exult engine is pre-scaling the screen in software, instead of letting SDL2 do it for free (SDL2 uses OpenGL/ES under the hood), so that's taxing the Pi4 CPU massively if I use SCALE 4X in order to fill the screen on a modern display.

**Comment by Dragon-Baroque** [comment]
@vanfanel, in effect, you are running Exult on a Pi 4. This is an honorable achievement, worth a claim of support by Exult, I am quite sure.

You face 3 issues, let me try to make a synthesis :

1. Because there is no X11 or Wayland, and no Window Manager either on the PI 4 Linux, you attempted to compile with `-DXWIN` off. This caused a mass of problems with file paths since `-DXWIN` is the way now Exult decides it runs under a non MacOS Unix, including Linux.

Answer : By now, `-DXWIN` no longer adds `libX11` to the SYSLIBS under Linux.
Consequence : You might help us by building Exult for PI 4 normally, I mean without the `-DXWIN` removal, test whether it runs on the PI, and report the experience to us.

2. Because the PI is a rather weak Processor, you build Exult without the HQ scalers and advise us to instead rely on SDL native scaler that uses OpenGL.

Answer : If Exult is running FullScreen [ Video Options gump ], has HighDPI left enabled [ Video Options gump ] and is using the _neutral_ scaler "Point x1" [ Video Options gump ], then Exult invokes automatically the `SDL_RenderSetLogicalSize` native scaler to reach the screen resolution.
Consequence : Could you please also test this on a non modified build, report whether that is satisfactory, and whether Exult starts properly and switches to fullscreen alone or whether you have to alter the `config.cfg` beforehand.

3. The `SDL_Quit` hooked to the `atexit` crashes Exult at exit.

Answer : You have your own Fork of Exult. Would you mind preparing a Pull Request of the code change ?

Finally, I think this discussion has overflown the original discussion thread title.
Would you mind reopening an issue around `Exult support of the Raspberry PI` or similar ?
