### ISSUE TITLE
Website hosting

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#167]
Since SourceForge is just not willing to move on I've looked into a way to host our website in a way that is more future proof for our project.
The aim was to find a host that wouldn't rely on one of us to pay for the hosting, not because I wouldn't want to pay for it but because it would be fatal if the one paying for it were not able to pay for it suddenly.
So the one that seems to be reliable and especially opensource friendly is https://www.tuxfamily.org.

I created an account and set up the Exult project. ~~Before I slowly begin to migrate the website and the forum I wanted to ask @drcode1, @marzojr and @wjp if they agree and that they register there as well, so I can add them as admins to the project.~~
Going there would mean we could have a secure website, the forum would actually be more snappy and it would finally work correctly by being able to automatically send mails (for registration confirmations etc...).

**Comment by DominusExult** [comment]
I just find I have no time to set up and maintain the forum etc. on tuxfamily.org. And our forum on the SourceForge is no fun to maintain as SF cut so many features by not allowing mail. And it is slooooooowwwww.

Therefore I propose to moving to [Github Discussions ](https://github.com/exult/exult/discussions). I opened that and added two announcements and a poll.
Pros: mark down, direct referencing of issues & commits, highlighting a developer, no need to maintain it
Cons: our forum look is of course not here, another archive (along with the old bug tracker on SF)

What do you think? @drcode1 @marzojr @Dragon-Baroque @wench

**Comment by drcode1** [comment]
Sounds just fine to me.
