### ISSUE TITLE
Choice of CLang or GCC, Review of configure.ac.

### ISSUE THREAD

**Issue by Dragon-Baroque** [exult/exult#185]
The GitHub Workflows use
- CLang for MacOS in `ci-macos`,
- GCC for Windows in `ci-windows`,

Whereas the `ci-linux` Workflow has two paths, one with CLang, one with GCC.
But its two paths end up in GCC anyway [ both execution logs invoke `g++`, never `clang++` ] because `configure.ac` chooses the compiler based on the operating system, not based on the CC/CXX or the OVERRIDE_CC/CXX environment variables. 

What is your position about the worthiness of supporting CLang for Linux ? I mean
- Do we drop the CLang path in `ci-linux` ?
- Or do we make it work ?

In my own development tree, I provide the choice of CLang and GCC in `configure.ac`.
Would you like that I work on adapting this to the `ci-linux` workflow to really support CLang ?

**Comment by DominusExult** [comment]
Probably getting the linux workflow to really test clang would be preferable.

(As for macOS, the Apple provided compiler has for years only been clang - though you can get gcc via the package managers macports, brew)

**Comment by marzojr** [comment]
I agree with Dominus.

**Comment by Dragon-Baroque** [comment]
First step : remove warnings in `uclex.ll` and `ucparse.yy` as `-Wredundant-tags` does not exist in CLang.

The MacOS builds succeed with warnings, whereas my own CLang builds fail because the warnings are propagated to errors.

**Comment by rofl0r** [comment]
> But its two paths end up in GCC anyway [ both execution logs invoke g++, never clang++ ] because configure.ac chooses the compiler based on the operating system, not based on the CC/CXX or the OVERRIDE_CC/CXX environment variables.

good practice is to use CC/CXX env vars if provided, and only if unset use a sensible default (which is usually `cc` for CC and `c++` for CXX, these are usually symlinks to gcc/clang or g++/clang++ on properly configured distros/systems)

**Comment by Dragon-Baroque** [comment]
Second step : alter `./configure.ac` to support CLang set into `OVERRIDE_CXX` as done in by the `ci-linux` workflow, and to handle also the `--with-cxx` option.

Pull Request #187, also to take advantage of the Compilation checks before merge.

**Comment by Dragon-Baroque** [comment]
Still looking at the `configure.ac` and the `Makefile.am`.

Two questions, please :

1. In all `AM_CPPFLAGS` in the `Makefile.am` there is a `$(INCDIRS)` used but nowhere set. What is its purpose ?

2. In the `Makefile.mingw`, the variables `OPT_LEVEL` and `WARNINGS` are separate. Whereas in `configure.ac`, the variables `DEBUG_LEVEL` and `WARNINGS` are merged, line 851 : `DEBUG_FLAGS="$DEBUG_FLAGS $WARNINGS"`. But both are exported and there are three `Makefile.am` that put both variables into the `AM_CPPFLAGS` : `conf/Makefile.am`, `usecode/ucxt/Makefile.am`, `usecode/ucxt/src/Makefile.am` and that duplicates the `WARNINGS` content. Should we remove the export of `WARNINGS` and remove `WARNINGS` from the three `Makefile.am` or should we align somehow the logic of `Makefile.mingw` and the logic of `configure.ac` + `Makefile.am` ?

**Comment by marzojr** [comment]
1. I think that INCDIRS is for allowing some unusual setups to work that is passed from the command line/environment.
2. I think I prefer the way it is done in Makefile.mingw a tiny bit more.

**Comment by Dragon-Baroque** [comment]
Made `pkg-config` mandatory by Merge Request #232.

@marzojr  next, I shall complete the alignment of `DEBUG_LEVEL` vs `WARNINGS` in `configure.ac` like `Makefile.mingw` along your wish.

**Comment by marzojr** [comment]
If you are willing to, yes please 🙂

**Comment by Dragon-Baroque** [comment]
Pull Request #233.
After the compilations passed, I merged it.
@marzojr you must do that differently, since I ended up with a the commit and a merge commit above, but you merged my previous one without a top merge commit. How did you do, please ?

**Comment by Dragon-Baroque** [comment]
Pull Request #234.

This one is to silent the CLang++ compiler over SDL because of some old style cast.

I leave you @marzojr and @DominusExult to review it. For the moment, I do not expect to merge it myself.

**Comment by marzojr** [comment]
> Pull Request #233. After the compilations passed, I merged it. @marzojr you must do that differently, since I ended up with a the commit and a merge commit above, but you merged my previous one without a top merge commit. How did you do, please ?

I always do a 'rebase and merge' since it leaves the history cleaner.

**Comment by Dragon-Baroque** [comment]
> I always do a 'rebase and merge' since it leaves the history cleaner.

I have found and used it for my latest PR. Thanks
