### ISSUE TITLE
sdlrwops*.* in makefile.am and makefile.common placed incorrrectly?

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#202]
@ceckak I noticed the autogen.sh warning https://github.com/exult/exult/runs/6181754521?check_suite_focus=true#step:4:21
and to fix this I created this patch:
[sdlrwops_makefiles.diff.txt](https://github.com/exult/exult/files/8566313/sdlrwops_makefiles.diff.txt)

This runs through autogen/ configure and builds just fine. Can you check whether this doesn't clash with your Android build?

**Comment by ceckak** [comment]
@DominusExult I tested a clean android build with your patch applied and everything worked fine.  Thanks for cleaning this up.
