### ISSUE TITLE
Sorry to bother you about this

### ISSUE THREAD

**Issue by i30817** [exult/exult#213]
seems like ubuntu might be screwing up bison uclex.cc again (i think i recall this was a problem on this project).

in short, in Jammy ubuntu buildbot, my autobuild is failing with `cc1plus: fatal error: uclex.cc: No such file or directory`

Here is the failing buildlog on jammy: https://launchpadlibrarian.net/601176924/buildlog_ubuntu-jammy-amd64.exult_1.7.0+svn20220513~ubuntu22.04.1_BUILDING.txt.gz

Here is the succeeding buildlog on Impish:
https://launchpadlibrarian.net/601177154/buildlog_ubuntu-impish-amd64.exult_1.7.0+svn20220513~ubuntu21.10.1_BUILDING.txt.gz

If you check the contents:

When earlier in the build uclex.cc was supposed to be built on the failing log:
```
/bin/bash ../../ylwrap uclex.ll lex.yy.c uclex.cc -- :  
```

In the building log:
```
/bin/bash ../../ylwrap uclex.ll lex.yy.c uclex.cc -- flex  
```

So ... what is going on?

**Comment by i30817** [comment]
The only recent thing that mentions this file is this commit: https://github.com/exult/exult/commit/f3ce356276ff474e639f92fb339fefb04dfeabdf

**Comment by i30817** [comment]
Oh right, earlier in the build:
```
checking for lex output file root... lex.yy
checking for lex library... none needed
checking for library containing yywrap... no
configure: WARNING: yywrap not found; giving up on flex
```

yywrap? They changed names, or just extracted the flex part?

**Comment by Dragon-Baroque** [comment]
I switched Linux Fedora 35 to Fedora 36 2 days ago. Same failure. Bottom reason is 
- autoconf went from 2.69 to 2.71 and
- this triggered the change into `configure.ac` from commit 851ca3880  by @DominusExult, using `AC_PROG_LEX([yywrap])`

I could make the build work again by replacing it by `AC_PROG_LEX([noyywrap])`.
@i30817  Could you check on Linux ? @DominusExult, could you check on MacOS ?

**Comment by i30817** [comment]
It builds with the usecode compiler (here in focal, would need to make a quilt patch to the build repository to check in the others). My autoconf is still 2.69 here though.

**Comment by i30817** [comment]
Seems like it's all go. They all built on amd64 (i386 is deprecated on ubuntu and i don't think this would make a difference for amd64, that, fwiw, is still building)

https://code.launchpad.net/~exult-team/+recipe/exult-daily

**Comment by i30817** [comment]
BTW i noticed that the build got rid of exultmsg.txt - that was another build failure before i sorted it out.


But i also noticed this commit also removed many more .data files for android:

https://github.com/exult/exult/commit/818d0708f0307bf89c98d33e0e979ba0b029f78e

What's going on here, are these .data files not available in android only for some reason? Or are they also unnecessary for pc now?

**Comment by marzojr** [comment]
> But i also noticed this commit also removed many more .data and .vga files for android:
> 
> [818d070](https://github.com/exult/exult/commit/818d0708f0307bf89c98d33e0e979ba0b029f78e)
> 
> What's going on here, are these files not available in android only for some reason? Or are they also unnecessary for pc now and are in the flex files (like the commit for exultmsg.txt says)?

These "removed" data files are bundled inside other data files, and they are only ever needed unbundled during build.

**Comment by i30817** [comment]
So let me get this right.

the `*.data` files are for the dissasembler which i install with exult studio, so they should go to that second install listing i have there.

And the vga files `bg_paperdol.vga` and `bg_mr_faces.vga`? Are they, like exultmsg.txt now inside one of the *.flx files, so i don't need to copy them explicitly?

**Comment by marzojr** [comment]
> the `*.data` files are for the dissasembler which i install with exult studio, so they should go to that second install listing i have there (used when exult studio is installed - and requires exult as a dependency), not normal exult? Ie: delete `u7bgintrinsics.data` and `u7siintrinsics.data` from the first listing and replace all the .data files in the second listing by `usr/share/games/exult/*.data` to copy them all?

Correct on all accounts.

> And the vga files `bg_paperdol.vga` and `bg_mr_faces.vga`? Are they, like exultmsg.txt now inside one of the *.flx files, so i don't need to copy them explicitly?

Correct on almost everything: the only exception is that these vga files have *always* been inside exult_bg.flx and you *never* had to copy them explicitly.

**Comment by i30817** [comment]
Ok. Everything is done then, for me. When you fix the original problem (the solution appears to have no problems in linux at least), i'll revert that commit on my end and this can be closed.

**Comment by marzojr** [comment]
> The internet says to use `%option noyywrap` on the makefile somewhere (here: [paxed/dgamelaunch#4](https://github.com/paxed/dgamelaunch/issues/4) )

For reference, `%option noyywrap` is not on the makefile, but on the `.ll` file passed to flex (see [here](https://westes.github.io/flex/manual/Options-Affecting-Scanner-Behavior.html#Options-Affecting-Scanner-Behavior)).

The description of `noyywrap` option to `AC_PROG_LEX` (see [here](https://www.gnu.org/software/autoconf/manual/autoconf-2.70/html_node/Particular-Programs.html#AC_005fPROG_005fLEX)), specifically this bit:

> Usage of AC_PROG_LEX without choosing one of the yywrap or noyywrap options is deprecated. It is usually better to use noyywrap and define the yywrap function yourself, as this almost always renders the LEXLIB unnecessary.

This indicates that it is the correct option: we do define a `yywrap` ourselves.

**Comment by DominusExult** [comment]
Sorry for breaking and thanks for fixing it!
