### ISSUE TITLE
Enemies in the Black Gate room can see and attack you when you are invisible.

### ISSUE THREAD

**Issue by fragmental** [exult/exult#22]
Enemies in the Black Gate room can see and attack you when you are invisible.  I haven't tested to see if other enemies can see you that shouldn't be able to.  I noticed this when attempting an any% speedrun.

**Comment by rofl0r** [comment]
are you talking about the original, or exult ? is this a bug report about exult doing it, when it shouldn't, or *not* doing it, when it should ?

**Comment by fragmental** [comment]
@rofl0r In the original game, they cannot see you and won't attack you, if you are invisible.  In Exult, they will see you and will attack you.  I'm using the latest build.

**Comment by DominusExult** [comment]
Something is wrong at
https://github.com/exult/exult/blob/master/combat.cc#L328
If I delete` !see_invisible &&` it works fine but why is the check for see invisible failing there?

Attaching a savegame in the final room. Just set the flag to invisible to test.

[exult71bg.sav.zip](https://github.com/exult/exult/files/4571381/exult71bg.sav.zip)
