### ISSUE TITLE
Image_window::VideoModeOK() usage/implementation inconsistent

### ISSUE THREAD

**Issue by ceckak** [exult/exult#220]
As noted in https://github.com/exult/exult/pull/217, `VideoModeOK()` is being called with `bpp` and `flags` parameters to check whether a specified video mode is supported and/or find the closest supported color depth, but the implementation completely ignores these parameters and always simply returns the highest color depth supported for the given resolution (or 0 if the resolution is unsupported).

The function was introduced in https://github.com/exult/exult/commit/b89a22a9cd926aa7e711fb6073804e18a538e98f, which was trying to replicate SDL 1.2's [`SDL_VideoModeOK()`](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlvideomodeok.html) using SDL 2.0 APIs.  That original implementation also lacked any support for the `bpp` and `flags` parameters, and the calling code that uses them dates back to SDL 1.2.

By and large, the current codebase appears to be working fine (aside from https://github.com/exult/exult/pull/217), but is somewhat confusing/misleading.  I'd like to clean this up, but would like some input on which direction to go with it.

- One option is to remove the `bpp`/`flags` parameters from `VideoModeOK()` and update the calling code to retain exactly the current behavior, but cleaning up the confusion of using these flags that are ignored
- Another option is to add more logic to `VideoModeOK()` to better emulate the original behavior of `SDL_VideoModeOK()`

Given that these flags are only present for consistency with the deprecated `SDL_VideoModeOK()`, I'd suggest going with the first option to avoid regressions and make the codebase easier to understand.

Thoughts?

**Comment by DominusExult** [comment]
I think option 1 would be best. I was trying to fix some not working stuff there before and barely managed to understand what's going on there 🤷‍♂️

**Comment by ceckak** [comment]
Thanks - I'll get started on it and see how it shakes out.

**Comment by DominusExult** [comment]
Did not see any reason why no to merge #222 :)

One question as you have dived into imagewin.cc: on macOS and iOS I always (since the switch to SDL2, I think) get the "Couldn't create inter surface..." triple in bool Image_window::create_scale_surfaces:
```
SDL Reports 960x720 windowed surfaces are not OK. Attempting to use 16 bpp. anyway
Coldn't create inter surface: Unknown pixel format
SDL Reports 960x720 16 bpp windowed surface is not OK. Attmempting to use 16 bpp anyway.
Coldn't create inter surface: Unknown pixel format
SDL Reports 960x720 32 bpp windowed surface is not OK. Attmempting to use 32 bpp anyway.
```
Do you have any idea what's going wrong there?

**Comment by ceckak** [comment]
Not sure off the top of my head, but I'll try to replicate it on macOS and dig into it.  From my digging through that code so far, it seems like there is a lot of complexity around trying to set specific color depths, and I'm not clear how much value that adds.  We could simplify the code substantially if we just let SDL pick the optimal color depth and used it.  I'm not sure if there are historical reasons we needed to specify color depths, and whether they are still relevant.  In any case, I'll try to reproduce.

**Comment by DominusExult** [comment]
I think it might have been relevant back in the early 00's but nowadays SDL2 might just be best equipped to choose the color depth.
Maybe @wench remembers?

CovertyScan also shows that there are now two dead ends in the code as !ok_rgp and !ok_pal can never be true (after imagewin.cc:432)
```
** CID 1518356:  Control flow issues  (DEADCODE)
/imagewin/imagewin.cc: 440 in Image_window::static_init()()


________________________________________________________________________________________________________
*** CID 1518356:  Control flow issues  (DEADCODE)
/imagewin/imagewin.cc: 440 in Image_window::static_init()()
434
435     	if (!ok_pal && !ok_rgb)
436     		cerr << "SDL Reports no usable fullscreen resolutions." << endl;
437     	else if (!ok_pal)
438     		cerr << "SDL Reports no usable paletted fullscreen resolutions." << endl;
439     	else if (!ok_rgb)
>>>     CID 1518356:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach this statement: "(std::cerr << "SDL Reports ...".
440     		cerr << "SDL Reports no usable rgb fullscreen resolutions." << endl;
441
442     	config->value("config/video/force_bpp", force_bpp, 0);
443
444     	if (force_bpp != 0 && force_bpp != 16 && force_bpp != 8 && force_bpp != 32) force_bpp = 0;
445     	else if (force_bpp != 0) cout << "Forcing bit depth to " << force_bpp << " bpp" << endl;

** CID 1518355:  Control flow issues  (DEADCODE)
/imagewin/imagewin.cc: 438 in Image_window::static_init()()


________________________________________________________________________________________________________
*** CID 1518355:  Control flow issues  (DEADCODE)
/imagewin/imagewin.cc: 438 in Image_window::static_init()()
432     		cerr << "SDL Reports 640x400 windowed surfaces are not OK. Windowed scalers may not work properly." << endl;
433     #endif
434
435     	if (!ok_pal && !ok_rgb)
436     		cerr << "SDL Reports no usable fullscreen resolutions." << endl;
437     	else if (!ok_pal)
>>>     CID 1518355:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach this statement: "(std::cerr << "SDL Reports ...".
438     		cerr << "SDL Reports no usable paletted fullscreen resolutions." << endl;
439     	else if (!ok_rgb)
440     		cerr << "SDL Reports no usable rgb fullscreen resolutions." << endl;
441
442     	config->value("config/video/force_bpp", force_bpp, 0);
443

```

**Comment by wench** [comment]
The deadcode thing seems to just be a side effect of how the new code works compared to the old code. The old code explicitly checked the different mode types separately setting ok_pal and ok_rgb appropriately while the new code makes no distinction setting both if a mode is ok, so ok_pal and ok_rgb are now always the same breaking the logic of the warning messages. The dead code paths can probably just be removed as they no longer make sense with the new code.

**Comment by DominusExult** [comment]
@wench do you remember the reason for the complexity of getting the correct color depth?

**Comment by wench** [comment]
TBH I don't remember but I'd hazard a guess it was for performance reason to avoid doing multiple pixel format conversion unnecessarily. For Slower early 2000s and late 90s systems you kind of wanted that. Especially when using scalers that were quite demanding on systems at the time, You really didn't want exult and sdl doing colour format conversions.
