### ISSUE TITLE
ES: modifying shapes in mods not saveable - due to SDLRWOPS changes? Windows

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#223]
Adding a frame to a shpe in shapes.vga and then "saving all" results in an Exult Studio Prompt:
`Error writing '<PATCH>/shapes.vga'`

Since this works in 1.8 but not current git I assume this is is also caused by the changes of the Android port in U7open or so.

Steps to reproduce:
- Start Exult with a mod, e.g. BG Keyring mod
- start Exult Studio from exult via ctrl-alt-m
- in Studio right click a shape in shapes.vga and export any frame from that shape
- right click the shape again and select `new frame`
- right click that frame and select `import frame` and select the frame you exported above
- in Exult Studio menu click file -> save all

tagging @ceckak and @marzojr

**Comment by ceckak** [comment]
Will take a look.  I haven't played with ES before, so may take a bit to get up to speed.

**Comment by DominusExult** [comment]
Just had the time to test on macOS and it's not reproducible there, so maybe Windows only.

**Comment by ceckak** [comment]
Ok - thanks for narrowing it down.  I have a windows desktop gathering dust and can try to get a build environment set up there.

**Comment by DominusExult** [comment]
Hmm, I guess with dcbd0318 it's useless to test as mods were not working before

**Comment by ceckak** [comment]
Finally got my windows build environment set up and can run exult and studio successfully.  I wasn't able to launch studio from inside exult and am not sure why yet - maybe a problem with passing the key sequence through the VNC session I'm using to remote-access windows.

However, I manually opened the keyring-modded forgeofvirtue game, edited the body and replaced it with the spaceship, saved all, and I see it show up in the game:
<img width="768" alt="Screen Shot 2022-07-01 at 9 56 12 PM" src="https://user-images.githubusercontent.com/87736037/176987144-f40f28ab-72b7-44bc-bfe3-8b7bd8f9a7bb.png">

This implies there's something specific/unique about the sequence you are using that is triggering the bug.  I'll go back and try again directly on the console this weekend.

**Comment by DominusExult** [comment]
Yes, you need to do the steps I wrote above. Or doing the shape exchange while Exult is connected to Exult Studio (still need to be in map edit mode).

**Comment by ceckak** [comment]
Didn't have any luck getting studio to launch with 'ctrl-alt-m', even when working directly on the windows console.  Also not having any luck getting studio to connect to an exult that is already running.  Not sure what I've got wrong, but I'll spend some time rummaging through the code to learn more about how studio gets launched and how the server communications work...

**Comment by ceckak** [comment]
Ok - I take it back.  Not sure what I was doing differently before, but I was able to fully reproduce the issue with the steps described above.  Will update the issue after I debug and identify a fix.

**Comment by marzojr** [comment]
I traced the issue to the fact that the underlying APIs used by SDLRWOPS apparently is opening the files in locked exclusive mode in Windows, which prevents ES from saving it while Exult is running. Fixing this also led me to a segfault when the shape files were reloaded, which I subsequently fixed.

**Comment by ceckak** [comment]
Thanks for chasing this down.  Between vacations and awkward access to my windows box, I'd been making slow progress.  The locked exclusive mode matches the behavior - ES doesn't use SDLRWOPS, but Exult does, so has the files locked when spawning ES from inside the game.

It looks like your fix simply tries to use normal ifstream access first, and falls back to SDLRWOPS if that fails.  Should be fine.  I may dig into SDL and see if I can talk them into changing the file locking behavior and/or make it configurable.

**Comment by marzojr** [comment]
> It looks like your fix simply tries to use normal ifstream access first, and falls back to SDLRWOPS if that fails.

From what I saw of SDLRWOPS source code, they try to open the file using C stdio, then they try using the JNI to open special paths. So there is a slight penalty on Android due to trying to open the file twice from the filesystem, but it should work basically the same otherwise.

If the 'open twice' behavior turns out to be too heavy a burden, we can also restrict the normal ifstream usage to only when USE_EXULTSTUDIO is defined.
