### ISSUE TITLE
Set up a Discord server

### ISSUE THREAD

**Issue by eliyo** [exult/exult#225]
As of today, it seems there is no way to get in contact with anyone interested in this project if you're not already part of the members. The registration on the forums is down, and the IRC channel is deserted. Please put in place a Discord server for the project which is the most convenient way to build communities nowadays.

**Comment by tristantarrant** [comment]
GitHub discussions is also a possibility

**Comment by eliyo** [comment]
> GitHub discussions is also a possibility
GitHub Discussions may be a great replacement for the forums however I am not sure regarding the chat. Another thing to consider is Discord generates so much community attraction it could contribute to a boost of popularity and interest in this project.

**Comment by DominusExult** [comment]
Irc is usually manned by Marzo and me and the forum registration IS wonky but I activate new users as soon as possible.
I don't think adding a Discord will help. Chat is not as everlasting as a forum post or Guthub issue.
And someone would need to be present there as well

**Comment by marzojr** [comment]
To be fair, there are Discord/IRC bridges that can be set up, so they would not be mutually exclusive. I would not oppose a Discord server for Exult.

**Comment by eliyo** [comment]
I agree with @DominusExult relatively to the archiving nature of Discord which is not as good as forums. This is usually the main reluctance ppl have over Discord when they're used to forums. This is however mitigated in Discord with ability to pin messages, the search feature as well as threads. I don't see Discord as a replacement to forums but a complement. 

My suggestion for the time being would be to experiment and set up a Discord server, advertise it on the website/social networks and see how it goes. Have a few knowledgeable people connected to answer questions. I can be moderator if you wish as I am very often connected on Discord for other purposes.

**Comment by DominusExult** [comment]
As for your registration attempts, please do read the sticky topics, especially this one http://exult.info/forum/viewtopic.php?f=1&t=1791246&sid=44ae024ffe91fd39432bf0a4e943e6f5

**Comment by eliyo** [comment]
@DominusExult I tried already to login but it failed, and I cannot reset my password. Just wondering how long it will take you guys to realize there is a real problem in the way communication works on this project! I proposed you an alternative that could solve a bunch of issues, it's on your side now!

**Comment by DominusExult** [comment]
what is your user name? If it is olio, I activated the account on the same day. But if you requested a password reset, it's basically made worse by our problem with the SF server that doesn't send emails (activation or email resets or whatever). If you tell me your username, I can "manually" send a new password to the registered email address which you can then change.

> Just wondering how long it will take you guys to realize there is a real problem in the way communication works on this project! I proposed you an alternative that could solve a bunch of issues, it's on your side now!

It's really not necessary to be like that, vice versa we could say we offered you ways to communicate with us which work and people use. That the forum is not working optimal right now is obvious ever since we set up the new forum, hence the sticky posts that cover this.

We could set up a Discord server and an IRC bridge but that takes time. Time that is lacking, especially as I would need that time to migrate the forum to a new server (see #167). Also Github now offers some "Discussion" tab that could be activated... dunno

**Comment by eliyo** [comment]
@DominusExult I just tried to login to the forum and it worked! Not sure why it didn't work last time I did, did you do something recently? Anyway, at least this is working now.

Sorry I didn't mean to be rude, I'd just wish you'd realize that things change and forums and IRC and just not the way to get people attracted to your project in 2022. There are things really interesting in what you guys have built, I have recently seen the articles on Yolu's Gaming Blog and they are fantastic, thinking we could extend BG/SI and even make total conversions is simply awesome!

I went to IRC last weekend and tried to get an answer to the 4 or 5 ppl there who were connected, I never got any. So what would be the point of bringing IRC to Discord? This may be done if technically feasible, but I really don't see anything relevant in doing this. I think the community and the project could greatly benefit from having up-to-date community building tools, and this is happening on Discord nowadays, it's like that, it's 2022 folks! And I don't think you'd regret it as Discord is really a good platform overall, this is not just a hype thing, they really built a strong and useful tool.

**Comment by nckx** [comment]
If your aim is to attract people interested in open, welcoming communities and software, don't use Discord.  Your entire forum becomes their walled garden and invisible to search engines.

Discord itself isn't even free software.  Worse, they actively work against free software clients.

You have to ‘join’ to read previous discussions, which I can't even do without giving them my e-mail address.

If you think that IRC's too old or that slick UIs attract users (dubious), take a look at Matrix instead — which can also be bridged to IRC.  I'm sure there's another alternative I'm missing.

**Comment by eliyo** [comment]
Everyone may have their own opinion about Discord, but for things to move it also helps to stick to the facts. Every indie game being made now has a Discord community, and this goes way beyond games, it's also for apps, tools and various other communities. This is not an opinion, this is a fact.

What I see in Exult is a wonderful project that has some great potential in particular through Exult Studio, but is limited in its awareness and attractiveness by its community management. Unfortunately with some of the comments I've seen in this thread so far, this is not really about to change. I hope someday it will though!

**Comment by eliyo** [comment]
@DominusExult can you please enable me to reset my password on the forum (olio), I didn't note it, the browser didn't save it and the session has expired (if there is another way to ask than writing here please let me know, thanks!)

**Comment by DominusExult** [comment]
I‘m warming up to the Discord server but I am thinking of getting us a channel in the UDIC discord server https://discord.gg/SPH7CKR5
I‘m in talks with Kenneth, who runs it and he sees no problem setting up a bot that bridges to IRC.
My reasoning is that it might be nice to have a lot of people around if you want to talk about general Ultima or so stuff. You have that there

**Comment by DominusExult** [comment]
So our channel #exult on the UDIC discord server is set up. Use https://discord.gg/JQMz3Vqhu7 to join the server and then go to the "Fan Projects" selection and enter #exult. 
There is a discord-irc bridge working, so when someone writes in discord it shows in irc and vice versa.
In theory, when you have the same nick in both it should display nicely on Discord, but that is not working and needs more looking at.

It's not what the OP envisioned but what I can do atm. If we really have a lot of traffic, we can decide on having our own server.
