### ISSUE TITLE
Fastmouse has issues

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#226]
Seems that on macOS it sometimes hides the cursor or places it off screen. On iOS and Android it didn't work at all and needed to be disabled.
This issue is a reminder to investigate this more.

**Comment by DominusExult** [comment]
@Dragon-Baroque just wondering whether you can confirm that fastmouse in fulscreen works on linux? Enable it and go fullscreen

**Comment by Dragon-Baroque** [comment]
@DominusExult, Full Screen Fast Mouse does work.
The pointer moves so fast to be near unusable against a game at 320x200,
it moves faster than without it but it is very usable against a game at Auto.

- Linux = Fedora 37, 
- Desktops = KDE/Plasma over Wayland or over X11, Gnome over Wayland or over X11,
- Screen = 1920x1080 at 120 Hz.

**Comment by DominusExult** [comment]
Thanks! So it's a macOS/iOS only issue

**Comment by marzojr** [comment]
It could be related to hidpi, and differences in hidpi handling on OSX/iOS and others.

**Comment by DominusExult** [comment]
Bingo @Marzo, I didn't think of this but it is indeed caused by hidpi

**Comment by DominusExult** [comment]
I can't figure out what the problem is.
When hidpi and fastmouse are enabled the mouse cursor will not show in the game window, only right at the edges and no input is registered inside the game except for the edges of the screen.

**Comment by DominusExult** [comment]
This works with SDL3 but the changes I needed to make to Exult's code for fastmouse in SDL3 do *NOT* work on Exult with SDL2.
I'm closing this issue because it is fixed upstream but very far away upstream :)
