### ISSUE TITLE
[Request] Allow sound/music to continue to play while Exult does not have focus

### ISSUE THREAD

**Issue by TapestryOfAges** [exult/exult#231]
While I usually am making requests for the reverse, I've been streaming Exult on Twitch and would love it if it was not immediately obvious to my viewers that I have alt-tabbed to check something in a walkthrough or send a quick text to my partner. :) There may well be underlying reasons why this is way more complicated than is worth pursuing for something not many people are likely to want, but who knows? Maybe it's simple and you can add a toggle to the music options menu.

**Comment by wench** [comment]
There is a config file option that should already do this.

In exult.cfg change config/audio/disablepause and set it to yes. exult will automatically create this setting in the config file when it runs so you just need to find the disable pause element and change it to yes
