### ISSUE TITLE
Exult on a Raspberry Pi (4)

### ISSUE THREAD

**Issue by ectorhga** [exult/exult#237]
Hi,

in the past I've compiled and run Exult 1.6 on a Raspberry Pi 3. Later, I changed over to a RPi4 and had some issues, that [were resolved when I used SDL1](https://github.com/exult/exult/issues/33#issuecomment-634648162) as backend.
I was now eager to try the latest release (1.8) on my RPi4. This Pi is used as a "RetroPie" with KMS/DRM and a resolution of 1920x1080. I used the `configure` options suggested by @vanfanel [earlier this year](https://github.com/exult/exult/issues/166#issuecomment-1083498416).

The game compiles and runs. I'm using a resolution of 1920x1080 and a 4x point-scaled game window (480x270), but I have the same issue as before when I start the game from the shell: The screen is tearing badly in both fullscreen and windowed mode.

I have a rudimentary xwin environment installed that is used for some emulators. If I start exult in there, the screen is also tearing *unless* I'm using `matchbox-window-manager` **and** run the game in windowed mode. But then I have a border and title screen around the game screen (which is a bit annoying). When I disable the title bar (`-use_titlebar  no`) the screen is tearing again in fullscreen and windowed mode... Strange.

I don't think this is really an Exult issue, but I wanted to start a discussion on how to get the best out of Exult on a RPi4.

**Comment by vanfanel** [comment]
Use SDL2. Using SDL1.x on this day and age is a VERY bad idea.

I don't know/care if SDL2 comes with KMS/DRM support on RetroPie, but if it doesn't you must build a KMS/DRM-enabled SDL2 first, and then build Exult against it.

Thanks the best way! :D

**Comment by vanfanel** [comment]
@DominusExult Ah, well done with killing SDL1.x support at last :dagger: 

@ectorhga  Rebuild SDL2 with the --enable-video-kmsdrm option, that should do it.
And don't use that small matchbox-window-manager thing, just run the game on the TTY.

**Comment by ectorhga** [comment]
Thanks for all of your input! Of course I compiled Exult with SDL2 (as it's not possible any other way). What I was saying is, that I have had my problems with SDL2 even on exult 1.6. Back then, using SDL1 was my "fix". 

@vanfanel I did what you told me: I compiled SDL2 from source (made sure the `--enable-video-kmsdrm` switch is set) and compiled exult 1.8.x again from source. In the end I have the same outcome: a badly tearing video output when running Exult from the shell. I tried different Exult video settings, but the tearing doesn't go away. Is it possible that I have missed something? Is maybe [your hack from two years ago ](https://github.com/exult/exult/issues/33#issuecomment-564246260) still needed?

**Comment by ectorhga** [comment]
I've made some investigations, and the screen tearing gets fixed with a newer kernel version. I think you need at least 5.10.64. With kernel 5.10.60 there was still tearing on my setup.
These are the prerequisites for running exult on my RetroPie setup with KMSDRM driver. Mind that for the time being RetroPie still relies on Buster and not on Bullseye.
* Kernel version >=5.10.64
* Exult needs to start in a xwindows session
* `VC4_DEBUG=always_sync` needs to be set

Also I'm using the 4x point scaler, to get a close as possible to the old 320×200 on my 1920x1080 display. (5x is not optimal with aspect correction as far I can see. )

**Comment by vanfanel** [comment]
@DominusExult If you still want Exult on the TTY without tearing, edit `imagewin/imagewin.cc`, and change this:

`screen_renderer = SDL_CreateRenderer(screen_window, -1, 0);
`
into this:

`screen_renderer = SDL_CreateRenderer(screen_window, -1, SDL_RENDERER_PRESENTVSYNC);`

...and rebuild Exult. You WON'T have any tearing. But please, please stop running games inside an Xorg session... It makes baby Jesus cry.

**Comment by marzojr** [comment]
> (5x is not optimal with aspect correction as far I can see. )
It should be; aspect correction is coded to scale to a 1:1.2 pixel aspect ratio, which has whole pixels when the scale factor is a multiple of 5.

> `screen_renderer = SDL_CreateRenderer(screen_window, -1, SDL_RENDERER_PRESENTVSYNC);`
I can't see a reason not to do this by default.

**Comment by rofl0r** [comment]
> screen_renderer = SDL_CreateRenderer(screen_window, -1, SDL_RENDERER_PRESENTVSYNC);
> I can't see a reason not to do this by default.

well, it can drop framerate considerably on slower devices

**Comment by marzojr** [comment]
> well, it can drop framerate considerably on slower devices
Exult usually runs at 10fps, which is the stock fps for original U7/SI. What potato would you be using which cannot manage 10fps?

**Comment by vanfanel** [comment]
> > well, it can drop framerate considerably on slower devices
> 
> Exult usually runs at 10fps, which is the stock fps for original U7/SI. What potato would you be using which cannot manage 10fps?

Even a Pi2 can run this much, much faster with the heavy software scaling it uses. So I wouldn't worry about performance with VSYNC on.

**Comment by wench** [comment]
Framerate  loss to vsync should be a non issue. Generally the problem with vsync come from the requirement that framrate = refresh/integer factor. The integer factor causes all the trouble and most shows its ugly heads when the theoretical frame rate is quite high. For instance at 60 hz refresh if the frame rate is above 60  the displayed framerate is capped at 60 because the integer factor has to be 1. If frame rate is between 30 and 60 the limit is 30 as the integer factor is 2, between 30 and 20 you get 20 cause factor 3 and so on. 59 fps droping dowwn to 30 is a big drop and is very noticable as is 29 down to 20 but as the integer factors increase the fps drop goes down. As the ideal fps for exult is 10 that is a factor of 6. If exult is struggling and the factor increases to 7, the fps will end up 8.5 fps. Not a big difference.

There is no downside to vsync for Exult it should be enabled, always.

As for slow systems what I'm working on might be a bit much for some systems. So maybe I should set up a development environment so i can build exult for a pi to see how bad it can be. I have a few low spec systems but a pi really seems like it would be best for testing something similar to what we'd expect to be the lowest spec system to be running exult these days.

**Comment by ectorhga** [comment]
> > (5x is not optimal with aspect correction as far I can see. )
> 
> It should be; aspect correction is coded to scale to a 1:1.2 pixel aspect ratio, which has whole pixels when the scale factor is a multiple of 5.

With 5x scaling I'm getting a warning, that the game window is smaller than 320x200 as soon as I turn on aspect correction. So in the end I'd only have (1080/(5*1,2) = 180 pixel, if I understand it correctly?


> But please, please stop running games inside an Xorg session... It makes baby Jesus cry.

LOL, take that, Jesus! ;) I just want to play the game in the best possible way. But I will rebuild it asap with the latest commit and report back.

**Comment by marzojr** [comment]
> With 5x scaling I'm getting a warning, that the game window is smaller than 320x200 as soon as I turn on aspect correction. So in the end I'd only have (1080/(5*1,2) = 180 pixel, if I understand it correctly?

Exult has 2 separate resolutions, the in-game one (which should be left at 320x200) and the window size. The window size has a few different "useful" resolutions you can cycle through, but you can set others by editing exult.cfg directly. You want the window size to be at least equal to game resolution multiplied by scale factor, then multiply height by 1.2 for aspect ratio. That warning means that the window size selected is not big enough to display the whole scaled game area, and it probably should be reworded.

I suppose we should just add more resolutions to the list as well, at least all common ones up to 5x scale. And maybe filter and display only the window sizes that can display the whole game area with the current scaler and aspect correction settings.

**Comment by ectorhga** [comment]
Then I'll probably use 4x scaling with aspect correction which results in a game window of 480x225. That way I'll come very close to the original 200 points vertically. 
I know it's cheating, but U7 in full screen is just too nice. But there any show stoppers when using a larger game window? I think there was a point in the Forge of Virtue, but I can't recall recall.

**Comment by bribs81** [comment]
Actually i'm trying ti use this script:
https://github.com/hahnmt/ExultRetropie/commit/adee7de5f43cf0f99d560c60304b6bcbb1fb7316

I modified to use Exult 1.8 but It have a lot of issues. I tried this summer to use sdl2 but It doesnt works.

Do you have some advices?

**Comment by DominusExult** [comment]
1.6 is really not what you should use anymore and the OpenGl scaler has been discontinued with the switch to SDL2.
Even before OpenGl had its own mess of display problems.
Seems there is no solution if you use that script for RetroPi.

**Comment by bribs81** [comment]
> 1.6 is really not what you should use anymore and the OpenGl scaler has been discontinued with the switch to SDL2. Even before OpenGl had its own mess of display problems. Seems there is no solution if you use that script for RetroPi.

Is there any step-by-step guide to compile exult 1.8?

**Comment by DominusExult** [comment]
Once you have all dependencies, it's just 
```
./autogen.sh
./configure
```
see https://github.com/exult/exult/blob/master/INSTALL

**Comment by Dragon-Baroque** [comment]
At first, when only building Exult ( not Studio ), the only option you may want to consider to `./configure` is `--prefix` to set the installation directory, like
```
./configure --prefix /home/MyUser/Ultima7
```
Then you run `make` ( Build proper ) followed by `make install` ( Installation of the executables into `/home/MyUser/Ultima7/bin/` and the game components into `/home/MyUser/Ultima7/share/` ).

You then deploy your owned copy of Ultima VII Part 1 into `/home/MyUser/Ultima7/share/exult/forgeofvirtue/` and you check that you find the `U7IFIX` files in the  `STATIC` subfolder.
Same about Ultima VII Part II into `/home/MyUser/Ultima7/share/exult/silverseed/`.

**Comment by DominusExult** [comment]
I think this issue can be closed
