### ISSUE TITLE
Hardware MIDI Synth for Exult in Linux and Configuration XML Pretty Print

### ISSUE THREAD

**Issue by Dragon-Baroque** [exult/exult#238]
[ Reopen of #88 ]

I have posted two branches of one commit in `Dragon-Baroque/exult`:

- `exult_config_xml` produces an Exult config file with clearer looking XML : instead of
```
 <audio>
   <disablepause>
   no
   </disablepause>
   </driver>
```
this code produces
```
  <audio>
    <disablepause>no</disablepause>
```
that is, terminals in XML are kept on one line, and nesting indentation is pushed to two spaces.
- `exult_alsa_midi` supports the hardware MIDI synths in Linux using ALSA : instead of _failing_ on the default `65:0` and reverting to `FMOpl`
```
Trying config specified Midi driver: `Alsa'
ALSAMidiDriver: Can't subscribe to MIDI port (65:0)
Failed to initialize midi player (code: -1)
Failed!
Trying: `FMOpl'
Success!
Midi Output: Enabled
```
this code _lists_ the available MIDI clients to ALSA and _chooses_ a reasonable MIDI synth, in my case the `Creative Labs Rx Audigy`.
```
Trying config specified Midi driver: `Alsa'
Listing midi devices:
14:0 : [ Midi Through : Midi Through Port-0 ], available, 0 channels, RW capability R W SR SW expected W SW
16:0 : [ SB Audigy 5/Rx [SB1550] : Audigy MPU-401 (UART) ], available, 16 channels, RW capability R W D SR SW expected W SW
16:32 : [ SB Audigy 5/Rx [SB1550] : Audigy MPU-401 #2 ], available, 16 channels, RW capability R W D SR SW expected W SW
17:0 : [ Emu10k1 WaveTable : Emu10k1 Port 0 ], available, 16 channels, RW capability W SW expected W SW
17:1 : [ Emu10k1 WaveTable : Emu10k1 Port 1 ], available, 16 channels, RW capability W SW expected W SW
17:2 : [ Emu10k1 WaveTable : Emu10k1 Port 2 ], available, 16 channels, RW capability W SW expected W SW
17:3 : [ Emu10k1 WaveTable : Emu10k1 Port 3 ], available, 16 channels, RW capability W SW expected W SW
128:0 : [ FLUID Synth (26380) : Synth input port (26380:0) ], available, 16 channels, RW capability W SW expected W SW
129:0 : [ TiMidity : TiMidity port 0 ], available, 16 channels, RW capability W SW expected W SW
129:1 : [ TiMidity : TiMidity port 1 ], available, 16 channels, RW capability W SW expected W SW
129:2 : [ TiMidity : TiMidity port 2 ], available, 16 channels, RW capability W SW expected W SW
129:3 : [ TiMidity : TiMidity port 3 ], available, 16 channels, RW capability W SW expected W SW
ALSAMidiDriver: Can't subscribe to default MIDI port [65:0], looking for other MIDI ports
ALSAMidiDriver: ALSA client initialised on MIDI port [17:0] [ Emu10k1 WaveTable : Emu10k1 Port 0 ]
Success!
Midi Output: Enabled
```
In the example above,  `FluidSynth` and `Timidity++` are listed because I had also set them as MIDI servers to ALSA.

Both commits will be set as Pull Requests with reference to this issue.

Dragon Baroque, August 24, 2022

**Comment by Dragon-Baroque** [comment]
Both approved and merged by @marzojr, thanks to you.

**Comment by DominusExult** [comment]
Assigned this issue to me, so I remember to document this!

**Comment by Dragon-Baroque** [comment]
Good point, @DominusExult.

I have put an explanation of the logic of the choice of the MIDI device as a comment in `ALSAMidiDriver.cpp` :
```
// ALSA MIDI port selection checks :
//   type has MIDI_GENERIC, done in find_next_port,
//   capability has WRITE and SUBSCRIBE_WRITE, done in find_next_port,
//   capability has not READ or SUBSCRIBE_READ or DUPLEX, done here,
//   port is available and has channels, done here.
// If this code does not allow the desired port, such as 14:0,
//   it can be set in .exult.cfg as
//   <alsa_port>14:0</alsa_port> in the <midi> section.
```
There are actually three levels of checks :
1. If one sets `<alsa_port>` in `.exult.cfg`, then `ALSAMidiDriver.cpp` tries to _connect_ to it, no checks are performed else than the success of the connection,
2. `ALSAMidiDriver.cpp` _lists_ ALSA MIDI clients that claim `GENERIC_MIDI` type and accept `WRITE` and `SUBSCRIBED WRITE` requests, as it does not want to list, say, just input keyboards,
3. `ALSAMidiDriver.cpp` _chooses_ the first [ by client id ] ALSA MIDI client among the _listed_ clients, that satisfies _also_ the following requirements :
- It is available,
- It has a non zero number of channels,
- It does _not_ accept `READ`, `SUBSCRIBED_READ` or `DUPLEX` requests. This may be a problem for keyboard synths.

In other words, there is some risk that :
- Hardware MIDI devices that do not verify any one of those conditions would not be _chosen_ and possibly even be _listed_.
- If it is _listed_ but not _chosen_, it can be set as `<alsa_port>` in .exult.cfg
- If it is not _listed_ it should be checked directly with `aconnect -o` ( an ALSA command ), and it can be set as `<alsa_port>` in .exult.cfg.
And reported to us, too.

I am not sure that Linux ( or MacOS, in your case ) can differentiate between the on and the off state of an external MIDI synth plugged on the DIN plug, or know about its MIDI channels. If it is USB plugged on the other hand, it most certainly reports its on or off state and its MIDI channels to the OS, this is part of the MIDI 2.0 protocol. From the #88 discussion you appear to own a µMIDI USB to DIN converter cable. If I may :
- What is the synthesizer at the end of the µMIDI DIN cable ?
- Is the µMIDI converted listed by MacOS when the MIDI synth is on ? When it is off or even not plugged ?

**Comment by DominusExult** [comment]
Thanks for the better description, this will come handy when writing this in the docs.

I have several devices daisychained (MT32, CM32, CM64, SC55 something).
AFAIR the USB2Midi device does not know whether there is a device connected to its two ports regardless whether turned on or off. It just reports its two available ports.
