### ISSUE TITLE
No communication from Exult to Studio 

### ISSUE THREAD

**Issue by Dragon-Baroque** [exult/exult#251]
Linux, latest 1.9 :
Running Exult, Activating Cheat mode, Launching Studio ( Alt Ctl M ), Studio launches, but message `Can't find gamedat for socket`.
In `mapedit/studio.cc`, the check `U7exists(GAMEDAT)` succeeds, but the check `U7exists(EXULT_SERVER)` fails.
The `~/.exult/forgeofvirtue/gamedat/exultserver` socket exists but `U7exists` does not find it - cannot open it, I guess.
If I remove the check `U7exists(EXULT_SERVER)` in `mapedit/studio.cc`, the socket is opened OK and the communication Exult -> Studio works.

**Comment by i30817** [comment]
Are you using the ppa? I guess i might have broken this, considering i hardcode the location of the games (after asking for the game data in install)

**Comment by Dragon-Baroque** [comment]
> If you're building on your own, not my fault.
Not your fault, indeed, do not worry.

The `U7exists` fails on sockets.

**Comment by Dragon-Baroque** [comment]
It relates to the issue #204 : commit 05338a4 by @ceckak replaced `stat()` by `U7open_in()` in `U7exists()`.
@marzojr fixed issue #204 by adding `U7opendir()` to `U7exists()` in commit dcbd031 for those systems where directories cannot be `U7open_in()`.
But sockets cannot either be `U7open_in()`.

I do not propose to restore a `stat()` in `U7exists()`. Instead, for the very narrow case of Studio looking for the Exult socket under Unixes - as Windows uses a named pipe instead and I don't expect a port of Studio to Android -, I propose to replace the `U7exists(EXULTSERVER)` in `mapedit/studio.cc` by a `stat()`.
A pull request is to come very shortly.

Now there remains a case inconsistency in this code. `U7exists(GAMEDAT)` resolves the `GAMEDAT` folder as case insensitive, but the `get_system_path(EXULT_SERVER)` and the `connect()` below are case sensitive. This is in fact of no importance as the socket is actually created _case sensitive too_ in `server/server.cc` `Server_Init()` using case sensitive `unlink()` and `bind()`.
