### ISSUE TITLE
Exult crashes randomly while sleeping past midnight in Britain

### ISSUE THREAD

**Issue by agentorangeguy** [exult/exult#256]
I've discovered a weird bug that at first I thought was only in my mod but I was able to replicate it on vanilla BG.  Basically you have to go to Britain somewhere, and sleep at an hour past midnight but before 6am it seems. I've only gotten this to work solo but it might work for other party as well.  Sometimes it takes a while (keep continually sleeping) but then it will crash... and it's always sleeping after midnight.  I can replicate this easier on my mod for some reason but I was able to do it on vanilla BG as well.  I pinpointed it starting after the https://github.com/exult/exult/releases?page=3 v1.9.0.20220724 version from july 24th 2022.  I couldn't replicate the crash before that but definitely after

**Comment by Dragon-Baroque** [comment]
Would you please follow the advice in http://exult.info/faq.php#bug_report and attach to this issue a _zip file_ with

1. An Exult savegame from which this problem shows at least 50% of the times when we follow some more precise instructions, if you please,
2. The whole stdout.txt log file produced by an Exult session started from the savegame and up to the reported crash,
3. The whole stderr.txt log file  produced by an Exult session started from the savegame and up to the reported crash.

Please take the issue #257  as an example of a problem report on which we could act.

**Comment by DominusExult** [comment]
I can reproduce this with the attached savegame (just sleep there for 12 hours). Nothing in the logs, just a segmentation fault.
I'll try and git bisect.
[exult82bg.sav.zip](https://github.com/exult/exult/files/9965413/exult82bg.sav.zip)

**Comment by DominusExult** [comment]
@agentorangeguy great job at finding the point of when the problem occurred. 

The culprit is commit 5df536bb7c85d8873cc054e26ca1b3b2797cedfb by @marzojr
