### ISSUE TITLE
Reapers walk in Exult

### ISSUE THREAD

**Issue by KnightCaptainU7** [exult/exult#272]
In Exult 1.8.0, reapers walk when they should be static. They can do this even when their NPC flag for Walk is set to false. Walks is also not set looking at the shape in ES.

In DOSbox, the reapers are static, and don't activate until you are within attack range.

**Comment by DominusExult** [comment]
hmm, this is perhaps similar to the lava monsters walking on lava. I'll have to see how that was fixed and if I can apply that similarly.

**Comment by KnightCaptainU7** [comment]
Fire elementals "swim" across lava. In both Exult and in DOSbox, setting the "Swim" flag allows for walking across the lava.

**Comment by DominusExult** [comment]
Bringing up that commit was the correct hint. The issue is caused by 2f97ebda390faec008c71c6109dd5b7f156af3fa from @marzojr.
There is a reaper in BG at 0462,01a9 for easy testing.

**Comment by DominusExult** [comment]
If I add a
```
		if (!can_walk && (ter & 1) != 0) {
			// Can not walk on water.
			return true;
		}
```
then it works for the reapers, but I'm not really getting the code to begin with

**Comment by DominusExult** [comment]
Way different and extensive ;)
Thank you!

**Comment by marzojr** [comment]
A lot of differences are edits for readability. Better to have a variable 'can_walk' than having '(move_flags & MOVE_WALK) != 0'.
