### ISSUE TITLE
Loot results different in Exult

### ISSUE THREAD

**Issue by KnightCaptainU7** [exult/exult#273]
There may be an Exult divergence in handling of the items given in spawned enemy bodies. For example if you kill a goblin, notice how they have the same single frame of a food? And trolls always have the 4 gems or none, and 10 gold or none?

In some play testing of the original game in DOSbox, goblins in the forest give about 4 food, with different random frames each time in the same body. Apples, a pumpkin, and one mutton. On another, bread, sausage, grapes, yellow cheese. Even dried fish has appeared. Also if you go far enough way the body will disappear, but the contents in it will be dropped on the ground.

Trolls will give different coin amounts in SI in DOSbox, but will always give either 10 or 0 in Exult. It seems Exult ignores or mishandles the "chance" percentage, you always get the maximum or nothing. I guess the original does a die roll against each one of the count? 

Even in the originals, gems were treated differently than coins, and work closer to binary. You either get all 4 or none from trolls. No idea why these are handled differently. Exult generally follows the originals as closely as possible, so I don't think the gems will be "fixed" the way coins should.

**Comment by jharrison03** [comment]
> For example if you kill a goblin, notice how they have the same single frame of a food? And trolls always have the 4 gems or none, and 10 gold or none?

What's supposed to happen here, is they steal *your* food, and when you kill them, your food should be in their inventory.  This is from the game lore, not necessarily how it's implemented in either the original or Exult.

In Exult, however, I do observe the food drops seem to be random at least.

**Comment by zosite** [comment]
I think those supposedly stealing your food, or at least leaving random food behind are gremlins (purple gremlins in SI and green gremlins in BG AFAIK), and not goblins. The fact that the loot winds up being different than the original comes clear when you think on swamp boots: there are only ONE pair of swamp boots in the original SI, but with Exult you can get youself a few more pairs from goblins protecting Fawn Tower before clearing the area and accessing the city. In the original U7-SI I think those goblins have an -empty- inventory, or at least not swamp boots and antique armor sets whatsoever.

**Comment by marzojr** [comment]
Playing around with UI_summon in the original (plus some custom usecode, plus custom loot tables), I could gleam some information on how the game does things:

- Food shape (377) is special: if the monster in question does not have a specified food frame (hard-coded in originals, specifiable in Exult), the frame is randomized for every instance created. The data suggests equal probabilities for every frame.
- For quantity shapes, the loot tables specifies the upper range of the quantity; the actual quantity is a die roll from 1 to this value, apparently with equal probabilities.
- If any items are added that (1) are not equipped in an inventory slot, (2) are not spells, and (3) are not food, the original game creates a container. There is equal likelihood of it being a chest, pickable locked chest, pickable trapped locked chest, backpack, and bag. If such a container is created
- Ammo created by originals was not a flat probability distribution like in Exult, but it matches the probability curve of 2d10.

**Comment by DominusExult** [comment]
Some old comments about this issue in our old tracker https://sourceforge.net/p/exult/bugs/1932/
