### ISSUE TITLE
Exult Studio - Can't view/extract frames over 31

### ISSUE THREAD

**Issue by Trystanosaurus** [exult/exult#29]
I'm probably doing something wrong but in Exult Studio I can only view/export frames 0-31 of the sprites in shapes.vga.

As far I could see that's fine for the ground sprites 0-149 which have a max of 32 frames but for the creature sprites it should go higher, as currently with the creatures I can only see their up and down animations (not left and right). 

For example in serpent isle, with the blonde lady avatar facing left I can double click her and it tells me it's shape 1029, frame 32 and facing left is shape 1029, frame 48 but I've not managed to see or extract these frames in studio.

**Comment by marzojr** [comment]
This is because those are not real independent frames: frames 32 and up are reflections of frames 0-31 through a 45-degree diagonal line running from top-right to bottom-left.

Closing as invalid.

**Comment by Trystanosaurus** [comment]
Thanks for the quick reply, I knew it was probably because I was missing something!
