### ISSUE TITLE
Swamps of Gorlab sleep is broken

### ISSUE THREAD

**Issue by Crowley9** [exult/exult#297]
I just went through the Swamps of Gorlab for the first time in my most recent playthrough and managed to get through it without the Avatar falling asleep and entering the Dream Realm. I noticed my companions are falling asleep, but then also waking up shortly afterwards. I tried again, this time dismissing everyone from the party before entering the swamp, and this time the Avatar did fall asleep as it should. I am guessing the issue is that when you have party members, the game is scripted to first put them all to sleep before sending the Avatar to dreamland. But as now the sleep effect on them is temporary, the game doesn't get into a situation where they are all asleep long enough to trigger the Avatar's sleep.

This is using the SI Fixes mod and Exult 1.9 snapshot from 2022-12-13. I have attached a save game just at the entrance to the swamp.

[gorlabsleepbug.zip](https://github.com/exult/exult/files/10263863/gorlabsleepbug.zip)

**Comment by DominusExult** [comment]
You are not the first to notice this https://sourceforge.net/p/exult/bugs/2057/ but again I cannot reproduce it.
What are your video settings in Exult and maybe the fps plays a factor as well.

**Comment by Crowley9** [comment]
Video settings:

Full Screen: Disabled
Window Size: 1280x960
HighDPI: Enabled
Scaler: Point
Scaling: x4
Game Area: Auto
Fill Quality: Point
Fill Mode: Centre
AR Correction: Disabled
Same settings for window as fullscreen: Yes

And FPS is set to 5.

**Comment by DominusExult** [comment]
I can reproduce it with these settings and making sure fps <6.
I couldn't reproduce it with vanilla SilverSeed but the only difference I can make out is the extra egg that polymorphs the Avatar back into his body. https://github.com/exult/exult/blob/master/content/sifixes/src/misc/egg_gorlab_swamp_sleep.uc

**Comment by ceckak** [comment]
I ran into this as well playing through on an Android tablet.  I didn't dig into the code, but from the surface, it looked like it was an issue with the large party size.  They would fall asleep one at a time, and by the time the last ones were falling asleep, the first ones were waking up again.

I worked around it by temporarily leaving  some party members behind to reduce the party size.

**Comment by mbanck** [comment]
I am at Gorlab swamp now as well, playing 1.12.1+sifixes. What I noticed is that the companions fall asleep, but if you switch from combat to non-combat (or maybe also vice-versa?) they all wake up again, only to fall asleep shortly thereafter.

I did not have a problem getting the Avatar to sleep and the dream sequence progresses as intended, but it looks weird/buggy that they wake up again.

Basically, when you hit "c" twice every now and then, you can walk around the swamp for a long time, much longer than (I guess) intended by the game.
