### ISSUE TITLE
Boydon's death doesn't behave like the original (SI-SS)

### ISSUE THREAD

**Issue by zosite** [exult/exult#299]
In the original U7-SI (with SS + SI Fixes), when Boydon dies he literally -explodes-, leaving twitching limbs all around (2 legs and 2 arms) along with his "Boydon's body" (with all equipment inside) and his still talking head, while shouting the lines "My beautiful body!!". You won't be able to resurrect him, you know, but you can still talk with his head as before being assembled.

In Exult 1.8.0 (also tested in latest snapshot, dated 12/25/22) there's no explosion nor limbs nor head whatsoever, leaving only the "Boydon's body" object around.

**Comment by DominusExult** [comment]
Good catch. Probably never worked correctly in Exult as no one thought of it.

**Comment by DominusExult** [comment]
Let me redact that. With 1.8 and current snapshot Boydon explodes.
Attached is an original savegame and vanilla SilverSeed savegame to test.
@zosite do you remember where and how Boydon died when he didn't explode?
[originalsavegame.zip](https://github.com/exult/exult/files/10368984/originalsavegame.zip)
[exult220si.sav.zip](https://github.com/exult/exult/files/10368988/exult220si.sav.zip)

**Comment by zosite** [comment]
???! Indeed he does on that savegame of yours! Could you please try this new one I've attached instead? Wizard Mode and a couple of "Mind Blasts" would do...
[exult13si.zip](https://github.com/exult/exult/files/10369014/exult13si.zip)

**Comment by DominusExult** [comment]
I tried with SI Fixes as well and he exploded properly.
I have no idea why he doesn't with your savegame. Maybe someone has time to debug this at some point.

**Comment by zosite** [comment]
Seems I found the answer to this one: the "Tournament" flag. MY Boydon has been heavily trained at Monitor List Field, and the very first training session unsets that flag. YOUR Boydon was not trained at all.

Just set that flag again for him in my savegame and you'll see him explode by the book! Now, question is: how does it behave in the original? I bet Boydon explodes no matter his training status, for I seem to remember having trained him seriously before the journey to Spinebreaker Mountains in the original game and still he went BOOM following the demise of Batlin. But please correct me if I'm wrong (I haven't had time to put those original savegames into good use just yet, sorry).

**Comment by marzojr** [comment]
This is controlled by usecode, so I guess it should behave the same unless the original hardcodes Boydon to have tournament flag on.

The issue here is that the list field uses the tournament flag to run usecode when the NPCs "die" in the list field, and it likely does not enforces Boydon's flag back on.

For what is worth, the tournament flag is what SI uses to run usecode when a character dies. Or rather, when the character takes enough damage to bring them from full health down to 0 or lower, which will also make Boydon seriously tanky when you get his health to 30.

**Comment by DominusExult** [comment]
In the original, fighting in the list field unsets the tournament flag as well and then Boydon doesn't explode.
(I was not able to train, as for some reason whatever experience I set on him, it wasn't enough for the trainers to train him)

**Comment by zosite** [comment]
Weird... I might admit that my memory doesn't serve me as it used to anymore, yet I remember having been able to train Boydon in the original as well. Not the automatons, of course (they don't even appear among optional trainees within list field pikeman dialogue), but Boydon, definitely Gwenno and maybe also Petra. Could it be that he is not supposed to be trained at all lest he isn't able to face his dead -properly- afterwards or something like that?

This is curious, though now I understand that the poor fellow doesn't explode because the unsetting of tournament flag makes his death to not be managed by usecode and that's also the original behaviour: unsetting tournament flag after list field training.

**Comment by marzojr** [comment]
> In the original, fighting in the list field unsets the tournament flag as well and then Boydon doesn't explode. (I was not able to train, as for some reason whatever experience I set on him, it wasn't enough for the trainers to train him)

You need to give training points, not experience, to use the list field.

**Comment by DominusExult** [comment]
Oops :)
After training at the list field the tournament flag is also unset.
*Maybe* some other event in the game knows about Boydon and sets the tournament flag on him later in the game?

Would this be something for a SI Fixes feature?

**Comment by marzojr** [comment]
> Oops :) After training at the list field the tournament flag is also unset. _Maybe_ some other event in the game knows about Boydon and sets the tournament flag on him later in the game?
> 
> Would this be something for a SI Fixes feature?

I inspected all instances of tournament flag being set in usecode, and there is only one case when it is set: by a little bunny in the starting cutscene (along with the tournament flags of several other NPCs). Some NPCs do have it set in other points, but not Boydon.

It would definitely be something for SI Fixes; but as I mentioned, tournament flag makes NPCs become basically immune to all damage that does not one-shot them. So Boydon trained to max strength is seriously tanky, especially with mass might on (but it would be even worse with BG's version!).

**Comment by zosite** [comment]
Well, actually Boydon starts on 30 Strength WITHOUT any training so I only trained him on Dexterirty & Combat with Shazanna. So yes, basically he's a serious tank by default, let alone the "Mass Might" spell.

At least now we know that this lacking of 'exploding behaviour' is -broken by design- so to say.

**Comment by KnightCaptainU7** [comment]
The List Field usecode is somewhat convoluted, but good to know about this issue.
