### ISSUE TITLE
Spell objects visible in normal game without cheats (U7-SI)

### ISSUE THREAD

**Issue by zosite** [exult/exult#300]
I don't think you're able to see those spell objects (Swordstrike, Paralyze, etc.) within the course of a normal game; they're indeed being used by the correspondign NPCs but not for you to take from them unless cheating (mind you, maybe the "Vibrate" spell and its inherent -brokeness- would force them to appear in the original game too).

On any case, I cannot remember dead mages having spell objects within their inventories in Moonshade after good ole Shamino decides to implement a few changes on its government, but in Exult 1.8.0 (also in latest snapshot dated 12/25/2022) you can find those spell objects all around. And the same goes for poor Mortegro (I think those were "Curse" and "Death Bolt") before a teleport lighting bolt makes him to appear (naked...) on the Valley of Eodon or something.

Still, I'd be grateful if someone else could confirm me on this, for I have no time to reach that far (Chaos Banes being released after Batlin is dead) playing the original right now nor do I know whether any game flag in the original U7-SI F2 cheat menu system would do the trick before due time so I could test it.

**Comment by DominusExult** [comment]
Indeed the original does not show these items on a dead body but if you force an NPC into your party or (I think) use the vibrate spell you can see them.
So I think the original does clean out these spell objects when it "fills" the dead bodies.
@marzojr is that something that is done by the original in usecode or game code?

**Comment by marzojr** [comment]
Looking over the bane apocalypse usecode, it uses UI_kill_npc to turn NPCs into their corresponding corpses. So the flaw is in the way that spells are deleted when transferring them to the corpse.

Looking over, it seems to me that spells inside containers are preserved, while those being held directly by the NPC are destroyed. I don't know if the originals behave the same or not, and I won't be able to test *that* for some time. Gustacio (NPC 22) is a good candidate for testing if anyone wants to do it; he has purple lightning in his backpack, in addition to fireballs in his hands. If you clear his tournament flag (all mages in Moonshade have it set) you can kill him and inspect the loot in his body.

**Comment by DominusExult** [comment]
Just tested it in the original:
All spells are gone when I kill him.
I made sure that he had the spells with him and both in hands and backpack by adding him to the party, then unadded him, set paralyze, unset tournament and killed him.

In Exult it's as you wrote, spells in containers are preserved.
