### ISSUE TITLE
SIFixes Feature Request: Use Book of Sonets by Beatrix to track down Anti-Shamino

### ISSUE THREAD

**Issue by zosite** [exult/exult#302]
I remember the Book of Sonets by Beatrix being useful to track the Bane of Anarchy into the Castle of the White Dragon as Shamino's personal item, most like Iolo's Lute and Dupre's Shield. Well, in Exult it doesn't work and "The hound looks confused"; the other two work flawlessly.

Using Exult latest snapshot, dated 12/25/22 along with SI Fixes mod.

**Comment by DominusExult** [comment]
I tested it and it doesn't work with the Book of Sonets in the original. Maybe that could be a feature for SI Fixes.

**Comment by zosite** [comment]
Indeed, please let Marzo know about this and thank you for the clarification.

**Comment by DominusExult** [comment]
Let's reopen it as a feature request.
But to be fair, using one tracks down all anti companions ;)

**Comment by marzojr** [comment]
Huh. As it turns out, there is usecode to track Anti-Shamino by the book of Sonnets in the game... but it uses the wrong book for it. You can track Anti-Shamino using an anonymous diary (quality 0x3E) instead of Beatrix's book of sonnets.

**Comment by zosite** [comment]
I can confirm it's that anonymous diary from that dead smith which relates the capturing of the Banes by Batlin and his henchmen what the Hound of Doskar tracks instead. Obviously a mistake on the original, thus definitely something for SI Fixes.

**Comment by KnightCaptainU7** [comment]
[hound.txt](https://github.com/exult/exult/files/10779329/hound.txt)
The above needs a few "DUPRE," changed to "-1,".

else if ((target_shape == SHAPE_BOOK) && ((target_quality == 62) && (gflags[BANES_RELEASED] && (!gflags[ANARCHY_BANE_DEAD]))))

should be 

else if ((target_shape == SHAPE_BOOK) && ((target_quality == 63) && (gflags[BANES_RELEASED] && (!gflags[ANARCHY_BANE_DEAD]))))
