### ISSUE TITLE
U7-SI & SS + SI Fixes: Planting The Silver Seed == EXP penalty?!!

### ISSUE THREAD

**Issue by zosite** [exult/exult#306]
[exult12si.zip](https://github.com/exult/exult/files/10366120/exult12si.zip)

Errr... I couldn't say for sure whether it works the same way in the original game (I hope it doesn't) but in Exult 1.8.0 / recent snapshot (+ SI Fixes mod), planting The Silver Seed on its corresponding hallowed glade meant around -10K EXP hit for my poor Avatar... funny...

After having been investigating it further thanks to the cheat system, this one seems to be related with the EXP amount the Avatar has right before planting The Seed, with a diminishing returns of sorts related to some high EXP treshold around 10K+.

I've attached a savegame right before planting the Seed with a 30K+ Avatar with absolutely no cheats having been used before that point, just in case I happened to break something with my tests.

Again, I wouldn't know the maths behind it, but I'd be grateful if you could unveil them to me so I could give the poor fellow his deserved reward, no more no less; -10K was a little bit hard for me right when I was struggling to hit Level 11 (51,200 EXP).

**Comment by zosite** [comment]
Ok, the EXP threshold for this to happen seems to be between 25,600 and 25,700 before planting The Seed. On my way to test whether it works the same in the original game (I hope I'll be able to do so, thanks to "serpent manimal" cheat system...).

**Comment by zosite** [comment]
Aaaaand, after testing this with the original game through its -official- cheat system I've confirmed the following: it does NOT substract any EXP beyond the aforementioned threshold nor it does add anything I could notice; your EXP remains the same with no bonus whatsoever.

Well, this means it's much more convenient to complete SS quest soon enough, yet for my playthrough I wanted to do it after defeating the Banes of Chaos in order for Karnax to mention that their atrocious deeds could be eventually undone thanks to the planting of The Seed. Yeah, I'm one of those lore/plot freaks who would prefer a good story than a powerful RPG character and I'm helpless... :_P

**Comment by wench** [comment]
This is suspiciously close to the 16-bit integer limit. I doubt that is a coincidence, but the behaviour is strange as it doesn't seem to be an overflow.  I suspect the trouble is coming from Exults implementation of Usecode Intrinsic set_npc_prop. Nothing immediately pops out as being a problem

**Comment by marzojr** [comment]
It is kind of, sort of, an overflow. But not in the way you think. For context:
1. usecode values in the original games are limited to 16-bit signed values;
2. experience is stored as a 32-bit value;
3. experience given by usecode is divided by 2.

With these in mind: in the Silver Seed usecode, we what amounts to this block:

```dart
		var exp = AVATAR->get_npc_prop(EXPERIENCE);
		if (exp <= 0x0320) {
			AVATAR->set_npc_prop(EXPERIENCE, 0x0320);
			abort;
		}
		if (exp <= 0x0640) {
			AVATAR->set_npc_prop(EXPERIENCE, 0x0640);
			abort;
		}
		if (exp <= 0x0C80) {
			AVATAR->set_npc_prop(EXPERIENCE, 0x0C80);
			abort;
		}
		if (exp <= 0x1900) {
			AVATAR->set_npc_prop(EXPERIENCE, 0x1900);
			abort;
		}
		if (exp <= 0x3200) {
			AVATAR->set_npc_prop(EXPERIENCE, 0x3200);
			abort;
		}
		if (exp <= 0x6400) {
			AVATAR->set_npc_prop(EXPERIENCE, 0x6400);
			abort;
		}
		AVATAR->set_npc_prop(EXPERIENCE, 0xC800);
```
That last line is important: 0xC800 is actually a *negative* number: it was meant to be +25,600 exp (`0xC800 / 2 = 51,200 / 2 = 25,600`), but that 0xC800 is sign-extended to 32-bits and turns into -7,168 exp instead (`((int16_t)0xC800) / 2 = -14,336 / 2 = -7,168`). This branch is reached when `exp > 25,600`.

Testing with custom usecode, it seems that usecode cannot ever reduce experience in the original games; so I guess it checks if `delta < 0` and bails out.

I think I will fix this by forcing exp to be treated as a unsigned 16-bit value in usecode, fixing not only a bug in Exult, but also a bug in the original (that you cannot gain exp from planting the silver seed if you have more than 25,600 exp already).
