### ISSUE TITLE
U7-BG/SI: Extra frame just before corpse item creation

### ISSUE THREAD

**Issue by zosite** [exult/exult#308]
In Exult (using v1.8.0 as well as snapshot dated 12/25/22) an extra frame with the NPC standing up normally is always being inserted just before the killing and creation of the corresponding corpse item. So, let's say you have your enemy unconscious (<=0 hit points) laying at your feet; if you decide to show -mercy- with a final blow you'll surely appreciate how he stands up for a final frame before it becomes a corpse object.

Granted, even if the originals don't seem to behave anything like that (or at least I wasn't able to see that extra frame) this would be only a cosmetic fix; until then it just looks... weird...

**Comment by DominusExult** [comment]
Back in 2010 @marzojr fixed that previously in 805d20f2c 
No idea how that got reverted (and what part of the changes in 2010 was fixing it).

**Comment by DominusExult** [comment]
Going through my saved snapshots it seems that 0c658baec caused this. @drcode1 added `void Combat_schedule::back_off` and this might have messed with the last frame of a slayed unconscious enemy.
