### ISSUE TITLE
U7-SI: Armor of Beauty wrong warmth value?

### ISSUE THREAD

**Issue by zosite** [exult/exult#309]
According to several sources (including the official "Balancing the Scales" guide) the Armor of Beauty (or just "breast plate") from Kylista matches the plate armour in defense value with a lesser weight and warmth value of 0 as additional benefits, which in the end means that wearing it would be the same as wearing a magic armour when it comes to protect a party member from northern wastes cold.

Well, testing it in Exult 1.8.0 (also in latest snapshots) I'd say that its warmth value is not 0 but a penalty, as if it were a normal plate armour in that particular. Could anybody please confirm me on this?

**Comment by DominusExult** [comment]
Original: 
naked NPC warmth stat of -0075
NPC wearing the Armor of Beauty -0084
So a warmth of -9, exactly as Exult does it.

To test in the original use the cheat screen, M(odify NPC), number of the NPC in party and then N(PC Stats).

**Comment by zosite** [comment]
Thank you, Dominus! But still, I can understand the official guidebook being wrong for it was published shortly after original game release, but it's unbelievable how after all these years sources like "The Codex of Ultima Wisdom" haven't been corrected accrodingly. o__0

**Comment by zosite** [comment]
Ok, I've found my copy of "Balancing the Scales" and it doesn't mention the warmth value but only the protective value of the breast plate (pag.62). It seems this mystification must have come from other wrong sources like "The Codex of Ultima Wisdom" and other famous walkthroughs. Sorry for the confusion.

**Comment by DominusExult** [comment]
No problem, just a matter of finding the right savegame :)

Btw. https://www.dropbox.com/s/hv5t9afgrpbsite/Serpent%20saves.rar?dl=0 is a collection of the original Silver Seed savegames following the usual walkthrough steps and the titles are good to get an idea at what point of the game it is (open the savegames in a quickviewer, hexeditor or anything to quickly see the first line with the savegame name).

**Comment by zosite** [comment]
Thank you so much, Dominus! I shall find them useful, indeed, since my main concern when it comes to test Exult is the time I would need (and I wouldn't have) to get to the same point in the original games for everything outside the standard cheat system, and in SI is much worse than in BG due to all those plot scripts and global flag mayhem...

Speaking of which, would you happen to have another one of those nice savegame downloads for BG-FoV too?

**Comment by DominusExult** [comment]
The SI archive proved itself very often ;)

Unfortunately no such archive for BG. But due to its less linearity it's easier to test BG stuff.

**Comment by zosite** [comment]
Ok, thank you anyway. Besides, you're right: I don't usually face much trouble when testing BG-FoV.

BTW, I've already fixed all "Codex of Ultima Wisdom" entries for the breast plate, just in case someone else uses it as a guide.
