### ISSUE TITLE
Opening spellbook turning page for bookmark spell circle 

### ISSUE THREAD

**Issue by xenoghast** [exult/exult#31]
for int 0..{bookmark_circle}% do;
{turn_page}+1; done
This is not code.

For having the spellbook turn_page animation for the bookmarked spell circle on opening.

https://github.com/exult/exult/blob/master/gumps/Spellbook_gump.cc
line>253

**Comment by xenoghast** [comment]
In real Ultima 7; When opening the spellbook there is a number of page turn animations equal to the circle of magic that the bookmark was last on. The opening issue was an example idea of the code necessary. This is the first I have ever contributed to GitHub.

**Comment by marzojr** [comment]
This is a "feature" from the original which was deliberately not added to Exult because it is annoying, especially if you bookmarked a 8th circle spell. Moreover, it is not even realistic: you don't need to flip all pages to reach a bookmark on a real book. This is a "won't fix".

**Comment by xenoghast** [comment]
This makes sense, not that magic is not unrealistic. I had a feeling it wasn't included because it does take extra time to open.
