### ISSUE TITLE
Mixed Light Sources math.

### ISSUE THREAD

**Issue by xenoghast** [exult/exult#32]
```
//???
{
	for nearby_light_sources;
		int obj_relative_pos = abs(avatar_pos(x, y) - lightsource_pos(x, y));
		int light_relative = sum((obj_relative_pos)(8 / 3, 4)); // multiply relative_obj_pos (x3 - x/3, 4y) and add together for percentage of impermissible light.
		if $nearby_light_source = shapeid0x 'torch';
			int light = 150;
		if $nearby_light_source = shapeid0x 'lamp';
			int light = 60;
		if $nearby_light_source = shapeid0x 'candle';
			int light = 30;
		if $nearby_light_source > 0;
		int $nearby_light_source = round(light - ((light / 100) * light_relative);
		else if $nearby_light_source = 0;
		int $nearby_light_source = 0;
	lux = const char 0 + ( sum $nearby_light_source)
	return lux;
}
```
Emptying variables math and everything might be way off in this outline, as well as possible expansions for detected light sources and possibly using intrinsics. I don't know.
```
//gameclk.cc
{
if (light || special) && is_dark_palette(pal)) {
	if lux > 11;
		light_palette = PALETTE_CANDLE;
	if (special)
		light_palette = PALETTE_SPELL;
	else if (lux > 89)
		light_palette = PALETTE_SINGLE_LIGHT;
	else if (lux > 255) 
		light_palette = PALETTE_MANY_LIGHTS;

		return light_palette;
}
```

**Comment by xenoghast** [comment]
{
for (obj in shapes)
	{	
		// wants to find parameters? obj distx, disty, lit_
		var lsources = obj->find_nearby(obj, dist, MASK_NONE);
		// Taken from GreatDouse
		for (lightsource in lsources)
		// Unknown call variable. distx disty
			var lev = ((obj->get_distance(lightsource)(x3 - x / 3, y4));
				// unknown shape ids 
				if lightsource = 0xtorch || 0xstreetlight || 0xsconce || 0xmagictallcandle || && lit
					int lid = 150
				if lightsource = 0xlamp || 0xtallcandle || 0xmagiccandle && lit
					int lid = 60
				if lightsource = 0xcandle || 0xcandle2..5 && lit
					int lid = 30
				// set array variable for light
				int lux = { round(lid - ((lid / 100) * lev), ??? }
		
		// clear array variable?
		// Is this too big to have a loop for constant rendered environment? Should the math use tables instead?
		// Am I even going the right direction with this?
	}
}

**Comment by xenoghast** [comment]
I think something side by side with the gamerenderer to output the mixed lightsources. If I knew an the right functions and alternatives to the scripting environment. The above instances wont work. I'll need to study more of the gamerend script.

**Comment by marzojr** [comment]
This is now fixed in master.
