### ISSUE TITLE
Might as well post a original serpent isle bug

### ISSUE THREAD

**Issue by i30817** [exult/exult#324]
I was reading the wiki and ended up in the Draxinar page (the dragon on the silver seed expansion).

https://wiki.ultimacodex.com/wiki/Draxinar

Anyway this dragon does riddles, and the trivia says one of the answers is wrong

I was wondering, since you're working on sifixes/blackgate again if it's a valid target for a fix, since it seems like it should be a simple replacement of a usecode constant.

**Comment by DominusExult** [comment]
https://github.com/exult/exult/tree/master/content/sifixes/src/misc <- @KnightCaptainU7 fixed that some time ago

**Comment by i30817** [comment]
mmm. I though i'd already read the readme for sifixes, but it was actually bgkeyring.
