### ISSUE TITLE
Unicode : NPC cannot hold names with diacritics

### ISSUE THREAD

**Issue by Dragon-Baroque** [exult/exult#341]
During the validation of the ICU variant of Studio, @DominusExult noticed that NPC hold names with diacritics only during the current Exult + Studio session.
When the changes are saved, when Exult and Studio are restarted, such NPC names become empty.

This comes from an original commit ae010cc1 by @wench into `actorio.cc` method `Actor::read`, followed by some commits, the latest being the commit 489313bd by @marzojr, changing whether the codebytes above 0x7f should be allowed.
What remained constant however, was that the codebytes below 0x20 were rejected, then forcing the NPC name to become empty.

If, while remaining in the German / French codepage of the original Ultima VII, we alter the name of an NPC to contain French / German diacritics, these fall into the range 0x01 .. 0x1f and they hold while Exult and Studio is alive.
The name is banished however by the check for codebytes below 0x20 at read time, thus explaining the failure noticed by @DominusExult.

What should we accept ?

1. Banish NPC names with diacritics all over, then that means rejecting the entry of such names in Studio, in the NPC Editor,
2. Allow NPC names with the diacritics of the original Ultima VII French / German codepage, and / or NPC names with the diacritics of Unicode, assuming that the developer of the mod shall provide a suitable `FONT.VGA`. Then we need simply to remove the check in `Actor::read`.

**Comment by marzojr** [comment]
Definitely 2.

**Comment by marzojr** [comment]
1a — we can always look back in git history anyway.

**Comment by Dragon-Baroque** [comment]
Completed by PR #342, commit a39f760f

**Comment by marzojr** [comment]
Just a hint, if you put "fixes #<issue number>" on the commit description, GH will automatically close the issue for you.
