### ISSUE TITLE
Exult on android setting 'd-pad screen location' should have the none setting disabled.

### ISSUE THREAD

**Issue by i30817** [exult/exult#356]
This is a nasty trap for first time users that start the games and then can't move. Ironically, in the pc version, that setting only possibility is 'none' which is correct (imo), but when it really should be required (or at least default/required if the long touch to pathfind setting is off) it's not.

The user can still quit the game/access the menu when they figure out double clicking the avatar will allow to click the 'diskette' button accessing the settings menu, although for accessibility reasons maybe the top icon menu should be enabled by default on android too?

**Comment by DominusExult** [comment]
it's weird. Both (dpad and the shortcut bar) should be enabled for Android https://github.com/exult/exult/blob/master/gamewin.cc#L388
Something is not working right on android.

**Comment by i30817** [comment]
I installed it on the playstore, and i didn't see the either, although i might have missed the dpad (it's transparent) but i certainly didn't have the top menu (i just enabled it in fact). There is also someone in the ultima subreddit asking about 'how to move' which looks like this.


Another thing, any reason in particular why key/dpad movement doesn't attempt to open doors? It's a bit annoying

**Comment by i30817** [comment]
In fact, the right mouse button pressed 'movement' behavior of opening doors seems bugged here (test in pc this time).


The avatar opens the door, enters, closes the door, _opens the door again, exits, closes the door the moves inside the room_

It's very strange

**Comment by DominusExult** [comment]
if you manage to build the android app yourself (as briefly discussed in #358) could you give feedback whether this works correctly? I think it does not but when I tried last time I was busy to get the app to work and didn't pay attention to these things.
And now I had to delete my Ubuntu VM because I forgot my password... ugh...

**Comment by i30817** [comment]
Wow, i think i just realized what's the problem with the camera. For some reason the 'mousewheel zone' of the touchpad is moving the camera.... and it's not all up or down. It's strange.

**Comment by DominusExult** [comment]
@i30817 can you give this apk a try? https://www.dropbox.com/scl/fi/e2eu0wrfgw06k85uqts8v/exult-snapshot.apk?rlkey=yllpj8257sm8q41zrafe767pm&dl=0 (I'm trying my hands at making the android snapshot build but need to figure things out first :) but at last here is a built of current git).

**Comment by i30817** [comment]
Just says apk not installed after trying to install. I currently don't have a desktop\laptop if that's needed for debug either, just this tablet.

**Comment by DominusExult** [comment]
AFAIU @ceckak you *have* to uninstall the release version to be able to install the debug one.

**Comment by ceckak** [comment]
That's correct.  It won't let you install an unsigned app over a signed one.  Incidentally @DominusExult - I'd be happy to share the signing key with you if you want to be able to sign apks to avoid this issue.

**Comment by i30817** [comment]
The current code in the exult port android launcher to 'import' the mods should be changed to also have the ability to import a generic mod. Currently in my last install I had to trick that thing to install 3 forge of virtue mods at once by creating a zip with all of the fov mods I wanted, it was how I was able to run the u6 mod.

**Comment by ceckak** [comment]
Agreed.  I've had limited time to work on this so went with some minimal basics to get the game playable.  Top of my list of improvements to make is better handling of savegames (currently they get deleted if you uninstall the app, and they require some adb trickery to extract).  More flexibility on installing mods and music is on the list too though.

**Comment by DominusExult** [comment]
Automatic Android snapshots are now being build and released along with the Windows snapshot.
@ceckak thanks for the signing key offer but I managed to create one myself.
The snapshot build is now taking about an hour as I'm letting it build both debug and release of the Android APK (and since each compiles four arches it takes a while).
The signed one can be downloaded from our download page http://exult.info/download.php and both from the github release page.

**Comment by ceckak** [comment]
If you are using a different signing key, it will have the same issue as the debug build that you can install over the apks we previously released using my key.  You could remove the old apks, or just take over my key to keep it all consistent.  I created the key purely for exult with the intent to transfer it if/when we had automated builds.

**Comment by DominusExult** [comment]
@ceckak I didn't think of that but it makes sense.
Could you send me the key, password and alias (all three needed for signing in the workflow)?

@i30817 when that next release is out, could you try if the mousewheel camera problem is fixed?
I can sadly confirm that both dpad, ESC button and shortcut bar are disabled on first run. Which really puzzles me.
Also the dpad needs to go higher. At least on the emulator there is too few downward travel space.

**Comment by ceckak** [comment]
@DominusExult - will do.  Should be able to send it out today.

**Comment by ceckak** [comment]
@DominusExult - sent the keystore and related details to your gmail account.

**Comment by i30817** [comment]
The mouse wheel /pad problem existed on my portable in wayland which is broken currently and at a repair price of at least 100€ I'm not sure I'll see it soon. Maybe this week, maybe never. damn planned obscelence hp shit.

**Comment by i30817** [comment]
Thinking about it some more, I kinda want the possibility to enable the stick even on PC. Touch screens are unusual in PC.... Unless you use a ipad or android tablet as a second or first monitor. Sounds insane and requiring rooting, but can be done on software with https://github.com/H-M-H/Weylus teamview or similar.

**Comment by wench** [comment]
Windows tablets and 2in1 Laptops with touch screens (like for example the entire Microsoft Surface range among others) are far from unusual so it could be very nice for people who use those devices. I have one but have never tried playing Exult on it, my interests have mostly been elsewhere for many years now.

**Comment by DominusExult** [comment]
> it's weird. Both (dpad and the shortcut bar) should be enabled for Android https://github.com/exult/exult/blob/master/gamewin.cc#L388
> Something is not working right on android.

that was easy to fix when I actually took a good look :) the ifdef was set for iOS *AND* Android, not *OR* so it was never triggered.
dpad, shortcut bar, touch pathfind etc, should now all be set correctly on first run.

**Comment by DominusExult** [comment]
> Thinking about it some more, I kinda want the possibility to enable the stick even on PC. Touch screens are unusual in PC.... Unless you use a ipad or android tablet as a second or first monitor. Sounds insane and requiring rooting, but can be done on software with https://github.com/H-M-H/Weylus teamview or similar. Pretty handy when latency requirements aren't too bad I suspect.

This would mean someone would need to setup the view of the controls on Desktop machines.

**Comment by DominusExult** [comment]
Moved the dpad further away from the screen edges to make it easier to use.

I've opened new issues for other issues referenced here and will close this one.
