### ISSUE TITLE
Exult studio is failing building in certain platforms

### ISSUE THREAD

**Issue by i30817** [exult/exult#36]
I suspect because the plugin for gimp depends on ancient gtk deprecated stuff. Or maybe i just need to make the control file add a package for those platforms, not sure. If so, it weirded me out it was only failing in some platforms.

Here are the build logs:

https://code.launchpad.net/~exult-team/+recipe/exult-daily

**Comment by i30817** [comment]
Actually by comparing the builds, the problem appears to be the opposite, exult requiring a too new libgegl on those older distros.

The new distro installs 'libgegl-0.4-0' and the older one installs 'libgegl-0.3-0' then fails the build with a bunch of include errors in u7shp.c.

This started failing recently, was u7shp changed recently?

**Comment by i30817** [comment]
Ah, it's because the smart pts merge and it was changed back in 2018. Maybe i should specify libgegl-dev (>= 0.4.0) i wonder if that'll work on the older distro.

**Comment by i30817** [comment]
I made a patch (that i didn't bother to build just waiting to see if the ppa fails) to see if it fixes this by making a ifdef for this commit:
https://git.launchpad.net/~exult-team/exult-engine/+git/packaging/tree/debian/patches/libgimp_compat.diff

pretty sure if the version check is not the actual version the api changed, but it's the libgimp version that is building on ubuntu focal, so i used that.

**Comment by marzojr** [comment]
Ack. No more #ifdefs in the middle of code, please; we already have enough of them which I am trying to get rid of. Given the choice between more #ifdefs and not building the Gimp plugin, I would always pick the latter.

I would not oppose (too much) having wrapper functions for the code that differs between the two versions, and having the entire implementation of the functions being guarded by #ifdef for the appropriate versions.

By the way, building Gimp plug-in is independent from building Exult Studio.

**Comment by i30817** [comment]
I'll leave it to you to decide what to do, i can always delete the patch later. The duplicated function solution with a master ifdef sounds like it'll work because that whole section is a huge function, if i'm not mistaken.

**Comment by i30817** [comment]
Was this fixed? Can i drop the patch?
