### ISSUE TITLE
Desperately trying to run the game

### ISSUE THREAD

**Issue by nickbe** [exult/exult#360]
When I try to run the game it shows throws me to the U7 screen. I tried to put the mod into different folders but nothing seems to work. 

This is my current folder structure:
![image](https://github.com/exult/exult/assets/10890765/6c87d918-06e8-4e17-873b-f9c0f969b7fd)

Clicking here just shows the normal menu:
![image](https://github.com/exult/exult/assets/10890765/b0906cbd-8d65-4eab-80bb-0014392c55bf)

and this is the config.
[exult.zip](https://github.com/exult/exult/files/11931765/exult.zip)

Can anyone please tell me what is wrong here?

**Comment by DominusExult** [comment]
Can you post the stdout.txt and stderr.txt? Can be found where the cfg is http://exult.info/faq.php#where_cfg

**Comment by i30817** [comment]
If this is about the ultima 6 mod it's a ultima 7 forge of virtue mod so you should place it only on that directory iirc.

In linux, with my ppa (that doesn't have a standard location for the install so i'm not showing the location just the structure), i have this directory structure for the games (you only need the gamedat folder from the original games).

The files are _all_ lowercased, but that's a linux thing for things to work there:

.
├── blackgate
│   └── static
├── forgeofvirtue
│   ├── mods
│   │   ├── islefaq
│   │   │   └── patch
│   │   ├── keyring
│   │   │   └── data
│   │   │       └── map01
│   │   └── ultima6v1.1
│   │       └── patch
│   │           ├── map01
│   │           ├── map02
│   │           ├── map03
│   │           └── music
│   └── static
├── music
├── serpentbeta
│   └── static
├── serpentisle
│   └── static
└── silverseed
    ├── mods
    │   └── sifixes
    │       └── data
    └── static

**Comment by rofl0r** [comment]
maybe it'd be an idea to provide some sort of helper script which you can point at a directory containing gamefiles or mods which then recurses over the contents and moves everything to the right place in the exult directory structure (including renaming the files to lowercase) ?

**Comment by i30817** [comment]
I mean, it's not like i haven't done that for my PPA. Although my script is specialized for my requirements (it doesn't copy the mod files that belong to the mods on the exult source because the PPA already installs the latest version of those mods with the package.

https://git.launchpad.net/~exult-team/exult-engine/+git/packaging/tree/debian/gamedat-setup

**Comment by nickbe** [comment]
> Can you post the stdout.txt and stderr.txt? Can be found where the cfg is http://exult.info/faq.php#where_cfg
[stdout.txt](https://github.com/exult/exult/files/11940136/stdout.txt)
[stderr.txt](https://github.com/exult/exult/files/11940137/stderr.txt)

Looks like FOV is not found although I bought the GOG complete edition. 
Also it's shown in the main menu that it's there.

**Comment by DominusExult** [comment]
Yeah, your folder structure is a mess and you are pointing at the Ultima7 which could very well be with FOV.
Please post stdout.txt and stderr.txt

**Comment by nickbe** [comment]
I just did. 
![image](https://github.com/exult/exult/assets/10890765/00f89472-3ce5-4cbb-8ffb-e3865a02d41a)

**Comment by nickbe** [comment]
Why not releasing a complete (clean and tidy) folder structure with some text files in the folders explaining what belongs here and from which sources?

**Comment by DominusExult** [comment]
So, from the stdout both configured games are with the addons ("game with identity ... found").

Can you describe what is happening  and what you expect to happen?

And does starting a normal unmodded game work?

I've written in the documentation what to use and install http://exult.info/docs.php#Installing%20the%20original%20Ultima%20VII%20games%20for%20use%20with%20Exult

**Comment by nickbe** [comment]
Thanks a lot. I will check the documentation in an hour and see if I can make it work.

Yes, the normal unmodded game is just starting as expected.

**Comment by nickbe** [comment]
I installed the GOG version from scratch and also Exult. After that I can start BG/FOV and SI normally.
Then I've added the "Ultima6v1.1" mod to this folder: X:\UltimaGames\Ultima7\mods

![image](https://github.com/exult/exult/assets/10890765/aae3b486-a5e7-4f0b-9b2e-702d1c894cc2)

This seems to be the right folder since I can now see the mod in the menu under "show mods":

![image](https://github.com/exult/exult/assets/10890765/1e68305a-dabc-47a8-b8bb-65b80d309b72)

But when I click it only the main game is started:

![image](https://github.com/exult/exult/assets/10890765/6c27993c-d4e1-452d-95c9-33f10740af9f)

Here are the logs:
[stderr.txt](https://github.com/exult/exult/files/11946089/stderr.txt)
[stdout.txt](https://github.com/exult/exult/files/11946090/stdout.txt)

Maybe I have to use a different game version or install the game files in a different way.
The errors:
Could not open file '.\forgeofvirtue\static\mainshp.flx
Could not open file '.\silverseed\static\mainshp.flx
Could not open file '.\serpentbeta\static\mainshp.flx

seem to indicate that the subfolders in 
AppData\Local\Exult should contain the actual game files.

![image](https://github.com/exult/exult/assets/10890765/460d17a4-e06b-451d-8fd6-c874610e0006)

**Comment by Dragon-Baroque** [comment]
@nickbe, Dear Sir, @i30817 gave you the right track.

My normal Exult install on Windows is `C:\Ultima7`, thus I unzipped `Ultima6v1.1.zip` in
`C:\Ultima7\forgeofvirtue\mods\` ( not in `C:\Ultima7\blackgate\mods` as the `Ultima6v1.1` readme says ) .

This is the folder where you can find also `islefaq\` and `islefaq.cfg`, `lbjoin\` and `lbjoin.cfg`, `Keyring\` and `Keyring.cfg`. Good trick to make sure that you are at the right place.

If you unzip `Ultima6v1.1.zip` in that place, you create a new folder `Ultima6v1.1\`. This is the right place. But the expected `Ultima6v1.1.cfg` is missing. Is is inside the `Ultima6v1.1\` folder instead.

Thus you need as a **second step** to copy ( or move ) the `Ultima6v1.1\Ultima6v1.1.cfg` one folder up to `Ultima6v1.1.cfg` ( into `...\forgeofvirtue\mods\`, that is ).

I do apologize not to have reported this trick to @DominusExult as soon as I noticed it.

 @DominusExult, Please, two questions :

1. Is there a reason why  `Ultima6v1.1` [ aka the Ultima6 remake ] is not available from the `Download` page of `exult.info` ?
2. We might solve the nested `Ultima6v1.1.cfg` issue by looking for the `.cfg` files not only in the `...mods\` folders but also in their immediate subfolders. I kind of understand why the author of the Ultima 6 remake insisted to have all files in the `Ultima6v1.1\` folder, this is less risky in terms of file conflicts...

**Comment by DominusExult** [comment]
🤦‍♂️damn, I had noticed the cfg issue as well, but instantly forgot about it again.
Thanks for bringing it up again.
Maybe agentorangeguy can fix that for the next version. I'll ping him.

@Dragon-Baroque your questions:
1. In the beginning I knew there would follow a new version right away and then my son's health issues took part of my mind 🤷‍♂️
I'll ask agentorangeguy whether a new version is coming soon and whether to mirror it on our page as well.
I'm also wondering whether to add options to install the 3rd party mods to our Windows installer. Same way it installs the audio pack and our mods - not bundling but optional download&install.
Thoughts?

2. good idea actually. For bundling this would make it less error prone (and then have Exult recognize a zipped mod in the mod folder as well etc... something @marzojr has been thinking before).

**Comment by i30817** [comment]
I also forgot about the cfg, although I make sure it's correct in the installer for the apt package. It's a bit counterintuitive.

**Comment by nickbe** [comment]
It seems that the Exult Installer (just freshly downloaded) copies the default mods into a newly created "mods" folder below the original given game files:

![image](https://github.com/exult/exult/assets/10890765/091c4b7b-0de3-4567-b712-df55c3c5b96e)

A "forgeofvirtue" folder does not exist except in the appdata folder. But here there are no mods pre-installed.
And I still don't understand what purpose of these folders is.

The trick to make U6 run was indeed to create this structure when adding the mod:
![image](https://github.com/exult/exult/assets/10890765/1e3fae4d-2813-44e8-8160-870c6d18b598)

And below:
![image](https://github.com/exult/exult/assets/10890765/8e920385-6d64-4aae-8271-6163ffd90f10)
with the actual mod files inside the patch subfolder.

Thanks guys for the hint - Now I can start Ultima 6 😄

**Comment by DominusExult** [comment]
The folders in the appdata structure are just for storing the savegames (and the gamedat folder for the current save).

**Comment by nickbe** [comment]
Can multiple mods be combined? Like islefaq and keyring?

**Comment by DominusExult** [comment]
Not just by file copying, there is a lot of manual work involved

**Comment by nickbe** [comment]
Ok. Thanks for all your help with this guys 😃
