### ISSUE TITLE
Modifying the menu

### ISSUE THREAD

**Issue by nickbe** [exult/exult#361]
Now that the Ultima 6 mod is running and I can start by clicking on a menu item - added to the main menu - I wonder why the same thing seems not possible with the keyring mod.

I added the same kind of link into the menu:
![image](https://github.com/exult/exult/assets/10890765/00b23597-cac6-48b9-a3ab-d5b9ec669d63)

While link to U6 works perfectly fine now, I couldn't make the Keyring link work.
I tried to figure out what's wrong but I'm either blind to an obvious problem or maybe the two mods work in a different way.

```
<game>
      <blackgate>
        <title>ULTIMA VII - THE BLACK GATE
		AND THE FORGE OF VIRTUE</title>
        <path>..\Ultima\Ultima7</path>
        <keys>(default)</keys>
        <waves>jmsfx.flx</waves>
        <autonotes>(default)</autonotes>
      </blackgate>
      <keyring>
        <title>ULTIMA VII - THE BLACK GATE
		KEYRING</title>
        <path>..\Ultima\Ultima7\mods\Keyring</path>
        <static_path>..\Ultima\Ultima7\static</static_path>
        <keys>(default)</keys>
        <waves>jmsfx.flx</waves>
        <autonotes>(default)</autonotes>
      </keyring>
      <serpentisle>
        <title>ULTIMA VII - THE SERPENT ISLE
		ABD THE SILVER SEED</title>
        <path>..\Ultima\Serpent</path>
        <keys>(default)</keys>
        <waves>sqsfxsi.flx</waves>
      </serpentisle>
      <u6mod>
        <title>ULTIMA VI
		THE FALSE PROPHET</title>
        <path>..\Ultima\Ultima7\mods\Ultima6v1.1</path>
        <static_path>..\Ultima\Ultima7\static</static_path>
        <waves>sqsfxbg.flx</waves>
        <keys>(default)</keys>
        <autonotes>(default)</autonotes>
      </u6mod>
    </game>

```

**Comment by marzojr** [comment]
@nickbe Did you try out the above? If yes, did it work? Can we close the issue?

**Comment by nickbe** [comment]
Sorry, I was out of town for a few days 😁 
Yes indeed that was the problem. Now the config looks accordingly and works like expected:

    <game>
      <blackgate>
        <title>ULTIMA VII - THE BLACK GATE
		AND THE FORGE OF VIRTUE</title>
        <path>..\games\blackgate</path>
        <keys>(default)</keys>
        <waves>jmsfx.flx</waves>
        <autonotes>(default)</autonotes>
      </blackgate>
      <keyring>
        <title>ULTIMA VII - THE BLACK GATE
		KEYRING</title>
        <path>..\games\blackgate\mods\Keyring</path>
        <patch>..\games\blackgate\mods\Keyring\data</patch>
        <static_path>..\games\blackgate\static</static_path>
        <keys>(default)</keys>
        <waves>jmsfx.flx</waves>
        <autonotes>(default)</autonotes>
      </keyring>
      <serpentisle>
        <title>ULTIMA VII - THE SERPENT ISLE
		ABD THE SILVER SEED</title>
        <path>..\games\serpentisle</path>
        <keys>(default)</keys>
        <waves>sqsfxsi.flx</waves>
        <autonotes>(default)</autonotes>
      </serpentisle>
      <ultima6>
        <title>ULTIMA VI
		THE FALSE PROPHET</title>
        <path>..\games\blackgate\mods\Ultima6v1.1</path>
        <static_path>..\games\blackgate\static</static_path>
        <waves>jmsfx.flx</waves>
        <keys>(default)</keys>
        <autonotes>(default)</autonotes>
      </ultima6>
    </game>
