### ISSUE TITLE
SI Fixes: Knight Banquet & Fawn Trial Lock

### ISSUE THREAD

**Issue by WOGamer** [exult/exult#362]
Playing in 1.8 with SI fixes and the knighthood banquet and trial in Fawn are both broken

For the banquet, the doors don't unlock, if I hackmove them out of the way, the avatar heads in but just stands behind the guest of honor chair and nothing happens. Avatar doesn't sit in the chair and the dialog never starts

For the trial, the doors unlock and the avatar walks into the docket followed by whichever companion offended the liar's descendants and then nothing. The next conversation sequence never fires.

**Comment by KnightCaptainU7** [comment]
Interesting, since there's a known original Usecode issue with the Fawn Trial. The Avatar does not sit during the trial (none of the party does).

Are you possibly using a mod?

**Comment by WOGamer** [comment]
Running with SI Fixes as populated by Exult when I installed it

**Comment by DominusExult** [comment]
I have two ideas:
- it's been fixed by 1.9
- it is an incompatibility with 1.8 due to changes in ucc or so.

-> can you try with the current 1.9 snapshot?

And maybe provide savegames prior to these events?

**Comment by WOGamer** [comment]
Link below should go to a save just before the banquet
[exult01si.sav](https://drive.google.com/file/d/1u1WO1t-elBOxTdYcpzcb2ym2BUzalYaG/view?usp=drive_link)

**Comment by WOGamer** [comment]
Issue appears to persist in 1.9

**Comment by DominusExult** [comment]
I can reproduce and it seems to be some kind of usecode showstopper. If I use a really old version of SI Fixes it works (and if I just replace the old usecode with a new one it stops working).
since we have so many snapshot releases it might be doable to regression test it. Will do that later.

**Comment by DominusExult** [comment]
@WOGamer the very snapshot of SI Fixes before still works https://github.com/exult/exult/releases/tag/snapshot-v1.9.0.20230612

@marzojr seems f9741ad broke something (or some dependencies of mingw broke something right at that moment - still need to test with a ucc build on my machine and compiling SI Fixes usecode)

**Comment by marzojr** [comment]
I updated the constants in SI Fixes. Its next snapshot should fix this.

**Comment by WOGamer** [comment]
The previous snapshot worked.

Thanks for the fix.

Marking as Closed/Completed.
