### ISSUE TITLE
Exult port for Haiku

### ISSUE THREAD

**Issue by Begasus** [exult/exult#365]
First of all, let me congratulate you on the great job the team is doing here! 

I've been looking into creating a port/package to the OS `Haiku`, build is working fine out of the box for 32bit and 64bit, and the games can be played, so everything is looking good that far.
I'm only strugling to make exult save the exult gamedata to be saved in /boot/home/config/settings/exult (yes we have a different layout system), instead of /boot/home/.exult

I already created a small patch to move the configuration file .exult.cfg to /boot/config/settings/exult that works fine: https://github.com/haikuports/haikuports/blob/cb50d897eaff5c10b1221d9010eeda211d1700e6/games-engines/exult/patches/exult-1.8.patchset

I just can't figure out how to move the .exult directory to the settings directory, my attempts here did not do the trick:
```diff
@@ -798,6 +807,11 @@ static string Get_gamehome_dir(const string& home_dir, const string& config_dir)
 #elif defined(XWIN)
 	ignore_unused_variable_warning(home_dir, config_dir);
 	return EXULT_DATADIR;
+#elif defined (__HAIKU__)
+	ignore_unused_variable_warning(home_dir);
+	string gamehome_dir(config_dir);
+	gamehome_dir += "/game";
+	return gamehome_dir;
 #else
 	ignore_unused_variable_warning(home_dir, config_dir);
 	return ".";
```
Any pointers here were to look would be much appreciated.

**Comment by DominusExult** [comment]
I don't see __HAIKU__ being defined in the patchset. Does it get set automagically (this sounds sarcastic, it's not meant to, sometimes stuff gets set automatically to me ;))?
It should be in config.h - please check config.h after configure which system it gets set to.
(This would be the simple explanation why this change doesn't work but wouldn't explain why the patchset works, though 🤷‍♂️)

**Comment by rofl0r** [comment]
yeah, the haiku system compiler defines `__HAIKU__` and the haiku developer's approach to portability is to add couple ifdef's to the programs they patch into compliance, because it's faster than to write configure checks for functionality.

**Comment by Begasus** [comment]
Looking into config.h and configure.ac it's not in there, I could check with adding it in there, but usually this isn't really needed.
Thanks for replying.

**Comment by marzojr** [comment]
Does haiku use XWIN? Or maybe configure is defining XWIN on the way? Because if so, it is likely that the `#elif defined(XWIN)` block right above your code would be used instead of the haiku code.

**Comment by DominusExult** [comment]
Sorry, only now understand more when looking at it properly.
`gamehomedir` is actually *NOT* what you are looking for or misunderstanding what it does. This sets where Exult is looking for the games' data  in the predefined folders (so on macOS it finds the games in /Library/Application Support/Exult/blackgate or /Library/Application Support/Exult/serpentisle.
Exult does not save gamedata, it is only looking for it.

`savehome_dir` you set in the patchset is where it is set that Exult saves savegame files and the "gamedat" folder (more or less the current loaded game unarchived).
Exult will do that for each game in distinctive folders:
-blackgate
--gamedat
--exultNNbg.sav
-serpentisle
--gamedat
--exultNNsi.sav

**Comment by Begasus** [comment]
Expressed myself probably wrong in the first posts, what you described is ecxactly what I look for.
At the moment they are "saved" in ~/.exult, my intention is saving them in ~/config/settings/exult.

savehome_dir is working partialy, it saves the exult.cf file in ~/config/settings/exult

**Comment by Begasus** [comment]
> Does haiku use XWIN? Or maybe configure is defining XWIN on the way? Because if so, it is likely that the `#elif defined(XWIN)` block right above your code would be used instead of the haiku code.

That did the trick! Moved the Haiku block prior to the XWin block and stuff is saved now in the right place, thanks!

**Comment by DominusExult** [comment]
The exult.cfg location is set by config_dir not savehome_dir, so my guess is that the savehome_dir changes in the patchset is not working.
You can debug by having some printouts in the `#elif defined(__HAIKU__)` block (and maybe in the XWIN block, too, to see if that takes precedence)

**Comment by DominusExult** [comment]
> > Does haiku use XWIN? Or maybe configure is defining XWIN on the way? Because if so, it is likely that the `#elif defined(XWIN)` block right above your code would be used instead of the haiku code.
> 
> That did the trick! Moved the Haiku block prior to the XWin block and stuff is saved now in the right place, thanks!

did you set this for savehome_dir now? (because again, gamehome_dir shouldn't be doing what you thought it does).

**Comment by Begasus** [comment]
Patch updated, you can see the recipe and patchset for exult at: https://github.com/haikuports/haikuports/pull/9008/files

**Comment by Begasus** [comment]
> did you set this for savehome_dir now? (because again, gamehome_dir shouldn't be doing what you thought it does).

Right, for now gamehome_dir is where it "actually" searches for the original data? (atm stored/packaged in read-only directory - being /boot/system/data/exult)
So altering that path I could set it to a "write-able" directory? (would be easier for users as we can't package the original games)

**Comment by DominusExult** [comment]
nice!
If you want to add a default location for Haiku to look for the games, then gamehome_dir is the right place for this change.

**Comment by DominusExult** [comment]
> > did you set this for savehome_dir now? (because again, gamehome_dir shouldn't be doing what you thought it does).
> 
> Right, for now gamehome_dir is where it "actually" searches for the original data? (atm stored/packaged in read-only directory - being /boot/system/data/exult) So altering that path I could set it to a "write-able" directory? (would be easier for users as we can't package the original games)

yes, exactly! 
Great you could make it work. Actually I'm just now installing a VM of Haiku :)

**Comment by Begasus** [comment]
Also "fixed" the location for the data, now users can install those themselves without worrieing about packaging it before they can play! :)

**Comment by Begasus** [comment]
OK, only thing missing would be a nice icon (sometimes when there is an svg icon available I can convert that into something we can use to set the application icon), haven't found one, so probably will call on the community to see if someone can step up to create one. :)

**Comment by DominusExult** [comment]
The exult.icns in the macosx folder perhaps?

**Comment by Begasus** [comment]
> The exult.icns in the macosx folder perhaps?

Tried that one, didn't produce something we could use :/
