### ISSUE TITLE
Exult crash when enable Shortcutbar

### ISSUE THREAD

**Issue by djleon83** [exult/exult#370]
Dears,

This is my first time playing Ultima7 using exult engine.
Maybe i meet a bug?
When i launch exult, enable the "shortcut bar" in setup and apply, exult crashed.

my OS is win10, and exult is 1.8.0, i tried the last snapshot version, same.
 
here is the screenshot and my cfg file:
![Snipaste_2023-07-19_09-38-18](https://github.com/exult/exult/assets/86500310/d857d6b7-8540-4788-89b0-f8381bdaeba2)
![Snipaste_2023-07-19_09-39-05](https://github.com/exult/exult/assets/86500310/b8bcf552-8c37-4dda-ac38-3d49b47cf793)
[exult.cfg.zip](https://github.com/exult/exult/files/12090219/exult.cfg.zip)

**Comment by djleon83** [comment]
I tried edit the exult.cfg file.
After i set "shortcutbar" to "transparent", i could enter the game, exult didn't crash, but the "transparent" setting didn't work, shortcutbar's background is black.

**Comment by DominusExult** [comment]
Does this cause a problem while playing? Because that it does anything when not in the game *is* a bug, but it doesn't crash for me at least.

**Comment by djleon83** [comment]
> Does this cause a problem while playing? Because that it does anything when not in the game _is_ a bug, but it doesn't crash for me at least.
I could not enable the shortcutbar in Exult's setting, when this error occurred, i could only choose to abort the program in the error window, the retry and ignor button doesn't work.
I've tried edit the exult.cfg file, when i modified the "shortcutbar" parameter to "yes", everything is ok, the shortcutbar shows in game.
Maybe there is something wrong with the Exult setting or the windows installer.

**Comment by DominusExult** [comment]
The question was whether you could enable it while playing (press ESC) and not in the main menu through the *SETUP* option.

Can you disable/enable it now in the in game settings?

**Comment by djleon83** [comment]
> The question was whether you could enable it while playing (press ESC) and not in the main menu through the _SETUP_ option.
> 
> Can you disable/enable it now in the in game settings?

Oh, before i edit the cfg file , no,  when i changed the setting, the same error.
After i edit the exult.cfg, yes i can change the setting in game now.

**Comment by DominusExult** [comment]
I was able to reproduce it on iOS (through Xcode and the iOS simulator). 
Backtrace of xcode:
```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00007ff8376f4202 in __pthread_kill ()
#1	0x00007ff83774cee6 in pthread_kill ()
#2	0x00007ff800131e58 in abort ()
#3	0x00007ff800131144 in __assert_rtn ()
#4	0x0000000104152ea8 in Vga_file::get_shape(int, int) at /Users/Dominus/Code/snapshots/exult/shapes/vgafile.h:332
#5	0x0000000104152b92 in Shape_manager::cache_shape(int, int, int) at /Users/Dominus/Code/snapshots/exult/shapeid.cc:445
#6	0x0000000104152fc7 in ShapeID::cache_shape() const at /Users/Dominus/Code/snapshots/exult/shapeid.cc:463
#7	0x00000001041531f5 in ShapeID::get_shape() const at /Users/Dominus/Code/snapshots/exult/shapeid.h:216
#8	0x000000010443ce06 in ShortcutBar_gump::createButtons() at /Users/Dominus/Code/snapshots/exult/gumps/ShortcutBar_gump.cc:225
#9	0x000000010443d076 in ShortcutBar_gump::ShortcutBar_gump(int, int) at /Users/Dominus/Code/snapshots/exult/gumps/ShortcutBar_gump.cc:273
#10	0x000000010443d0d1 in ShortcutBar_gump::ShortcutBar_gump(int, int) at /Users/Dominus/Code/snapshots/exult/gumps/ShortcutBar_gump.cc:261
#11	0x000000010449f9aa in Game_window::set_shortcutbar(unsigned char) at /Users/Dominus/Code/snapshots/exult/gamewin.cc:3069
#12	0x000000010440d99a in GameDisplayOptions_gump::save_settings() at /Users/Dominus/Code/snapshots/exult/gumps/GameDisplayOptions_gump.cc:198
#13	0x000000010440d789 in GameDisplayOptions_gump::close() at /Users/Dominus/Code/snapshots/exult/gumps/GameDisplayOptions_gump.cc:65
#14	0x0000000104411961 in CallbackButtonBase<GameDisplayOptions_gump, Text_button>::activate(int) at /Users/Dominus/Code/snapshots/exult/gumps/Gump_button.h:116
#15	0x0000000104410b9f in GameDisplayOptions_gump::mouse_up(int, int, int) at /Users/Dominus/Code/snapshots/exult/gumps/GameDisplayOptions_gump.cc:282
#16	0x00000001041cab11 in Gump_manager::handle_modal_gump_event(Modal_gump*, SDL_Event&) at /Users/Dominus/Code/snapshots/exult/gumps/Gump_manager.cc:502
#17	0x00000001041cb4cd in Gump_manager::do_modal_gump(Modal_gump*, Mouse::Mouse_shapes, Paintable*) at /Users/Dominus/Code/snapshots/exult/gumps/Gump_manager.cc:720
#18	0x00000001044a4b82 in Gamemenu_gump::game_display_options() at /Users/Dominus/Code/snapshots/exult/gumps/Gamemenu_gump.cc:126
#19	0x00000001044a54b1 in CallbackButtonBase<Gamemenu_gump, Text_button>::activate(int) at /Users/Dominus/Code/snapshots/exult/gumps/Gump_button.h:116
#20	0x00000001044a4fe4 in Gamemenu_gump::mouse_up(int, int, int) at /Users/Dominus/Code/snapshots/exult/gumps/Gamemenu_gump.cc:174
#21	0x00000001041cab11 in Gump_manager::handle_modal_gump_event(Modal_gump*, SDL_Event&) at /Users/Dominus/Code/snapshots/exult/gumps/Gump_manager.cc:502
#22	0x00000001041cb4cd in Gump_manager::do_modal_gump(Modal_gump*, Mouse::Mouse_shapes, Paintable*) at /Users/Dominus/Code/snapshots/exult/gumps/Gump_manager.cc:720
#23	0x00000001044a5067 in Gamemenu_gump::do_exult_menu() at /Users/Dominus/Code/snapshots/exult/gumps/Gamemenu_gump.cc:185
#24	0x0000000104222010 in ExultMenu::setup() at /Users/Dominus/Code/snapshots/exult/exultmenu.cc:170
#25	0x0000000104224b50 in ExultMenu::run() at /Users/Dominus/Code/snapshots/exult/exultmenu.cc:455
#26	0x000000010455a487 in Init() at /Users/Dominus/Code/snapshots/exult/exult.cc:892
#27	0x00000001045553fe in exult_main(char const*) at /Users/Dominus/Code/snapshots/exult/exult.cc:611
#28	0x0000000104553a21 in ::SDL_main(int, char **) at /Users/Dominus/Code/snapshots/exult/exult.cc:430
#29	0x00000001047e0adf in -[SDLUIKitDelegate postFinishLaunch] at /Users/Dominus/Code/snapshots/exult/ios/SDL/src/video/uikit/SDL_uikitappdelegate.m:393
#30	0x00007ff800c0ddae in __NSFireDelayedPerform ()
#31	0x00007ff8003b3353 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
#32	0x00007ff8003b2eb0 in __CFRunLoopDoTimer ()
#33	0x00007ff8003b2637 in __CFRunLoopDoTimers ()
#34	0x00007ff8003acec8 in __CFRunLoopRun ()
#35	0x00007ff8003ac264 in CFRunLoopRunSpecific ()
#36	0x00007ff809b4024e in GSEventRunModal ()
#37	0x000000010d7667bf in -[UIApplication _run] ()
#38	0x000000010d76b5de in UIApplicationMain ()
#39	0x00000001047ded98 in SDL_UIKitRunApp at /Users/Dominus/Code/snapshots/exult/ios/SDL/src/video/uikit/SDL_uikitappdelegate.m:69
#40	0x0000000104782209 in main at /Users/Dominus/Code/snapshots/exult/ios/SDL/src/main/uikit/SDL_uikit_main.c:17
#41	0x000000010545a384 in start_sim ()
#42	0x00000001142af41f in start ()
```
To reproduce:
- run Exult and disable the shortcut bar
- rerun Exult, go to the Exult menu settings (not in game)
- enable the shortcut bar (yes)
-> on iOS this will crash Exult with the assert in vgafile.h. On macOS the shortcut bar is shown.

Solution: make sure the shortcut bar is no shown in the Exult menu settings?

**Comment by Dragon-Baroque** [comment]
Same crash in Linux :
- Activate the Shortcut Bar in the Game Display gump while in Game : OK
- Activate the Shortcut Bar in the Game Display gump while in Setup : crash

I would expect that the Game Display gump remains the same whether in Game and in Setup, if only to properly save the options in the cfg file. 
But could the Shortcut Bar Enable button only try to create the Shortcut Bar while in Game ?
I mean is there a way to know whether the current window is Game or not ?

**Comment by DominusExult** [comment]
We do this reverse check for the Face_stat buttons in `gumps/GameDisplayOptions_gump.cc` via `gwin->is_in_exult_menu()`. Apparently someone figured out that displaying the face stats in the Exult menu would not be a good idea :)
*I* just can't figure out how to do the check properly so the setting changes but doesn't load the shortcut bar in the exult menu.

**Comment by DominusExult** [comment]
If I change https://github.com/exult/exult/blob/master/gamewin.cc#L3068
from 
```
if(using_shortcutbar()) {
		g_shortcutBar = new ShortcutBar_gump(0,0);
```
to
```
if(!is_in_exult_menu() && using_shortcutbar()) {
		g_shortcutBar = new ShortcutBar_gump(0,0);
```
it works correctly. It sets the correct value in the cfg and reads it back when I reload the exult menu setup but doesn't try to display the shortcutbar. But when I start a game the shortcut bar displays.

**Comment by Dragon-Baroque** [comment]
> But when I start a game the shortcut bar displays.

Is it not what should happen ? 
I was about to propose a code change very similar but putting the in_exult_menu in factor to the whole if - including the disable case ...
```
    if(!in_exult_menu) {
        if(using_shortcutbar()) {
            g_shortcutBar = new ShortcutBar_gump(0,0);
        } else {
            gump_man->close_gump(g_shortcutBar);
            g_shortcutBar = nullptr;
        }
    }
```

**Comment by DominusExult** [comment]
Yes, this is exactly what should happen but poorly worded by me. I'll ceck your code. If it all works, it makes sense to do it this way

**Comment by DominusExult** [comment]
thank you @djleon83 for spotting this bug and especially taking time to report it.
