### ISSUE TITLE
Mods and patches with outdated txtmsg.txt

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#375]
I see that the Avatar pack is the actual culprit. It's txtmsg.txt is no longer compatible with Exult. The hex addresses have changed since then and the AP was never updated for that :(

_Originally posted by @DominusExult in https://github.com/exult/exult/discussions/368#discussioncomment-6533975_

**Comment by DominusExult** [comment]
@marzojr the outdated textmsg.txt is messing things up as the proper hex addresses have changed since 2007 :)

**Comment by DominusExult** [comment]
A quick check also found that the Keyring mod has wrong offsets, made obvious when you view the endgame.

**Comment by i30817** [comment]
Sounds like a annoying problem if that file can't be replaced completely. Maybe a editor tool to keep track of which entries are being overwritten for the current version of exult and warn about it?

**Comment by DominusExult** [comment]
Thanks to @Zhelkas both the BG and SI textmsg.txt files are updated with correct messages.
