### ISSUE TITLE
configure strips/overwrites user-supplied CXXFLAGS

### ISSUE THREAD

**Issue by mbanck** [exult/exult#38]
Around line 130 in `configure.ac`, all `-O` and `-g` options are stripped from `CXXLAGS` (and `CFLAGS` before, but there's a lot less C than C++ code in exult if at all I think):

```
# Lets clean up CXXFLAGS of -O[0-3gs]? and -g[0-3]?
for cxxflag in $CXXFLAGS; do
        AS_CASE([$cxxflag],
                [-O|-O0|-O1|-O2|-O3|-Os|-Og|-g|-g1|-g2|-g3], [],
                [NEWCXXFLAGS="$NEWCXXFLAGS $cxxflag"])
done
CXXFLAGS="$NEWCXXFLAGS"
```

Later on, `-g` and `-O` are set based on the value of `--with-optmization` (with `-O2` being normal/the default if that is not passed explicitly), but that means the user cannot set `-g` and `-O` independently.

I think `--with-optimization` should either check whether `CXXFLAGS` are already set and leave `-g` and `-O` alone, or provide another `custom` option or so, that just doesn't strip it out (that might mean that the above quoted `AS_CASE` call needs to be folded into the `--with-optimization` logic).

**Comment by marzojr** [comment]
This should be fixed in moth master and v1.6.x branches.
