### ISSUE TITLE
macOS 13 problems with Exult & Exult Studio drag and drop

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#390]
```
I have posted the two messages on Google. This first one does not bring any sensible answer, but the second one Looked for URLs on the pasteboard, but found none.`, points somewhat to WebKit or Safari or Firefox. Some browser engine, anyway.

Have you got a recent upgrade of Safari ? I mean since you last tried a Drag and Drop between Studio and Exult ... Could there be some Safari listening process in the background ?
```

_Originally posted by @Dragon-Baroque in https://github.com/exult/exult/issues/379#issuecomment-1702396909_
            
The only difference was that I rebooted my machine. But all points to something like that. The same snapshots work in earlier versions of macOS. I really have to investigate this more.

**Comment by DominusExult** [comment]
@Dragon-Baroque 
This is infuriating... At some point it worked flawlessly for every drop and then it stopped again.
I tested this with the SDL` testdropfile` test and drops from Exult Studio produced the same error. *AT FIRST*

Started it up again and drops were getting registered on `testdropfile`. And now it gets really weird:
When I dragged the shape first over `testdropfile` and THEN onto Exult the drop worked. Sometimes vice versa, first dragging over Exult and then dropping on `testdropfile` the drop errored out as well.

Then I observed everything with a Pasteboard Viewer App and there might be a clue:

When it fails the `public.file-url` had 26 bytes and when it succeeded it had 25 bytes.
Copying the `public.file-url` from the Pasteboard Viewer App I got the result that there is an extra control character `<NUL>` as my text editor shows. In an hex editor it shows as `00`
I have no idea why that happens and why it works sometimes and then not at all again.

**Comment by Dragon-Baroque** [comment]
> When it fails the public.file-url had 26 bytes and when it succeeded it had 25 bytes.

You may be on something, though.

The URI should be `file:///U7SHAPEID.0.199.0` : 4 ( `file` ) + 4 ( `:///` ) + 9 ( `U7SHAPEID` ) + 2 ( `.0` ) + 4 ( `.199` ) + 2 ( `.0` ) is 25 bytes. The emitter is `Store_u7_shapeid`  in `shapes/u7drag.cc`, and brothers `Store_u7_npcid`, `Store_u7_chunkid` and `Store_u7_comboid`. **All of them** return the string length **plus one** to hold a NULL at the end ( zero terminated string ). This makes a length of 26.

Could you retry changing, in `shapes/u7drag.cc`, the three `return 1 + snprintf` by `return snprintf` and the one `return ptr + 1 - data` by `return ptr - data` and see whether it works again ?

**Comment by DominusExult** [comment]
thanks! that seems to work. I have to try my older macOS versions, though. Not that it truncates the URI on these :)

**Comment by DominusExult** [comment]
I can confirm it working on macOS 13, 10.14 an 10.11.
By an educated guess, this is probably safe.

**Comment by Dragon-Baroque** [comment]
On my side, I have checked Linux, over X11 and over Wayland. Both are working.
I was about to ask you to check on Windows, but I realized this would be futile, the Drag and Drag code path is entirely different.

I shall prepare a commit for `exult-sdl3` shortly.
On the other hand, please tell me whether the fix should be tested on SDL 2. That is, if you would like this fix to be backported to to master.

**Comment by DominusExult** [comment]
Definitely backport it to SDL2. I've run into this problem with my SDL2 builds as well and my tests on the older macOS versions were with the SDL2 build.

I was about to test Windows and realized the same before actually doing it :)

**Comment by Dragon-Baroque** [comment]
Backporting to `master` shall be easy.
The question, then, is how to I keep `exult-sdl3` up to date after that ?
- Shall I leave `exult-sdl3` put, apply / cherry pick onto it the commits that shall come to `master`, or
- Shall I git rebase it and git push force ?

**Comment by DominusExult** [comment]
Probably git rebase? I'm really not the expert on this.

I'd even say, your migration is really so far finished that it should go into a branch of Exult. Doing that you could tidy up the commits of the last few days and sort them by topic :) Or just as we did it :)

Btw: with this drag and drop change, Exult also accepts drops when in fullscreen (but SDL2 also needs more `game_to_screen_hdpi` changes as the drop location is wrong).

**Comment by Dragon-Baroque** [comment]
Batch of three commits sent to `exult-sdl3`.

The second one, commit 45c657d7 fixes the current issue.

**Comment by Dragon-Baroque** [comment]
@DominusExult 
I have created and accepted the PR #392 onto `master`.
This is a backport to SDL 2 of the fix for the current issue we both validated for SDL 3, and that you validated for SDL 2.
Afterwards, I shall rebase the `exult-sdl3` branch.

**Comment by DominusExult** [comment]
Thank you!
