### ISSUE TITLE
Game Keeps crashing when I go into Combat

### ISSUE THREAD

**Issue by Senoj2693** [exult/exult#398]
How do I fix this? I have version 1.8 FYI.

**Comment by DominusExult** [comment]
Please use the snapshots, there was a combat crashing bug fixed.

**Comment by Senoj2693** [comment]
Snapshot of what exactly?

**Comment by Senoj2693** [comment]
Also my game crashed a couple of times when I switched to the Point Scaler

**Comment by DominusExult** [comment]
> Snapshot of what exactly?

http://exult.info/faq.php#whatis_snapshot
Get the snapshot at http://exult.info/download.php

**Comment by Senoj2693** [comment]
I managed to fix this by installing the 1.9 snapshot that someone else here mentioned

**Comment by fr0** [comment]
I also have this problem.

This seems serious enough that it would be worth creating a new official release if 1.8 is fundamentally flawed.
