### ISSUE TITLE
Ingame speech plays over endgame

### ISSUE THREAD

**Issue by wench** [exult/exult#403]
While recently playing through BG I noticed that The Guardian's speech that plays when you disable the barrier around the blackgate will play over the endgame sequence if you use the wand on the blackgate before the speech finished playing. This is obviously not correct as the original could not have acted this way as the original quits the main game to run the endgame executable. Question is what should Exult do about this?
* do nothing? In BG the initial part of the Endgame sequence Is long enough that the ingame speech should finish before the Guardian starts speaking in the Endgame and the blackgate is destroyed. In SI I don't think you could release the Great Earth Serpent fast enough to have the ingame speech play over the Endgame
* Immediately stop all ingame speech and sfx when starting the endgame? I imagine this is probably how the originals worked though I haven't personally tested them, I did watch a speedrun and the speech immediately stops.
* Wait for all speech and sfx to finish before starting the endgame sequence or make sure it has stopped before the critical moment in the end game sequence where it would cause a problem? This sems like a nice idea but I'm not sure if Exult's Audio system can even do this at the moment.

Tested this on Exult compiled from git a week ago(cf485e5906d7b321ea0f576942528cd4ec775e77). Not that much has changed since that commit.

**Comment by wench** [comment]
I'll fix this myself if I can get a consensus on what the fix should be.

**Comment by DominusExult** [comment]
I think option 3 would be the nicest.
I did notice that, too, when I tested the "you have played for x days" end screen, but was too focused on this than report it.

**Comment by wench** [comment]
A consensus of 1 was not quite what I was expecting but I'll make those changes and if someone wants to change things in the future so be it.

**Comment by wench** [comment]
If you want to test what I did easiest way is in game with cheats enabled press Alt-1 to open the sound tester. play a voice sample. Escape from the sound tester and then press F10 to play the endgame. The screen will grey out till the speech stops and then the endgame will start. Stop the speech while waiting with Escape, Enter, Space or Double clicks.

**Comment by DominusExult** [comment]
Thanks, I'll take a look when I return home (in a few days).

Your new quote is great 🤩
