### ISSUE TITLE
mt32emu playback sped/pitched way up

### ISSUE THREAD

**Issue by HurinSteadfast** [exult/exult#404]
Hello!

I'm using exult 1.8 on Windows 11.

I tried to use the mt32emu MIDI functionality.  Having placed the CM32L_CONTROL.ROM and CM32L_CM.ROM in:
C:\Users\<username>\AppData\Local\Exult\data, I do get output in-game but it is sped up and pitched way up.

The md5sums of my CM32L ROMs are verified as the ones Munt and DosBOX Staging support and I have no issue with playback in either of those applications.  Including Ultima VII in DOSBox.

I'm attaching an MKV file (wrapped in .zip) containing a video showing the difference between (first) digital music (recorded MT-32) and (then) the mt32emu playback.  As you can see/hear, the difference is stark.

Please let me know if you need other information in order to track down this issue.

sha256sum of ROMs:

Name: CM32L_CONTROL.ROM
Size: 65536 bytes (64 KiB)
SHA256: 08d68695e5bff6bbcbb751d6e4453db9f5ead0b5f41e86480798a04376dfe090

Name: CM32L_PCM.ROM
Size: 1048576 bytes (1024 KiB)
SHA256: 0dc50190bb7ea3fb212c970346b771a511772b528801e7eda6d27efda8c40698

[mt32emu-issue.zip](https://github.com/exult/exult/files/13193487/mt32emu-issue.zip)

**Comment by wench** [comment]
I can confirm this problem and I'm pretty sure I know the cause

**Comment by HurinSteadfast** [comment]
Thank you!!!!

**Comment by DominusExult** [comment]
Next automated snapshot, in a few hours, will have the fix.

**Comment by DominusExult** [comment]
@wench I just noticed that this change kills Mt32emu music on iOS (still works on macOS). It's still using the mt32emu driver (as stdout is dutifully reporting) but you can't hear anything. Other midi drivers can still be heard and I made sure that this change was the culprit.
Any idea what is happening?

**Comment by wench** [comment]
I have a pretty good guess why that might occur. I'd guess the reason is your ios build of libmt32emu hasn't been built with the cmake setting "libmt32emu_WITH_INTERNAL_RESAMPLER" set to true. My change makes use of the libmt32 sample rate converter so if libmt32emu is not compiled with a supported sample rate converter, there will be no sound. I should perhaps add in a check in Exult to see if sample rate conversion will work and if not, fail midi driver startup and output an error

**Comment by DominusExult** [comment]
Thanks, spot on :) Since I have to use Xcode to build mt32emu along with Exult, cmake is not being used and I have to pass this option on differently  :)

Also the error messages you added last night are much appreciated!

**Comment by Dragon-Baroque** [comment]
@DominusExult about the messages @wench added, could any of you fix the name `Mt32EMU` so that they look like the Midi driver name in the Audio Gump to `MT32Emu` instead ?

**Comment by DominusExult** [comment]
> @DominusExult about the messages @wench added, could any of you fix the name `Mt32EMU` so that they look like the Midi driver name in the Audio Gump to `MT32Emu` instead ?

done :)
