### ISSUE TITLE
Android 7.0 Compatible Version

### ISSUE THREAD

**Issue by Empyrean-Heaven** [exult/exult#427]
Greetings. I have recently discovered the joy of this port and game itself and wish to play it on my Android tablet. Regrettably, both 1.8.0 and 1.9.0 apks seem to be not installable on my device. I believe this is due to my tablet being Android 7.0. Is there a version somewhere compatible with my software?

**Comment by wench** [comment]
I don't know much about the android build of Exult but what I do know is that Android 7 is super old from 2016 and went end of life in 2019, and it is difficult to make android apps that properly supports really old versions and new versions of Android. You're probably out of luck trying to use an official build of the 
 Exult app with Android 7.  Chances are a custom build could be made to support that version of Android if an old version of the sdk and ndk was used.

**Comment by DominusExult** [comment]
I think the culprit is https://github.com/exult/exult/blob/a7536acd5c2f357a52746ce16d975db43a266195/android/app/build.gradle.in#L16 
We would need to lower this to SDK 24 (Android 7.0) or SDK 25 (Android 7.1) but I have no idea about `glob()`.
Mainly I agree with @wench that Android 7 is just really old.

**Comment by DominusExult** [comment]
But maybe @ceckak can chime in :)

**Comment by Empyrean-Heaven** [comment]
Aww. Are there perhaps any older versions that maybe could work out?

**Comment by DominusExult** [comment]
Sorry, no. There was an ages old version but since then the control and the shortcutbar came which makes the mobile version actually useful.

**Comment by ceckak** [comment]
I will try and take a look.  I haven't touched the code in quite a while, so it may take me a bit to muddle through getting a regular build working.  Will post an update here if/when I get a build working and have more detail on what breaks with the lower SDK version.

**Comment by DominusExult** [comment]
I'm closing this. Android 7 is just really old and unless we add glob ourselves (as I've seen at https://groups.google.com/g/android-ndk/c/vSH6MWPD0Vk) we don't know yet what other problems will arise by going lower with the SDK API
