### ISSUE TITLE
Exult Studio: Groups can overwrite groups by drag and drop

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#448]
Old bug from our bug tracker https://sourceforge.net/p/exult/bugs/2013/

When you have several groups in Exult Studio and you move one group by drag'n'drop, you can move it onto another group and it will seem to create a subgroup.
Then save groups, restart ES (or reload the mod or game) and the group you moved is duplicated and the group it was subbed at is gone. Essentially overwritten by the group you moved.

**Comment by Dragon-Baroque** [comment]
There is an easy, one line change solution : do not allow any drag and drop within the list of user groups.

**Comment by DominusExult** [comment]
Whee! Thanks
