### ISSUE TITLE
BGKeyring crashes to desktop in combat

### ISSUE THREAD

**Issue by DavidZvanZyl** [exult/exult#451]
At some stage mod decided to crash to desktop when you engage in combat.
Entering in combat is working but for combat the mod crashes

**Comment by DavidZvanZyl** [comment]
Caused by the musket. Unequiping the musket seems to work.

**Comment by DominusExult** [comment]
What version of Exult? 1.8 had some weapon ready crash that is fixed in 1.9

**Comment by DavidZvanZyl** [comment]
Yes, that was 1.8. Thanks, updated.

**Comment by rofl0r** [comment]
maybe put into new issue template a fat warning "ONLY REPORT BUGS YOU ENCOUNTERED USING THE DAILY SNAPSHOT. If you're using an older version, especially 1.8, the bug has been fixed already in all likeihood."
