### ISSUE TITLE
Exult/Exult Studio drag and drop fails on Apple silicon

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#453]
For some reason drag and drop from exult Studio to Exult fails on Apple Silicon machines.
Viewing the macOS pasteboard with the Pasteboard Viewer app indicates that nothing is wrong on the Exult Studio side, it still populates the pasteboard the same as on Intel machines. But Exult itself seems to not be able to read the pasteboard.

**Comment by Dragon-Baroque** [comment]
> Couldn't get a copy of a URL-flavored data from the pasteboard.
> Looked for URLs on the pasteboard, but found none.

Cannot find the message in Exult, nor in SDL, nor in GTK+. Suspect macOS proper, then.
Are the macOS Intel and the macOS Silicon at the same version ?

> In DRAG_BEGIN of Shape
> In DRAG_DATA_GET of Shape for 'text/uri-list'
> Setting selection data (154/0)

If you can find a macOS platform where is works, say Intel macOS, do you get the same `text/uri-list` ? Or does it switch to `public.file-url` ?

**Comment by DominusExult** [comment]
Both Apple Silicon and Intel machines are on the same macOS version
However I found a difference via the Pasteboard viewer:
On Apple Silicon you have both` public.url` and `public.file-url` after dragging from ES, and `public.file-url `is "odd".
![image](https://github.com/exult/exult/assets/3313896/d1bd81e5-e4a9-4569-866a-c2adec7d1f3f)
![image](https://github.com/exult/exult/assets/3313896/dc9adf4f-183f-4841-ae1a-829c666b1dc9)

Intel shows *two* `dyn`.something and the `public.file-url`
![image](https://github.com/exult/exult/assets/3313896/d0f21c34-d4b1-42a9-99dc-b88f7566c85d)

Watching the public.file-url on Silicon seems to be futile, then.

**Comment by DominusExult** [comment]
Trying to drop in the SDL testdropfile I get `Failed to get a sandbox extension` (both SDL2 and SDL3) which leads me to 
https://wadetregaskis.com/mac-app-sandboxing-interferes-with-drag-drop/ which kind of appears to me that this is SDL triggering this sandbox bug on Apple silicon

**Comment by Dragon-Baroque** [comment]
> Watching the public.file-url on Silicon seems to be futile, then.

I can just be that the `public.file-url` Drag and Drop item has its existence checked on macOS Silicon.

Anyway, you could perform a few tests to delimit the problem of the Drag and Drop from Studio to Exult in macOS Silicon :

1. As super user, try to create an empty file `/U7SHAPEID.0.156.0` on macOS Silicon, rerun Studio and Drag and Drop the same shape 156. Does Exult receive it ? Does the Pasteboard Viewer list it ?
2. SDL2 and SDL3 come with the `testdropfile` although it might not be built or distributed. If you can get its SDL2 version on macOS Silicon, you could try to Drag and Drop into it a regular file ( from the macOS Finder, I suppose ), then try to Drag and Drop a pseudo file from Studio, either a non existing file, or a file you created by hand [ by 1. ] and see for which of them the `testdropfile` can receive the Move and Drop events.
3. Then finally, run my SDL3 test branch `exult-sdl3`, but then you need also the updated commits to SDL3. Please tell me.

**Comment by DominusExult** [comment]
I've answered you in a mail but for verbosity I'll answer here as well:
1. This does not change anything (I had to create a symbolic link to be able to add a file to root to begin with as macOS has become very protective of its root) - except that when I drag and drop the empty file` /U7SHAPEID.0.156.0` via Finder onto Exult the shape 156 *does* get created.
2. For both SDL2 and SDL3 the drop ends with the logged error `Failed to get a sandbox extension`
3. I've sent you the failed loggings of this

You might have missed my post above your last post pointing at https://wadetregaskis.com/mac-app-sandboxing-interferes-with-drag-drop/ where `Failed to get a sandbox extension` lead me.

> Merely inspecting the UTIs in the pasteboard is fine – that doesn’t interfere with anything. So if all you care about is if any kind of file (or folder) is being dragged, you’re set. But if you want to only react to some types of files or folders, you need to know more.
> 
> If you ask for the URL – even without actually using it – you trigger some behind the scenes activity involving app sandboxing. This prevents the file being made accessible to your app if & when it actually is dropped into your app.

The partial workaround seems to use `NSPasteboardURLReadingSecurityScopedFileURLsKey` which seems to be something SDL2 and SDL3 need to implement (more likely we/you need to send a patch in).

**Comment by Dragon-Baroque** [comment]
> The partial workaround seems to use `NSPasteboardURLReadingSecurityScopedFileURLsKey` which seems to be something SDL2 and SDL3 need to implement (more likely we/you need to send a patch in).

You can certainly help by looking into XCode to find, if you can, when `NSPasteboardURLReadingSecurityScopedFileURLsKey` was defined, and perhaps whether it is supported by Apple Intel.

> Except that when I drag and drop the empty file `/U7SHAPEID.0.156.0` via Finder onto Exult the shape 156 does get created.

That is nasty. It means that Application Sandboxing applies to both the Drag and Drop emitter and the Drag and Drop receiver. Because the receiver ( Exult ) use the same ( SDL ) code to receive the file `/U7SHAPEID.0.156.0` whether it comes from Studio or from Finder.

> Pasteboard Viewer also has an empty public.utf8-plain-text. It did however paint the correct sized green grid in Exult for any dragged shape.

The green grid is displayed because Studio sends a message to Exult by the communication socket at the Drag Begin, providing the needed information to display the grid.

And

**Comment by DominusExult** [comment]
> > The partial workaround seems to use `NSPasteboardURLReadingSecurityScopedFileURLsKey` which seems to be something SDL2 and SDL3 need to implement (more likely we/you need to send a patch in).
> 
> You can certainly help by looking into XCode to find, if you can, when `NSPasteboardURLReadingSecurityScopedFileURLsKey` was defined, and perhaps whether it is supported by Apple Intel.

No mention of it in any of the SDKs.

> > Except that when I drag and drop the empty file `/U7SHAPEID.0.156.0` via Finder onto Exult the shape 156 does get created.
> 
> That is nasty. It means that Application Sandboxing applies to both the Drag and Drop emitter and the Drag and Drop receiver. Because the receiver ( Exult ) use the same ( SDL ) code to receive the file `/U7SHAPEID.0.156.0` whether it comes from Studio or from Finder.

However, I found another curiosity: via the official emulation layer (Rosetta2) you can run Intel compiled applications on the Apple Silicon.
An Intel compiled Exult Studio outputs the correct drag data that can be dropped successfully on an Apple Silicon Exult. Pasteboard Viewer does again show the correct drag data.
(vice versa, Apple Silicon Exult Studio with Intel Exult does not work)

**Comment by DominusExult** [comment]
I've inquired at the gtk-osx discussion https://github.com/jralls/gtk-osx-build/discussions/92 and was pointed at https://gitlab.gnome.org/GNOME/gtk/-/issues/6480 - the discussion certainly points at it possibly being fixed in current gtk3 code.
As John Ralls suggest I'll  try with a git build of GTK3 tomorrow.

**Comment by DominusExult** [comment]
Using Gtk3 git did indeed fix the problem.
@Dragon-Baroque thanks for helping so much!

**Comment by Dragon-Baroque** [comment]
Thank you, but I feel frustrated.

The GTK+ 3 issue points to a merge commit fa1fd6 almost ( today ) at the top of the branch `gtk-3-24`. The merge commit merges commit 7e9676 into `gtk-3-24` with changes :
```
Date:   Tue Feb 27 12:31:16 2024 -0800

    Fix Cocoa pasteboard constants for gtk.
    
    Corresponds to gdkselection-quartz changes in f30ed5ddc.
    Fixes https://gitlab.gnome.org/GNOME/gtk/-/issues/6480

 gdk/quartz/gdkquartz-gtk-only.h  | 14 ++++++++++++++
 gdk/quartz/gdkselection-quartz.c | 20 ++------------------
 gtk/gtkquartz.c                  | 13 +++++++------
 3 files changed, 23 insertions(+), 24 deletions(-)
```

I am quite willing to accept that this fixes our problem, I mean why Apple Silicon was not working and is working now.

But I do not understand how the Cocoa pasteboard problem the commit 7e9676 fixes could not impact Apple Intel too, I mean _why Apple Intel was working when Apple Silicon was not_. Because I do not see anything Apple Silicon specific in the commit. Were by any chance your GTK+ 3 versions different in your two Apple machines ?

**Comment by DominusExult** [comment]
I'll check again but I'm pretty sure that I used the same release for both my intel and apple silicon builds (as I glue them together for one universal build).
- My explanation is that Gtk3 used deprecated pasteboard functions (by not correctly setting the macOS min/max defines) and these still work on Intel but not anymore on Apple Silicon 🤷‍♂️

**Comment by DominusExult** [comment]
However thinking about it, my Intel builds are targeting macOS as low as 10.11 while the Apple builds are targeting 11.1+ (Apple Silicon is only available since macOS 11). So that is likely to have played a role.

**Comment by Dragon-Baroque** [comment]
> However thinking about it, my Intel builds are targeting macOS as low as 10.11 while the Apple builds are targeting 11.1+ (Apple Silicon is only available since macOS 11). So that is likely to have played a role.

It could be the very same with GTK+ 3. Are we able to see the target when we receive a brew binary, say gtk3, on both Apple Intel and Apple Silicon ? If not, how is it set by the build process, and is it visible to the source Git tree of GTK+ 3 ?

**Comment by DominusExult** [comment]
What I meant is that both Exult Studio and Gtk+3 were built with macOS target 10.11. I'm building Gtk+3 via the project gtk-osx https://gitlab.gnome.org/GNOME/gtk-osx which is specifically aimed at making it easier to bundle Gtk apps on/for macOS. And this also lets you set the minimal target (for Exult/Exult Studio for Intel I have to use `CFLAG  -mmacosx-version-min=10.11` and `export MACOSX_DEPLOYMENT_TARGET=10.11`, gtk-osx does that for all libs when you set the target). If you don't set the minimal target every build will only work on the build machines target and newer macOS - fine for testing but not useful for providing snapshots.
Both Exult Studio and Gtk+3 need to be build with the same target or things go weird :)
And I just tested this, if I don't set the target, build on the macOS 14.x Intel machine, the pasteboard problem happens with the latest Gtk+3 *release* (which doesn't have the fix yet, of course).
So the reason my Intel build was working was the lower target, which explains why the fix is not Apple Silicon specific.

**Comment by Dragon-Baroque** [comment]
> What I meant is that both Exult Studio and Gtk+3 were built with macOS target 10.11.
> Both Exult Studio and Gtk+3 need to be built with the same target or things go weird :)

I did not realize that GTK+ 3 was bundled with Exult Studio. Like Windows. Thank you.

> And I just tested this, if I don't set the target, build on the macOS 14.x Intel machine, the pasteboard problem happens with the latest Gtk+3 _release_ (which doesn't have the fix yet, of course).

Precisely. The fix closes a mismatch in GTK+ 3 about the Drag and Drop MIME contents. With the SDK at 10.14+, the new content names replaced the older deprecated content names, but not everywhere in GTK+ 3. The fix makes the replacement complete.

So I think that both the older names and the newer names work in macOS Intel and macOS Silicon, but the newer names do not work exactly the same as the older names. Recall for example that the 6480 issue you were referred to was about a spurious `\r\n\` in an URL, which tells that the older names support several URL, but the new ones don't, you have to do this differently. So the mismatch broke the Drag and Drop of files when GTK+ 3 when built with SDK 10.14+. Until the fix.

Explanation is clear. Frustration is no longer. Thank you for your time.
