### ISSUE TITLE
Game Display option button crashes game

### ISSUE THREAD

**Issue by xSKKx** [exult/exult#454]
Using 1.9 snapshot. AIO data pack. Interactions mod.
I have no idea as to what could be causing this.
All other options work fine.

**Comment by DominusExult** [comment]
Can you provide your stdout.txt and stderr.txt? Assuming you are on Windows they can be found at the same place where the exult.cfg is http://exult.info/faq.php#where_cfg
And does the Game Display button work on an unmodded game?

**Comment by xSKKx** [comment]
The button still crashes from the main screen as well without loading any mod.
When I load up from the exult.exe and don't select any mod.

Using the Setup button at the bottom of the main screen still crashes the game when trying to select Game Display.
[stderr.txt](https://github.com/exult/exult/files/14630634/stderr.txt)
[stdout.txt](https://github.com/exult/exult/files/14630635/stdout.txt)

**Comment by wench** [comment]
Can you provide your exult.cfg

**Comment by xSKKx** [comment]
Figured it out.
I forgot that I had the Quests and Interactions patch in the config as required to run that mod.
That is the issue.
When I use the original config the Game Display opens.

I suppose in the future I can configure what is in the Game Display before using that mod.
Anyway, here is the config.
[exult.txt](https://github.com/exult/exult/files/14637669/exult.txt)


Thank you for the replies.

**Comment by DominusExult** [comment]
> I forgot that I had the Quests and Interactions patch in the config as required to run that mod.
> That is the issue.

Could you elaborate? AFAIK it doesn't need to be at all in the config (I have it running as a regular mod and no need for anything in  the cfg). Can you show me that cfg?

**Comment by xSKKx** [comment]
Well, according to the installation instructions in the readme file....
2. Installation
---------------
1. Extract this archive to your Exult directory - this will create a folder inside called "quests_and_interactions" that contains the patch.
2. Add the following code to your exult.cfg, inside the <blackgate> configuration section:
<patch>
./quests_and_interactions
</patch>
3. Run Exult and start a new game!

IMPORTANT: YOU MUST START A NEW GAME! This patch adds new objects into the gameworld to support a quest, and if you try to run from a saved game those objects will not be there (meaning the quest will not function properly).
[readme.txt](https://github.com/exult/exult/files/14641496/readme.txt)

So, do I not need to add those lines in the config in order for this mod to function?

**Comment by DominusExult** [comment]
Ah, I see, this let's me test what the problem may be.
But no, if you download the Q&I from our download page http://exult.info/download.php you can just place everything in your mod folder and it will show up as a mod you can play.
