### ISSUE TITLE
Prepare a new release? Version 1.10

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#457]
Hi all,
seems a new version should be prepared. !.8 is plagued by the git fixed weapon ready crash, we have better combat and lots under the hood.
So what are your thoughts? Would you mind going through the bug tracker to find stuff that would make sense to fix before?

Next version should be a 2.0 version :)

@marzojr @drcode1 @wench @tristantarrant @Dragon-Baroque

**Comment by wench** [comment]
Sounds like a good idea. We could feature freeze the code base right now and it wouldn't make much of a difference as no real active development is occurring right now. Larger work in progress changes would be best deferred till after the 2.0 release. Trying to rush SDL3 or input refactoring into the 2.0 release seems a little risky.

**Comment by marzojr** [comment]
> Sounds like a good idea. We could feature freeze the code base right now and it wouldn't make much of a difference as no real active development is occurring right now. Larger work in progress changes would be best deferred till after the 2.0 release. Trying to rush SDL3 or input refactoring into the 2.0 release seems a little risky.

I agree 1000‰ on all counts.

**Comment by Dragon-Baroque** [comment]
> Seems a new version should be prepared.

Fully agree. Apart from the "version" name, unless I misunderstand something :

Proposal : Indeed we code freeze `master` and cut off it a replacement for 1.8 named, say, "1.10". Rather soon.
After that, the snapshots of `master` take the name "1.90git" or 1.99git" as pre 2.0 and we start discussing 2.0's content and schedule.

Of course, I shall take care of SDL 3, but at the moment, it is not only incomplete and "risky", it is irrelevant until SDL 3.2 comes out as the first public release and gets distributed widely. By now, the next incoming Linuxes of April 2024 only offer SDL 2.30.

**Comment by DominusExult** [comment]
All fair points and expected :)

> Proposal : Indeed we code freeze master and cut off it a replacement for 1.8 named, say, "1.10". Rather soon.

Makes good sense, didn't think of that. I was kind of mind locked into single digits minor versions.

> After that, the snapshots of master take the name "1.90git" or 1.99git" as pre 2.0 and we start discussing 2.0's content and schedule.

To prevent us locking ourselves in, I'd propose the next git version to be 1.11 then. 

But a port to SDL3, Marzo's SDL event refactoring etc, all warrant a 2.0 release, which should then be the next big goal, IMO. Maybe even, if I dare to dream, the detaching of gumps rendering from map rendering :)

> By now, the next incoming Linuxes of April 2024 only offer SDL 2.30.

That's not too far off the last SDL release, to be fair. There have been worse gaps :)

**Comment by wench** [comment]
> detaching of gumps rendering from map rendering
Yeah that would be a 2.0 class feature. With the other big changes I've been waiting for them to be merged before messing with everything

**Comment by marzojr** [comment]
I would say that next Git version is 1.11, and we change to 1.99 when those major features are ready.

Anyway: add issues here in the [project](https://github.com/orgs/exult/projects/1) I made for it.

**Comment by DominusExult** [comment]
I think once @wench 's fix for the black line is confirmed and committed we can go for a 1.10 release and move the remaining 1.10 assigned issues to a later release.

**Comment by wench** [comment]
Yeah my fix isn't ready yet. after fixing one set of problems I found more and a crash

**Comment by DominusExult** [comment]
created a new branch with 1.10 release stuff and put the correct version number everywhere.
Tomorrow I'll start with creating the Windows and macOS installers and test if these work correctly and don't print anywhere the old version.

**Comment by DominusExult** [comment]
I'm almost ready but am waiting for @agentorangeguy's new version of the Ultima VI mod, so it is ready at the same time.

There is one other thing:
I want to try and get Exult approved on the iOS AppStore again. Last time there were several hurdles, among them that our warning message on first startup of Exult without data files will not be allowed on the AppStore.
I'm proposing to change it to:
```
Welcome to Exult
To play you need the static data for either
"The Black Gate" or "Serpent Isle".
```
instead of
```
Warning
Could not find the static data for either
"The Black Gate" or "Serpent Isle".
```

**Comment by wench** [comment]
I don't think there is any reason not to change the message.

**Comment by DominusExult** [comment]
I did the change but alas, the AppStore review rejected Exult again.

> Guideline 4.2.3 - Design - Minimum Functionality
> 
> Your app did not include sufficient content in the binary for the app to function at launch, and we were required to download or unpack additional resources before we could use it.
> 
> 
> Next Steps
> 
> To resolve this issue, please revise your app to ensure that users can use the app on launch without needing to download or unpack additional resources.

Maybe, just maybe, I can whip @malignantmanor's dev game resources into shape :)
![image](https://github.com/user-attachments/assets/d4aac0e3-40a4-422d-bd0c-d488d947a75e)

Later today I will release Exult 1.10!!!

**Comment by DominusExult** [comment]
the new version has been released.

Feel free to mess with master! :)

**Comment by DominusExult** [comment]
As we need a bugfix release, mainly for adressing the Windows crash (and Android problem with getting mods installed), I'm preparing a new 1.10.x release. What should I version it? **1.10.1** or **1.10.2** ?

Additional changes are the new icons and minor fixes.

**Comment by wench** [comment]
I would just go 1.10.1 we haven't done one of these before so we don't have history to guide us. Bumping u

**Comment by Dragon-Baroque** [comment]
I agree with 1.10.1. Alternating dev and release - say 1.10.1, 1.10.3 ... for dev, and 1.10.0, 1.10.2 ... for release - does not hold since the dev is in master as 1.11.

**Comment by DominusExult** [comment]
Thanks, that was my thought as well.
I‘m preparing the binaries atm and will release later today

**Comment by DominusExult** [comment]
Released earlier :)
