### ISSUE TITLE
Crash in Studio opening the Combo set of the Keyring mod

### ISSUE THREAD

**Issue by Dragon-Baroque** [exult/exult#458]
Since the various "Reworking endian input" commits and especially mine : 4dd78ce5bb, opening the Studio onto Forge of Virtue plus the Keyring mod and opening the Combo browser => Crash.

Diagnostic : While the `Serial_in` and `Serial_out` string readers in `server/objserial.cc` now pre-read and pre-write the string length as a 64 bits `size_t`, the combo names in the Keyring `combo.flx` remain with a 32 bits `int` string length.

What do you think ? That serialized strings above 4G is overkill, or can the Keyring `combo.flx` be fixed ?

And are there potential other places, like names in the Shape files, that would be impacted the same way ?

**Comment by wench** [comment]
If strings are larger than 4GB there is a serious problem and I wouldn't imagine the state of the program to be all that stable. I find it quite reasonable to use 32 bits for string sizes.  
Might need some handling for detecting existing files that have 64 bit sizes, if the size is read as 32 bit and the first 4 bytes of the string are all zero then it might be enough to detect that the size is actually 64 bit. Alternatively if the size is read as 64 bits and the length would exceed the size of the read buffer then it is probably 32 bit. However i have noticed that the Serial_in and Serial_out classes do no bounds checking at all. This needs fixing .
