### ISSUE TITLE
Usecode script arrays not stopped in mapedit mode

### ISSUE THREAD

**Issue by marzojr** [exult/exult#468]
I found this one by accident when investigating #152 : if you toggle mapedit, almost everything is paused; but usecode script arrays continue running uninterrupted. They should probably also be delayed. Maybe even most time sensitive entries in tqueue?

Disabling all entries in tqueue during mapedit is not feasible, though, because the Avatar cannot move in this case.

**Comment by DominusExult** [comment]
There are also shape animations that could use stopping. For example there is a plant opening/closing which makes placing anything beside it a hassle as its animation interferes with the dragging of shapes.
