### ISSUE TITLE
Video options gump slightly messed up by clang-tidy and previously in merged-devel

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#47]
@marzojr 
fc65495a messed up the scalers list, result is that the button is not presenting the scaler names anymore

At some point in the merged-devel branch the video options got altered, so the "Game Area" button would show the 320x200 option twice (normally it switches between 320x200 and Auto).

In 87342f9a one of the 320x200 options got replaced with 0x0.

**Comment by marzojr** [comment]
fc65495 I can see what went wrong. The other one that caused an issue was 0703bee4.

I can see no way that 87342f9 would cause the 0x0; must be a different issue with undefined behavior along the way which just happens to give a 0x0. I can't see it on my end; can you still reproduce the last bit?

**Comment by DominusExult** [comment]
can't reproduce with your fixes. Thanks!

**Comment by DominusExult** [comment]
One thing I noticed with the iOS build:
it gives me the additional game area options "400x250" "480x300". When I use "480x300" the game area changes correctly but when I close and enter the Video Options gump again, it paints "400x250" on the Game Area button.

(and how does it add those two options anyway with the new code? I'm puzzled)

**Comment by marzojr** [comment]
The options are generated from game_resolutions array, which is populated elsewhere (line 296-303).

As for the other issue you are seeing, the game_resolutions index was never updated to account for the game resolution given the additional iphoneos options.

I am doing something to simplify/improve the code and address this.
