### ISSUE TITLE
Windows installer including the Ultima VI mod (and other mods)?

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#474]
It might be beneficial to include the Ultima VI mod and other mods (though Glimmerscape is currently the only one of those not deprecated), the same way we include our mods: You select them, they get downloaded and installed along with Exult.

@agentorangeguy if this were acceptable for you, I would like to include the Ultima VI mod. However there are two things to discuss on this:
- currently your download has the problem with the cfg file (not correct location in the zip
- no unified download as it changes with each release
My proposal is that you either fix the cfg problem (and maybe the unified download link) on your side or we add a fixed download to our download page (currently we have a direct backup copy).

**Comment by wench** [comment]
I have concerns about including third party mods that we are not responsible for, But I guess we already do give a lot of support for the U6 mod and if we include it will install without issues so it might not make much difference. We really could do with some way to indicate who the source of the mod is, and we didn't create it. I have seen some amount of confusion around the place with people thinking that we made it.

**Comment by DominusExult** [comment]
I will see what to label these to make it clear in the install tree view.
For now I think "third party mods". Let me write the iss file to show how it will look.

At least for the U6 mod it will be a good thing as people are getting confused how to install it :)

**Comment by DominusExult** [comment]
@wench The installer would look like this (also added sizes of these and the other other downloads). Anything you would like to be changed?

![image](https://github.com/exult/exult/assets/3313896/e22a3e7b-2d8d-4a77-a390-bfe88d498bfb)

**Comment by wench** [comment]
Seems about all that can be expected. I don't think anything needs to be changed.

**Comment by i30817** [comment]
Android should have something similar, imo.

**Comment by DominusExult** [comment]
The Android port has this on its ToDo list, and for other systems, I recommend a new issue and possibly a pull request
