### ISSUE TITLE
Read only forum broken by SF upgrade to PHP 8.x

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#486]
When I switched us to the secure SF host we got upgraded to PHP 8 and this broke our phpbb forum as our version is not compatible with PHP 8. 
The forum needs to be migrated to a newer version and then it should *just* work.

I'm assigning this to myself but it's low priority atm but I'll get it done.

**Comment by rofl0r** [comment]
fyi they also "upgraded" to use cloudflare https://sourceforge.net/p/forge/site-support/25671/ which means a lot of users will no longer be able to access it - basically everyone using a non-mainstream browser, a vpn, a proxy, or anything else that cloudflare considers undesirable.

**Comment by DominusExult** [comment]
ow, that is unfortunate :(

**Comment by DominusExult** [comment]
The forum works again (in read only mode) - the forum software is updated and thus works with php8.2 again.
