### ISSUE TITLE
Music Looping Behavior

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#491]
> Concerning the music looping.
> In the original, it went like this:
> As long as you are in the music area (like the stables at the start, a tavern or dungeon) the music would loop, even if you have gumps open or hold a conversation. Once you DO leave the area, the music would run out and then switch back to ambient sounds (unless another music is triggered).
> In Exult, there are two behaviors:
> -With looping enabled, the music loops endlessly, until you trigger a different music! The trigger that once you leave the music area there won't be more loops is missing. Thus you also never hear embient sounds (birds and stuff).
> -Without looping, the music just runs once and won't do so again unless you again enter the building in question or run over a very specific trigger.
> I compared it with the original. Right at the start in the stables, the song loops until you leave the stables, then it won't appear again. In Exult, the behaviors above happen.
> That's what I meant that the looping doesn't work like the original (in the original, the looping was quite clever).

> This is also incredibly annoying in SI with the Fellowship music never stopping, just hanging on a buzz.

from our old SF tracker https://sourceforge.net/p/exult/bugs/1990/

**Comment by NotStanley4330** [comment]
I can poke at this one as well because I looked at some of the audio code recently. I definitely remember this one dissuading me from playthroughs in Exult vs DOSBox previously, as I got really sick of the over blasting music that made it seem like Ultima 6 all over again lol. I'd bet we can do a similar thing to weather effects where you track distance from an egg and just have it no longer loop once you get far enough away.

**Comment by DominusExult** [comment]
relevant is this as well https://sourceforge.net/p/exult/patches/104/

And some other music track bugs https://sourceforge.net/p/exult/bugs/1839/ https://sourceforge.net/p/exult/bugs/1838/ and https://sourceforge.net/p/exult/bugs/1843/ - Might need to open a separate issue for those.

**Comment by wench** [comment]
we interpret the music egg's looping flag to mean loop endlessly but it would make sense if it actually meant loop while the egg is in proximity. As it is there is no way to stop a track from looping once it has started so I'll need to make changes to the music player. Asigning this to myself

**Comment by DominusExult** [comment]
D‘oh, I never realized that THIS is what is odd about the looping music, of course it should only loop around the egg.

**Comment by wench** [comment]
I should have this ready to push in a day or so. I need to do some more testing to make sure it is working as intended (at the moment I'm not convinced it is)

**Comment by wench** [comment]
I was right things are broken and i need to make sure that I hopefully just made an incorrect assumption and didn't completely break something fundamental in the egg code.
