### ISSUE TITLE
Background sfx music *tracks* are really annoying and the code has issues

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#498]
In the Background_noise function https://github.com/exult/exult/blob/master/gamewin.cc#L158 there are some issues:

1. I really think the sfx tracks (4 (rainstorm), 5 (snowstorm), 6 (outside), 7 (nighttime)) are just noise with *some* little differences. IMO these should be disabled and only use the sfx for day and nighttime, defined later on.
2. We somehow overlooked that other music devices than digital, mt32(emu) or adlib can and should play the DangerNear und Dungeon tracks.
3. the wave sfx need their volume drastically reduced (nighttime AUDIO_MAX_VOLUME - 230, daytime AUDIO_MAX_VOLUME - 240)
4. we check twice for `if (hour < 6 || hour > 20)` (or `if (bghour < 6 || bghour > 20`) even though we have already made this the `bool nighttime`

IMO at least the nighttime and outside sfx music tracks should be disabled. And the code needs to make allowance for other music drivers to play DangerNear and Dungeon music.
(3 & 4 are easy enough to fix).

@wench @marzojr what are your thoughts?

**Comment by DominusExult** [comment]
Correction: Dungeon (track 52) is an "ambient" track as well which doesn't play nicely on other drivers.
But DangerNear (track 10) is a "real" track.

**Comment by DominusExult** [comment]
I've created a patch that needs review as I'm not so sure about whether I did this correctly.
[fix_sfx_tracks.patch](https://github.com/exult/exult/files/14938670/fix_sfx_tracks.patch)
https://pastebin.com/RWR1mQph

This disables the nighttime and daytime sfx tracks, enables DangerNear for all drivers, plays sfx waves for day and night (and also for SI as with ffdbb2159 these play correctly).

**Comment by wench** [comment]
As I am fixing the music  looping elsewhere this function should not be stopping music to play ambient sound except maybe for danger music if the originals would override the general music with the danger track, if I have done everything right there would be no need for the bee cave exception  as the ambient sounds will always wait for the music to stop by itself and while in the bee cave them music will never stop but once leaving it will stop repeating.

**Comment by wench** [comment]
It feels like there should be some music priority mechanism.
Combat music is highest priority and overrides everything 
Next priority would be music played by usecode
Then music played by jukeboxeggs
The danger music would be next if it works as I think it should 
lastly the ambient tracks can only play if nothing else is playing

**Comment by DominusExult** [comment]
Updated patch without beecave check, removed FMOpl from drivers that can play the ambient tracks, re-enabled the daytime ambient track and disabled the daytime sfx when Ogg/MT32 driver OR another track is being played.

**Comment by DominusExult** [comment]
> It feels like there should be some music priority mechanism.
> Combat music is highest priority and overrides everything
> Next priority would be music played by usecode
> Then music played by jukeboxeggs
> The danger music would be next if it works as I think it should
> lastly the ambient tracks can only play if nothing else is playing

This sounds like a good idea

**Comment by DominusExult** [comment]
Updated the patch again, made some mistakes, foremost one that crashed Exult when music was disabled but SFX enabled :)

Anyway, @wench, while you are working on music looping, may I commit this (along with the bee cave check until you commit yours) or should I rather hang on to it for now?
