### ISSUE TITLE
NPC schedule bug - where is Lord Marsten?

### ISSUE THREAD

**Issue by elektronomikon** [exult/exult#501]
Hi,

in the first several minutes of gameplay i noticed the town of monitor getting eerily empty - Lord Marsten could not be found at all! Even worse, on my voyage to moonglow i spotted Zulith in the middle of the ocean :-)

So i started the game anew and took screenshots (attached) of Marsten's NPC  schedule right at the beginning of the game, after entering monitor and after talking to him.

I'm playing on Debian Linux with Version 1.8.0

Thanks in advance!
![2024-04-11_13-18 new game while at beach](https://github.com/exult/exult/assets/6134910/47853564-40d5-4613-9eda-02aa64a2575c)
![2024-04-11_13-20 after entering monitor](https://github.com/exult/exult/assets/6134910/b6470a04-4698-4883-b906-1fd468b27d59)
![2024-04-11_13-22 after talking to marsten](https://github.com/exult/exult/assets/6134910/a34b28ab-376b-4dd8-a8bf-ecda337ed68b)

**Comment by elektronomikon** [comment]
edit: fixed screenshot ordering

**Comment by elektronomikon** [comment]
Thanks, i'll give compiling the current git tree another try

**Comment by elektronomikon** [comment]
No, still Marsten goes about thieving - i'll take a look if my game files are somehow corrupted.

**Comment by elektronomikon** [comment]
It worked with the gog.com version ...

**Comment by DominusExult** [comment]
Thanks for checking! Do you still have the faulty install and could you share it (to forum@exult.info)? Just out of interest what is wrong with it.

**Comment by rofl0r** [comment]
maybe it'd be a good idea to do a checksum on the gamefiles to detect known good versions and otherwise print a warning of sorts ?

**Comment by marzojr** [comment]
Also maybe run `exult --verify-files` with the broken installation.
