### ISSUE TITLE
Audio Volume Mixer WIP

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#502]
I've created a new gump to control the volume of music, sfx and speech.

So far it can only read and write the settings of exult.cfg.

Atm I'm stumped to actually move the slider via the scroll buttons, dragging with the mouse or mousewheel. This is out of my meager programming knowledge and I'm hitting a wall.

Furthermore this is not hooked up to the actual volume of these sources.
SFX can probably easily be done via `AUDIO_MAX_VOLUME`, music maybe via `volume_curve`. AFAICT there is nothing to control the volume of voc files.

I have this branched in my fork of Exult at https://github.com/DominusExult/exult/tree/volume_mixer.
Pressing Shift+V will open the gump.

![image](https://github.com/exult/exult/assets/3313896/fb34c13d-4136-4a7e-ab74-19bbeafb9678)

**Comment by NotStanley4330** [comment]
I pulled this down and will look at getting the sliders working. I can also make it so it controls master SFX volume as I know how that works fairly well.

**Comment by wench** [comment]
I'll add in code that will allow proper realtime volume control of music . volume curve isn't really appropriate for this. Not sure if ogg music and midi should have separate controls. Midi could have separate controls per device but that doesn't really seem necessary

**Comment by wench** [comment]
Thinking the gump should only control music volume for the current music device or oggs but the config file should probably store things separately per device to allow people to tune volume per device by switching between them.

**Comment by DominusExult** [comment]
> Thinking the gump should only control music volume for the current music device or oggs but the config file should probably store things separately per device to allow people to tune volume per device by switching between them.

This might be a bit over the top for the normal user but probably welcomed by more "serious" users.
So I guess `<volume>` should be its own section under `<audio> `with several `<volume_DRIVERNAME>` and `<volume_sfx>`, `<volume_speech>`

**Comment by wench** [comment]
Sounds good to me. As I add music volume support to the Audio code I'll update the Audio code so it will use those config settings to set music volume upon startup. I'll fork your branch and make a pull request on your repository when done

**Comment by DominusExult** [comment]
I've updated my fork with main Exult and added a button to the Audio Options gump.
(name of the button and the used shortcut key are open for discussion :))

The Audio Options gump could use just a tiny bit more space or I need to minimize the gap between the section by just 1 pixel to have a wider gap between the mixer button and the audio section.

![image](https://github.com/exult/exult/assets/3313896/70192437-bfe6-40a1-9df9-677f92b68fcc)

**Comment by wench** [comment]
If it is ok with you I'll add a new slider widget class and update your new gump to use that instead of what you've done

**Comment by DominusExult** [comment]
Go for it, I have no attachment to it ;)

**Comment by wench** [comment]
Ok cool. Also letting you know that #508 when merged will conflict with your changes to AudioOptions_gump because you changed the position of the music looping button and that conflicts with the changes I made to the button.

**Comment by DominusExult** [comment]
> Ok cool. Also letting you know that #508 when merged will conflict with your changes to AudioOptions_gump because you changed the position of the music looping button and that conflicts with the changes I made to the button.

yes, I know that it will not apply cleanly but at least there is no conflict with where I placed it.

**Comment by DominusExult** [comment]
I played around with it just now. Generally looking great :)
However the volume settings don't seem to work out exactly as saved.
If I set the volumes to just barely audible (all three settings), close all gumps and return, the slider is sill at the correct position but the volume is much higher and if you then change all the way up to 100 it is very much higher than the 100.
Digital music is acting weirdly at times It didn't change the volume at all when you moved the slider other times it seems to work fine (but also not sticking correctly to what the slider is set to).

**Comment by wench** [comment]
I'll check it out if there are issues with sfx, speech a digital music the problem might be in very old code

**Comment by wench** [comment]
I created a new branch here on the exult repo for this that any of us can commit  any fixes

**Comment by DominusExult** [comment]
Thanks! I fixed the iOS compilation on that.

Xcode complains about 
```
protected:
	Gump_widget()     = default;
```
in both Gump_widget.h:37 and Gump.h:121 with `Explicitly defaulted default constructor is implicitly deleted`.
The proposed fix is to replace `default` with `delete`.

**Comment by wench** [comment]
Having difficulty replicating errornous behaviour but I did notice that escaping or cancelling out of the Mixer gump does not behave properly (sfx volume gets reset to whatever music was a classic copy paste bug). This is now fixed. If you were escaping out of the gump and not pressing ok, That might explain why you saw problems. I haven't noticed anything wrong with the sound tester. I added lots of debug code and the correct volumes were getting through to the final stage of the Audio mixer. Playing sounds will now output debug info for what the real volume it will be played at in hex from 0 to 100

Problem with missing oggs is a tricky one. If only some ogg files are missing then what should we do. I can add a check to the volume mixer so that is will adjust midi music volume if oggs are missing, but which oggs should we check for? All of them? Just the test tune? Or maybe i should just have it adjust Midi and ogg volumes together except maybe if current midi volume != current ogg volume. Ideally I would have two separate music sliders, one for ogg and one for midi. Might also be an idea to have a text popup if the test tune ogg is missing

Warnings about default constructors This seems to be something only clang cares about. Fixed

**Comment by DominusExult** [comment]
I really have to record it, maybe with a video. With Speech it is very apparent that something is wrong.
Right now I started Exult with the slider already at 2, tested the Speech with the sound tester and it *blasted* speech, and when I dropped it to 1 it was very audible lower, up to 2 again very much louder. Going all the way up to 100 (very very loud) and only now when sliding to left the volume changed gradually.

**Comment by DominusExult** [comment]
Please disregard. This was caused by a software running on my macOS that handles audio volume. Great piece of software with an option for "audio boost". To me that always meant that it was just amplifying the volume. But no, it would also gradually amplify audio. With some very weird effects. If you want to experience that https://youtu.be/pqRjTRP_WC4

**Comment by wench** [comment]
I am going to try to have the gump automatically resize to 3 or 4 sliders if ogg music or not. Will be a bit of an experiment with creating procedurally drawn modal gump background, I'm surprised we didn't try a longtime ago. Wont need to create or modify shapes for new or changed generic modal gumps

**Comment by DominusExult** [comment]
Xcode complains about `unused variable cmbshape` in gumps/Modal_gump.ccc:229.

And the options gumps now trigger
```
 if (!shape || !shape->get_data()) {
			CERR("nullptr SHAPE!!!");
```
in shapeid.h:138

**Comment by wench** [comment]
Both fixed

**Comment by wench** [comment]
This is what I've been doing. Updated it  to use the new procedural drawing. Autmatically sizes to three or 3 sliders. It will show 4 sliders if both midi and ogg are enabled. It will also resize wider to fit the longer labels. The error message will show for 5 seconds if playback fails. Decided to make it pop up at the top instead of adding empty space to the gump itself. Also decided to try out 3d slider tracks insteal of single colour flat. I think it looks quite nice like this

3 sliders:
![mixer3](https://github.com/exult/exult/assets/1016583/f033c082-9640-4662-be92-4372f43e0c34)


4 sliders:
![mixer4](https://github.com/exult/exult/assets/1016583/8b3c3111-eb3f-4290-a627-eb377a73f85e)

it's getting late, Will push these changes tomorrow, well I guess since it is after midnight that will be later today

**Comment by DominusExult** [comment]
Looks cool 😎

**Comment by wench** [comment]
Pushed. I think that's about it unless problems are found. I am happy with everything

**Comment by DominusExult** [comment]
I wonder if the alert could be enhanced to be a standalone alert that *could* also be for alerts that need user interaction. I had prototyped such an alert gump in #104. Useful for that case, other Exult Studio alerts,  or when the window size is smaller than the game area alert.

Anyway, I will test some more tomorrow and report back so it can be merged. Thanks a lot!

**Comment by wench** [comment]
Can make it be anything you like. I just put it this way because I didn't think it needed a user interaction

**Comment by DominusExult** [comment]
It's working great. found no problem with it :)

However :), what do you think of making the OK button into an apply button as is done with the Video gump? Testing got kind of annoying since you have to close the gump and reopen it for the settings to apply. When I forgot everything was odd of course :)

**Comment by wench** [comment]
I don't really understand what you mean by "you have to close the gump and reopen it for the settings to apply" the mixer gump immediately applies settings as they are changed. Pressing ok only closes the gump and saves the settings to exult,cfg and reopening the gump does nothing that would matter here it doesn't even reread settings from disk, it only gets the current volumes being used by the audio subsystem.

**Comment by DominusExult** [comment]
Sorry, I was unclear, I mean the Audio Options gump which I used to test various drivers

**Comment by wench** [comment]
Ok yeah changing that is probably a good

**Comment by wench** [comment]
Changed the Audio Options Gump to have an apply button instead of ok

**Comment by DominusExult** [comment]
Thank you, I think it's good to go.

**Comment by wench** [comment]
Made a Pull Request for it. Will be nice to get off this branch, I spent way too long on this. There are things I want to do that are not this.

**Comment by DominusExult** [comment]
Sorry for the noise but somehow I pushed the volume mixer branch again - no idea what happened there :(
But it doesn't seem that it broke anything on git
