### ISSUE TITLE
Training points are bugged - cannot change (subtract) via usecode or ES/cheat menu

### ISSUE THREAD

**Issue by agentorangeguy** [exult/exult#541]
Training points are bugged.  Using Exult Studio to set them back to 0 for an npc does nothing.  Changing training points via usecode is bugged as well. Example:  Avatar has 3 training points.  Using the UI_npc_prop(AVATAR, TRAINING, -3); intrinsic does nothing to 'zero' out the Avatar's current training points and this used to work.  

Additionally, there is no option in the F2 cheat menu to change training points at all as it used to, it has been completely removed.

**Comment by wench** [comment]
Ah oops, will fix the cheat screen momentarily. The training points option should still work in the cheat screen if you press 2 while editing an npc. It just isn't showing a menu item for it, I accidentally removed it in my recent changes.
However I tested it and the cheat screen is also unable to set training points to zero. I could go from 3 to 1 but unable to go down to 0. I'll fix this not being able to set them to zero as a comment in the code indicates that this is bugged behaviour.
