### ISSUE TITLE
Windows Installer downloads offical mods from latest GitHub release

### ISSUE THREAD

**Issue by wench** [exult/exult#556]
This problem caused an issue for at least one user with the 1.10.0 release, see #554  This may not seem like a big problem but it might cause more problems in the future.

I have concerns that the mods are being installed regardless of the version Exult are always the latest version and may not match the version of Exult which could lead to compatibility problems if the mods get updated to use new functionality not in for example the 1.10.0 release.

Always downloading the latest version of the mods seems to be  to ensure the latest snapshot will download the latest mods as expected. but it can cause problems for official releases and non current snapshots.

I'm thinking things should be changed so the official mods are included in the installer not downloaded by the installer. The mods are so small that they won't noticeably increase the size of the installer.

After making this change issuing a 1.10.1 release with the new installer might be a good idea, But it is definitely something that needs doing before 1.12

**Comment by DominusExult** [comment]
This should be rather easy I think. We could still leave it in the optional download options but it will skip the download and just install the files.

**Comment by DominusExult** [comment]
Thinking about it more:
- our mods should also be released as zips to download (so other system releases can always get the correct time synced mod if need be)
- The Windows installer for releases AND snapshots should always have the mods included with an install option instead of a download & install option.

**Comment by wench** [comment]
Agreed. I'll make the needed changes to the windows makefile and installer.

**Comment by wench** [comment]
Ok done. Pushed the changes. I didn't alter the components list so the mods are still listed under download and install. This set of changes now means that building the Exult dist in mingw now requires the zip package

**Comment by wench** [comment]
Closing this because it is fixed to my satisfaction.
