### ISSUE TITLE
Xcode Analyzer results

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#57]
I ran Exult through the Xcode analyzer and thought this list might be interesting:

Dead store Group
exult/version.cc:116:2: Value stored to 'firstoption' is never read
exult/usecode/ucdisasm.cc:230:2: Value stored to 'ip' is never read
exult/usecode/ucsymtbl.cc:225:35: Although the value stored to 'magic' is used in the enclosing expression, the value is never actually read from 'magic'
exult/shapeid.cc:314:2: Value stored to 'ok' is never read
exult/usecode/ucsched.cc:692:22: Although the value stored to 'barge' is used in the enclosing expression, the value is never actually read from 'barge'
exult/menulist.cc:389:4: Value stored to 'mouse_updated' is never read
exult/gumps/Stats_gump.cc:246:3: Value stored to 'attsx' is never read
exult/gamemap.cc:860:10: Although the value stored to 'entlen' is used in the enclosing expression, the value is never actually read from 'entlen'
exult/gamedat.cc:1051:21: Value stored to 'err' is never read
exult/gumps/Gump.cc:386:3: Value stored to 'obj' is never read
exult/files/zip/zip.cc:504:6: Value stored to 'err' is never read
exult/gamerend.cc:296:6: Value stored to 'dx' during its initialization is never read
exult/gamerend.cc:297:6: Value stored to 'dy' during its initialization is never read
exult/gamemgr/sigame.cc:468:3: Value stored to 'next' is never read
exult/gamemgr/bggame.cc:532:10: Value stored to 'ticks' during its initialization is never read
exult/gamemgr/bggame.cc:1695:3: Value stored to 'next' is never read
exult/exultmenu.cc:223:32: Although the value stored to 'ypos' is used in the enclosing expression, the value is never actually read from 'ypos'
exult/exultmenu.cc:281:32: Although the value stored to 'ypos' is used in the enclosing expression, the value is never actually read from 'ypos'
exult/files/zip/unzip.cc:581:3: Value stored to 'lSeek' is never read
exult/files/zip/unzip.cc:583:3: Value stored to 'lSeek' is never read
exult/files/zip/unzip.cc:840:3: Value stored to 'err' is never read
exult/cheat_screen.cc:1063:37: Value stored to 'mode' is never read
exult/cheat_screen.cc:1064:23: Value stored to 'mode' is never read
exult/cheat_screen.cc:2604:27: Value stored to 'mode' is never read
exult/cheat_screen.cc:2605:23: Value stored to 'mode' is never read
exult/audio/midi_drivers/CoreMidiDriver.cpp:39:2: Value stored to 'err' is never read
exult/actions.cc:237:18: Although the value stored to 'blk' is used in the enclosing expression, the value is never actually read from 'blk'
exult/audio/midi_drivers/XMidiFile.cpp:1435:4: Value stored to 'len' is never read
exult/audio/midi_drivers/XMidiFile.cpp:1706:2: Value stored to 'time' is never read
exult/exult.cc:1583:14: Although the value stored to 'gump' is used in the enclosing expression, the value is never actually read from 'gump'
exult/audio/midi_drivers/LowLevelMidiDriver.cpp:1437:40: Value stored to 'size' is never read
exult/audio/midi_drivers/LowLevelMidiDriver.cpp:1496:6: Value stored to 'sysex_size' is never read

Logic error Group
exult/pathfinder/Astar.cc:40:3: Forming reference to null pointer
exult/usecode/ucsched.cc:626:24: The left operand of '>' is a garbage value (within a call to 'get_int_value')
exult/shapes/font.cc:118:4: Called C++ object pointer is null
exult/shapes/font.cc:143:6: Called C++ object pointer is null
exult/shapes/font.cc:184:4: Called C++ object pointer is null
exult/shapes/font.cc:211:4: Called C++ object pointer is null
exult/keys.cc:755:58: The left operand of '==' is a garbage value
exult/shapes/vgafile.cc:273:8: Branch condition evaluates to a garbage value
exult/imagewin/scale_2x.cc:55:2: Array access (from variable 'src1') results in a null pointer dereference (within a call to 'Scale2x_noblur')
exult/imagewin/scale_2x.cc:69:2: Array access (from variable 'src1') results in a null pointer dereference (within a call to 'Scale2x_noblur')
exult/imagewin/scale_2x.cc:83:2: Array access (from variable 'src1') results in a null pointer dereference (within a call to 'Scale2x_noblur')
exult/imagewin/scale_2x.cc:97:2: Array access (from variable 'src1') results in a null pointer dereference (within a call to 'Scale2x_noblur')
exult/imagewin/scale_bilinear.cc:43:2: Dereference of null pointer (loaded from variable 'ar') (within a call to 'Scale_2xBilinear')
exult/imagewin/scale_bilinear.cc:59:2: Dereference of null pointer (loaded from variable 'ar') (within a call to 'Scale_2xBilinear')
exult/imagewin/scale_bilinear.cc:75:2: Dereference of null pointer (loaded from variable 'ar') (within a call to 'Scale_2xBilinear')
exult/imagewin/scale_bilinear.cc:91:2: Dereference of null pointer (loaded from variable 'ar') (within a call to 'Scale_2xBilinear')
exult/imagewin/scale_bilinear.cc:110:2: Dereference of null pointer (loaded from variable 'ar') (within a call to 'Scale_2xBilinearPlus')
exult/imagewin/scale_bilinear.cc:126:2: Dereference of null pointer (loaded from variable 'ar') (within a call to 'Scale_2xBilinearPlus')
exult/imagewin/scale_bilinear.cc:142:2: Dereference of null pointer (loaded from variable 'ar') (within a call to 'Scale_2xBilinearPlus')
exult/imagewin/scale_bilinear.cc:158:2: Dereference of null pointer (loaded from variable 'ar') (within a call to 'Scale_2xBilinearPlus')
exult/usecode/ucinternal.cc:516:13: The left operand of '>' is a garbage value (within a call to 'get_int_value')
exult/usecode/ucinternal.cc:2869:10: Dereference of undefined pointer value (within a call to 'get_class_ptr')
exult/gamemap.cc:840:3: Called C++ object pointer is null
exult/gamemap.cc:842:7: Called C++ object pointer is null
exult/gamemap.cc:1594:3: Called C++ object pointer is null (within a call to 'ensure_chunk_read')
exult/files/crc.cc:128:34: The right operand of '^' is a garbage value
exult/imagewin/scale_xbr.cc:50:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/imagewin/scale_xbr.cc:64:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/imagewin/scale_xbr.cc:78:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/imagewin/scale_xbr.cc:92:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/imagewin/scale_xbr.cc:109:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/imagewin/scale_xbr.cc:123:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/imagewin/scale_xbr.cc:137:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/imagewin/scale_xbr.cc:151:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/imagewin/scale_xbr.cc:168:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/imagewin/scale_xbr.cc:182:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/imagewin/scale_xbr.cc:196:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/imagewin/scale_xbr.cc:210:2: Forming reference to null pointer (within a call to 'Scale_xBR')
exult/files/zip/unzip.cc:149:4: Assigned value is garbage or undefined
exult/files/zip/unzip.cc:168:4: Assigned value is garbage or undefined
exult/files/zip/unzip.cc:193:13: 1st function call argument is an uninitialized value
exult/audio/midi_drivers/mt32emu/TVP.cpp:257:48: The result of the left shift is undefined because the left operand is negative
exult/usecode/intrinsics.cc:3331:14: The left operand of '>' is a garbage value (within a call to 'get_int_value')

Memory error Group
exult/shapes/shapevga.cc:387:1: Potential memory leak
exult/readnpcs.cc:236:1: Potential leak of memory pointed to by 'schedules'

Memory (Core Foundation/Objective-C/OSObject) Group
exult/ios/ios_utils.mm:81:2: Potential leak of an object of type 'UIViewController *'

**Comment by drcode1** [comment]
I'll take a look at cleaning these up, though I suspect some of the null
pointer earnings are false.

**Comment by DominusExult** [comment]
Yeah, probably a couple of falses in there. Marzo has been cleaning stuff left and right already.

**Comment by marzojr** [comment]
Hi Jeff,

I can save you the trouble. The xcode analyzer is basically just clang
static analyzer, and I have already analyzed all of those null pointer
issues. They are *all* false positives.

As for the other warnings, I think many of the written but unused are due
to things like DEBUG vs not, or other of the many optional defines we have.

**Comment by drcode1** [comment]
Thanks!  I suspected that would be the case.
