### ISSUE TITLE
Replacing xdrag with SDL_DROPTEXT

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#58]
@Dragon-Baroque ported Exult Studio to GTK+3 and we talked about whether it would be possible to replace xdrag on *nix systems with SDL_DROPTEXT. The reason why I asked was to make Exult not depend on XWindows when you enable Exult Studio support. Since you can build Exult Studio with Quartz (instead of XQuartz/X11/XWindows) and Exult itself does not need X11 at all, this would be a great thing.
Dragon-Baroque's analysis he sent me per email to keep a public reminder:

_I have looked further into your question whether Exult could receive dropped objects from ExultStudio in native Quartz.
I have changed my position of using SDL_DROPTEXT.
Instead I think now that your were right it taking example from the SDL source code.
To complement SDL, I had the source code of GTK+ doing Drag and Drop with Quartz.
Side comment : it should be much simpler than the X11 code._

**Initialization** from src/video/cocoa/SDL_cocoawindow.m

[data->nswindow registerForDraggedTypes:[NSArray arrayWithObject:(NSString *)...]]

except that you replace the underlined argument by a NSArray of 4 NSString ( or perhaps NSString *, this is confusing  ) :

`"U7SHAPEID", "U7CHUNKID", "U7NPCID", "U7COMBOID"` ( from shapes/u7drag.h )

**Callback 1** from src/video/cocoa/SDL_cocoawindow.m, just the entrance and the exit

```
 - (BOOL)performDragOperation:(id <NSDraggingInfo>)sender
{ @autoreleasepool
{
NSPasteboard *pasteboard = [sender draggingPasteboard];

...

return YES;

}}
```

At first I suggest to just put a fprintf to stderr to let you know that you have had indeed a Drop event in Exult from any Npc / Combo / Chunk or regular Shape from ExultStudio.
If this works you can enrich it with

`NSPoint point = [sender draggingLocation];`

Then take from the same code in SDL some converter from NSPoint to x,y in SDL units.
By the way, it seems that the Y direction is reversed in Quartz compared to SDL and GTK+.
You should then be able to retrieve the data with some

`NSData * data = [pasteboard dataForType:[NSString stringWithUTF8String:"U7...ID"]];`

where you place the "`U7CHUNKID`" or ..., the one that you should actually retrieve from the array - it should be a single element array

`[pasteboard types]`

The NSData * can then be used with

`[data bytes] `gives the byte array pointer

`[data length]` gives the byte array length

With all that you should be able to call Drop callbacks like in xdrag.cc

**Callback 2**

```
- (NSDragOperation)draggingUpdated:(id <NSDraggingInfo>)sender
{
NSPoint point = [sender draggingLocation];

...
return NSDragOperationCopy;
}
```

Where again, you should be able to retrieve mouse location from the NSPoint, and possibly too, to retrieve the NSData from the NSPasteboard from the NSDraggingInfo, exactly like in performDragOperation.

If you get both the mouse location and the data, you would have everything needed to call the Move callbacks like in xdrag.cc.

**NB:** From what I have seen in SDL and GTK+, I am quite confident that you can obtain

- The 2 callbacks being called when you perform a Drag&Drop operation from ExultStudio,
- The location of the mouse.

I am far less secure about the extraction of the data, and even whether it shall be available in the callbacks without further requests to Quartz.

**Comment by Dragon-Baroque** [comment]
Changed my mind.

A commit on Dragon-Baroque/exult, branch exult_x11_dependencies to use SDL_DROPFILE - mind, not SDL_DROPTEXT - for Drag and Drop on Unix like platforms.

On the one hand, the patch removes the second X11 dependency on macOS, on the other hand, SDL does not present events to  track the movement of the mouse : the fine position green grid of the Shapes and the Combos in Drag and Drop from ExultStudio into Exult is lost.

Tested only on Linux.

To expand to Windows too ...

Sincerely
Dragon Baroque
-===(UDIC)===-

**Comment by DominusExult** [comment]
This was accepted and works great
