### ISSUE TITLE
Minor endianness issue, compiled Exult on a PowerPC

### ISSUE THREAD

**Issue by Link4Electronics** [exult/exult#582]
Hello everyone, I hope everything is alright. So, I compiled exult on a PowerMac G5 running Debian sid PPC64. It works but every time I need to use the --nocrc parameter to be able to play, otherwise it complains about exult_si.flx having wrong checksum, despite using the file from repo
Thank you for your support, best regards
Link.

**Comment by wench** [comment]
You need to use the exact flx files that were built with exult. If you are using flex file that you yourself didn't build when building exult it might fail crc check. All 3 exult flex files have their crc checked by exult. If there was an endian problem, all should flexes fail the check. exult_si.flx was updated 2 days ago so any version from somewhere else will no longer match what is expected by the build process. The crc checks are there to make sure you are using the flex files that match the exact version of exult you are trying to run. I'm guessing you didn't do a make install after building so the build process didn't overwrite your old flexes with the new ones

**Comment by Link4Electronics** [comment]
I have cloned the last repo, cloned yesterday, and used the flx generated during the building, but just to make sure gonna do a make clean and a new build rn.
Best regards,
Link.
