### ISSUE TITLE
Exult for iOS testflight not accepting new testers

### ISSUE THREAD

**Issue by 0xcoolio** [exult/exult#586]
When I try to launch exult on my ipad, I got a message that the beta expired and no longer accepting new testers.

Appreciate all your work keeping this amazing game fun and running well all these years!

**Comment by DominusExult** [comment]
I'm working on it. I've missed updating the testflight version, submitted a new version and right now am waiting for Apple to greenlight it.

**Comment by DominusExult** [comment]
TestFlight has been updated
