### ISSUE TITLE
Port to GTK+3

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#59]
@Dragon-Baroque ported Exult Studio to GTK+3 and documented his port in detail at https://github.com/Dragon-Baroque/exult/blob/gtk3-port/mapedit/ExultStudio_Migration_to_GTK3.md
His branch is at https://github.com/Dragon-Baroque/exult/tree/gtk3-port

@marzojr already said he would take a look, I'm just adding this issue as a reminder and a place to discuss possible issues. I'm sure @drcode1 is interested as well in this port.

**Comment by drcode1** [comment]
Wow!  He did a lot of work.  I read about a third of it, and feel like I 
haven't been keeping up at all with GTK.

**Comment by marzojr** [comment]
Merged in.
