### ISSUE TITLE
Removal of X11 dependency in Delay and Server_delay

### ISSUE THREAD

**Issue by Dragon-Baroque** [exult/exult#60]
Proposed a new branch "exult_x11_dependencies" on Dragon-Baroque/exult.

It removes the ConnectionNumber / xfd dependency of Exult over X11 in Delay() ( gumps/gump_util.h ) and Server_delay ( server/server.cc ) using either pure SDL cross platform ( Delay ) or SDL  + UNIX select without xfd ( Server_delay ).

**Comment by DominusExult** [comment]
Just tested and it works fine on macOS

**Comment by Dragon-Baroque** [comment]
The Travis build of the pull request failed because of merge conflicts between exult/master and exult_x11_dependencies.
I merged master into exult_x11_dependencies and fixed conflicts. Then pushed the new exult_x11_dependencies.
The Travis build then passed.
Is this the right way to do that ? Should I have attempted a rebase of exult_x11_dependencies on master instead ?

**Comment by marzojr** [comment]
I would prefer a rebase to master and force-push. This leaves a cleaner history.

**Comment by Dragon-Baroque** [comment]
Branches exult_x11_dependencies ( and exult_user_events ) rebased to master.
