### ISSUE TITLE
Android/iOS: When Exult switches from background to foreground the mouse cursor is shown

### ISSUE THREAD

**Issue by Tonynaut** [exult/exult#601]
When playing Exult 1.8 on an Android handheld, the mouse cursor was hidden.  This was the right experience as the avatar control was through direction stick and interacting with the environment was through touch.

When updating to Exult 1.10.1, the mouse cursor is always visible and just feels in the way.  Would be nice to get back to no mouse cursor on a touch-based system (or at least have the option to turn the mouse cursor on or off if touch is an option).

(Note:  Updating to 1.10.1 stopped Exult from crashing on me when when defending Stefano in Serpent Isle... nice to be able to continue my game!).

**Comment by DominusExult** [comment]
Thanks for the report, I've noticed it as well but was only able to reproduce (on the Android Emulator) with the lock stock Android 15 image (not with the Google Play image nor the Android 14 image).
I'll keep an eye on it and try to prevent it.
The mouse cursor should only show when a mouse is attached to the device.

**Comment by DominusExult** [comment]
Hmm, could you try the latest snapshot? https://github.com/exult/exult/releases/tag/snapshot-v1.11.0.20241213
It may not be present with that anymore.

**Comment by Tonynaut** [comment]
I'll try it right now.

**Comment by Tonynaut** [comment]
All is good in the latest snapshot!  Consider this issue closed.

**Comment by DominusExult** [comment]
thank you for quickly testing this. My guess is that the used SDL library had a bug that has been fixed since.

**Comment by Tonynaut** [comment]
I hate to re-open this, but I did find an issue.  When you launch Exult (the latest snapshot as discussed above) everything works great.  If you switch out of Exult (don't close Exult, just switch to another app), and then switch back to Exult, the cursor reappears.

**Comment by DominusExult** [comment]
I can confirm this on both Android and iOS, though on iOS a touch will hide the cursor again (but not on Android). Thanks for getting back.

I have an idea on how to fix this.

Note to myself:
in exult.cc `static void Handle_event(SDL_Event& event)` add a case for `SDL_APP_DIDENTERFOREGROUND` - perhaps add it to `case SDL_FINGERDOWN`

**Comment by DominusExult** [comment]
@Tonynaut I tested on a real device right now and you can hide the cursor when you touch with **two** fingers.

I'm still looking into how to fix it completely.

**Comment by Tonynaut** [comment]
You are right.  Tried it here... when I touch the screen with two fingers the cursor disappears.

**Comment by DominusExult** [comment]
Just a progress report, for some reason I cannot make it work directly when Exult enters foreground again, but at least I found the culprit of why you need to touch with two fingers. THAT I am about to fix, I only need to test how Exult on Android behaves when a real mouse is connected (if I can manage to test this).

**Comment by Tonynaut** [comment]
Let me know if you need me to test.  Happy to do it.

**Comment by DominusExult** [comment]
> Let me know if you need me to test. Happy to do it.

Thanks for the offer but now that I'm using a real device for testing as well, I've got it working.

Next snapshot (in about 18 hours) should have it working that *one finger* touch is enough to hide the cursor again.

**Comment by Dragon-Baroque** [comment]
The changes in `master` have been replicated into `exult-sdl3` if you would like to validate them in SDL 3.

Would you like to describe how I should install the build of Exult under Android Studio - I know how to install Android Studio itself -, and how to use the Android Emulator on the built APK ? 
Please consider that my Linux is Intel, is Android Studio cross platform capable ( ARM ) ? Is the Android Emulator cross platform capable ?
Would it help you if I was able to validate an Android build of Exult before posting a change to `exult-sdl3` ?

**Comment by DominusExult** [comment]
I will check eventually, but xmas time is stressy ;)

To install Exult, start Android Studio and in the "device manager" create a new device (Android 14, best not a fold).
Start that and drag and drop the apk (debug, release needs to be signed).
To get a game onto it, drag and drop a zip with either BG or SI (only the static folder is enough, but the whole folder, not just the files).

By the default we build all four arches so that will definitely work in the emulator. To save time you can build the arch native to your linux machine (see configure), on my ARM based macOS I need to build the arm8-64 only.

**Comment by DominusExult** [comment]
I follow the instructions in android/Readme.md
- install gradle
- download the tools (sdkmanager)
- grab the SDK, NDK, buildtools, cmake (in the versions from configure) via sdkmanager
- setup Java Home, Android home, paths
- run autoreconf/configure

**Comment by DominusExult** [comment]
@Dragon-Baroque it seems on SDL3 it needs to be just slightly different (and maybe SDL2 the same)

Maybe like this:
```
case SDL_EVENT_FINGER_DOWN: {
		if ((!Mouse::use_touch_input) && (event.tfinger.touchID !=SDL_MOUSE_TOUCHID)) {
```
This is not ideal :(

SDL2:
fingerId on finger some arbitrary number starting with 0 going into the thousands, depending on the touch device/platform, no way to properly differ between mouse and real finger.
touchId finger > 0, mouse = -1
SDL_MOUSE_TOUCHID = -1 for both finger and mouse, it returns (as it says, the mouse touchId)

SDL3
fingerID some arbitrary number starting with 1 going into the thousands, depending on the touch device/platform, no way to properly differ between mouse and real finger.
touchID finger iOS = 1/Android = 5, mouse both iOS and Android = **18446744073709551615**
SDL_MOUSE_TOUCHID = 18446744073709551615 for both finger and mouse, it returns (as it says, the mouse touchId)

**Comment by Dragon-Baroque** [comment]
Looking into the SDL sources, `touchId` ( type `SDL_TouchID` ) in SDL2 was a `Sint64`, became `touchID` ( type `SDL_TouchID` unchanged ) a `Uint64` in SDL3. But `SDL_MOUSE_TOUCHID` remained `-1`, transformed into `18446744073709551615` by the `Uint64` type.

In other words the replacement to `touchId != SDL_MOUSE_TOUCHID` should be the right one in SDL2, just altered to `touchID != SDL_MOUSE_TOUCHID` in SDL3.

Would you like to apply the SDL2 change, to `master`, I shall propagate it to SDL3 into `exult-sdl3`.

**Comment by DominusExult** [comment]
> Looking into the SDL sources, `touchId` ( type `SDL_TouchID` ) in SDL2 was a `Sint64`, became `touchID` ( type `SDL_TouchID` unchanged ) a `Uint64` in SDL3. But `SDL_MOUSE_TOUCHID` remained `-1`, transformed into `18446744073709551615` by the `Uint64` type.

Great, thanks for explaining!

I've already committed it 2 hours ago :) 5246d21d86430
