### ISSUE TITLE
u6 mod bugs acceptable here? 

### ISSUE THREAD

**Issue by i30817** [exult/exult#606]
I can't register in disquis or facebook. 

Anyway Sherry can only be talked to right after you start exult\the game the first time, not after a load. 

I suspect the egg that initiates conversation is getting progressively more distant from the actual npc sprite as time goes on, and restarting exult somehow resets it. 

Also the mini quest to get the Wizard of Oz book to Lord British makes him look like a idiot because the actual book is in his table in his room, which I suppose is a testing leftover. You can only do this quest before Sherry joins, because her joining modifies the dialog chain and hide the book topic.

**Comment by marzojr** [comment]
This tracker is for bugs in Exult, Exult Studio, the tools, or for the mods whose source is bundled with Exult (Keyring, SI Fixes, Isle FAQ).

U6 Mod is not in any of these groups. Please try to contact the author directly.
