### ISSUE TITLE
Duplicate files in Studio file list with case sensitive filesystems

### ISSUE THREAD

**Issue by Dragon-Baroque** [exult/exult#65]
### Description

On Linux, opening game Forge of Virtue with mod KeyRing results in spurious file pairs in Studio file list, if Forge of Virtue is installed with the files upper cased to follow the DOS convention.

- The file list shows `shapes.vga` ( from Exult, of the KeyRing mod ) and `SHAPES.VGA` ( from Forge of Virtue )

And some other similar pairs. The `shapes.vga` is expected, the `SHAPES.VGA` is not.

### Analysis

- In `mapedit/studio.cc,` function `add_to_tree,` Studio first gathers the `<PATCH>` files from the KeyRing mod.
- Then it gathers the `<STATIC>` files from the Forge of Virtue base game, while removing the files already found from the `<PATCH>` with a call to `U7exists` against the current `fname`.
- This existence test with `U7exists` works immediately and properly on case insensitive file systems ( Windows, default macOS ), but fails on case sensitive file systems ( Linux ) because `U7exists` is called outside its definition domain :
_The DOS case insensitive part of the call to `U7exists` [ or actually to any `U7...` function ] should be in lower case for the upper casing trial loop of `base_to_uppercase` in `files/utils.cc` to work properly_.
- This is precisely not the case at hand : the `U7exists` function is called with `<PATCH>/SHAPES.VGA` whereas `shapes.vga` resides in the `<PATCH>` folder.
- For this existence test to work on case insensitive file systems the argument to `U7exists` should be transformed to `<PATCH>/shapes.vga` by lower casing the `fname`.

Dragon Baroque, January 8 2021

**Comment by Dragon-Baroque** [comment]
Fix proposal on 

- Fork Dragon-Baroque/exult,
- Branch exult_studio_file_duplicates,
- Lower cases `fname` in `U7exists` call in `add_to_tree` in `mapedit/studio.cc`, 4 lines change.

Dragon Baroque, January 9, 2021

**Comment by marzojr** [comment]
Fixed by merging pull request #67 .
