### ISSUE TITLE
Exult Studio no longer shows corrects stats of examined NPCs

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#68]
When you doubleclick an NPC in mapedit mode the NPC editor window of Exult Studio pops up. The stats shown are not correct but only show the value 1 for everything (strength, intelligence...).

This seems to have originated in the devel merge branch, all Windows snapshots I have since we switched to 1.7 show this problem, while the 1.6 release works correctly.

**Comment by DominusExult** [comment]
@marzojr the culprit is 6eb7079e1ad16f257a61fc3ecf859e1eae3a8707 <- the move to GTKBuilder. I suspected this but did a git bisect anyway.
I'll take a look if I can see something obvious :)

**Comment by DominusExult** [comment]
Observation:
- It also affects the flags tab of the NPC editor
- Also affects creating a new NPC. Instead of setting everything to property to 12, it's 1.
- When you create an NPC, hit apply and then in Exult to place the NPC, Exult crashes

**Comment by Dragon-Baroque** [comment]
From DominusExult's Observations :
First and Second Observations pinpointed to wrong use of gtk_widget_get_name, use gtk_buildable_get_name [ 4 times overall, all in npcedit.cc ]
Third Observation still present before move to GTKBuilder. In Linux, Exult crash shows as 
```
terminate called after throwing an instance of 'std::bad_weak_ptr'
  what():  bad_weak_ptr
Aborted (core dumped)
```

**Comment by Dragon-Baroque** [comment]
I believe that the invalid weak_ptr message tells you is : You are attempting to create secondary shared pointers of an object whose master primary shared pointer does not yet exist.

I tried to create the Npc_actor directly as a shared object - see attached patch [NPCEditor.zip](https://github.com/exult/exult/files/5829850/NPCEditor.zip) -, and it dies much later, in set_schedules, in the same Actor::update_from_studio.

Then as creating the NPC, I gave it  Name, a Face, a Shape, and also "reasonable" Schedule : Set -> Loiter at Game location, then this time the NPC shows up in Exult. Not sure to be on the right track though ...

**Comment by marzojr** [comment]
Hm. Now that I look at them, all the XXX::update_from_studio functions are completelly broken in more ways than one.

**Comment by marzojr** [comment]
I can't see the crashes on Windows with the commit I just pushed. Let me know if it still happens elsewhere.

**Comment by Dragon-Baroque** [comment]
Does not crash on Linux anymore.

Cannot compile with DEBUG, though, --with-debug=extreme causes a macro definition conflict on COUT and CERR in actors.cc : because actors.cc includes objs.h before config.h, and because the common_types.h includes config.h but exult_constants.h does not, and both define COUT and CERR according to DEBUG.

**Comment by marzojr** [comment]
That was an accidental paste. I reverted that line change.

**Comment by marzojr** [comment]
I forgot to close this.
