### ISSUE TITLE
Configure error when compiling

### ISSUE THREAD

**Issue by Demorde** [exult/exult#7]
Hello, when compiling on Fedora 24 pulling fresh from git, it pushes the following error and fails to compile.

```
checking for SDL - version >= 1.2.0... yes
./configure: line 19706: syntax error near unexpected token `newline'
./configure: line 19706: `		XIPH_PATH_OGG('
```

**Comment by marzojr** [comment]
You need to install ogg/vorbis development headers.

**Comment by Demorde** [comment]
That did work, but I will note that on Fedora you need *liboggz-devel* not just *libogg-devel*
