### ISSUE TITLE
import SF.net bug tracker issues as long as it's still possible

### ISSUE THREAD

**Issue by rofl0r** [exult/exult#8]
there's tools to automate it: http://stackoverflow.com/questions/4627241/migrate-sourceforge-tickets-to-github-issues
this is already issue nr #8 , so as time passes ppl will open a lot of issues here and finally it may not be able anymore to use the same issue numbers.

**Comment by DominusExult** [comment]
We missed the window of opportunity but AFAICT we would not have been able to migrate attachments of the SF tracker. But without the attachments 70% of our tracked bugs are useless.

Maybe we should at least close the SF trackers and point people at the Github issue tracker now.

**Comment by drcode1** [comment]
Seems reasonable.

**Comment by DominusExult** [comment]
Made the sourceforge tracker read only and point it at the github issue page.
Will need to fix our documentation for this as well but as usual SF has problems again and is often not accessible

**Comment by DominusExult** [comment]
Documentation now also points at the issue tracker, so I'm closing this.
