### ISSUE TITLE
Travis-CI is stopping macOS builds

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#82]
AFAIU Travis-Ci ist stopping free builds of macOS https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by marzojr** [comment]
Hm. You are correct, they are stopping free macOS builds. But also they are kind of killing the whole Open Source build model: you now get some credits for building on Linux and once they are used up, you can request more on an OSS basis. Hrm.

**Comment by tristantarrant** [comment]
Just use GitHub actions

**Comment by marzojr** [comment]
Sounds like a reasonable alternative. @DominusExult their [virtual environment](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) lacks MacPorts (similarly to the Travis environment, actually); can you investigate the feasibility of building using Homebrew on OSX instead?

Of course, we can do the same as with Travis and just install it, but I am just curious (one less dependency to install). Also, maybe mt32emu should be added to Homebrew as well.

Anyway, I am studying GitHub actions.

**Comment by DominusExult** [comment]
Installing via Homebrew is likely as painless as with MacPorts. Is Homebrew directly available in the github actions?
I'm in quarantine until friday and have time to grab the proper install commands.

For Windows I wonder if you can install InnoSetup via actions and use that to make snapshots available

**Comment by marzojr** [comment]
Homebrew comes preinstalled, yes. I believe that we can use it to extract the produced binaries, yes, and they have msys2 and InnoSetup 6.1.2 preinstalled on their Windows runners.

**Comment by DominusExult** [comment]
Just tested building via Homebrew:

For Exult without Studio you need this command:
`brew install automake libtool pkg-config sdl2 libvorbis`

If you want to test building Studio as well, add
`gtk+3` and use `sdl2 --head` rather than `sdl2` because of the check for SDL2 > 2.0.14 in configure.

Similar to MacPorts you then need to set the Cflags:
```
export CFLAGS=-I/usr/local/include
export CXXFLAGS=$CFLAGS
export CPPFLAGS=$CFLAGS
```

I'll see about trying to get libmt32emu added to Homebrew, until then we can just use `--disable-mt32emu` for testing.

**Comment by marzojr** [comment]
I have a prototype setup using Github Actions, It seems to be working overall, but I will wait for all of the added stuff to run, and then unlinking Travis OSX build, before marking this as fixed.

**Comment by marzojr** [comment]
Looks reasonable.

**Comment by rofl0r** [comment]
`      - name: Install SSH key` is repeated twice in the above snippet (2nd time it should be delete artifact instead)
