### ISSUE TITLE
hanging note bug on track 35 (and other non looping tracks?)

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#85]
It's a long standing bug that was introduced between the 1.2 release (June 2004) and a Windows snapshot from October 2009 (I found on my hard drive).
It's reproducible on Windows via MIDI and possibly on all platforms via FMOpl (on macOS it doesn't happen with CoreAudio but with FMOpl).
Going through commits that affect audio, especially MIDI I found that there actually were not too many.

But of course we have the big one
d8771b66 with the MIDI code from Pentagram overhauling the Exult code

0ed8f9b7 <- probably not it

ff9973e7 and follow up 381f6f3c look interesting and have the potential to be the cause.

(there were other commits to the audio code but I preliminary judged them to not be the cause)

**Comment by wench** [comment]
Black Gate or Serpent Ilse? If BG only I have an idea where the problem could be, The code from pentagram explicitly does not handle note off events as xmi files that U8 and SI uses dont have note off events but BG uses them and the code as it is I don't think handles the note off events used in bgs standard midi files.

**Comment by DominusExult** [comment]
Thanks!
Definitely BG, I will need to test SI.

**Comment by wench** [comment]
I think I should set up a build environment and write a fix

**Comment by DominusExult** [comment]
Ooh, that would be great!

If you are still on Windows, the msys2/Mingw environment is really easy to set up and requires no files provided by us.
The VCprojects however are drastically out of date now.

**Comment by marzojr** [comment]
I was updating the MSVC stuff recently; but given the probable [switch to cmake](https://github.com/exult/exult/issues/79) in the future, which would allow generating MSVC projects, there is probably not much use in updating them now. It is better to use the msys2 setup on Windows for now. I can provide some notes on generating compile_commands.json and setting up VSCode with clangd for a more IDE-like experience if you want.

**Comment by wench** [comment]
Not much needs to be done for Visual Studio 2019. Decent standards compliance and Nuget packages makes thing super easy now compared to the old projects

**Comment by marzojr** [comment]
Ah, yes, I forgot that MSVC has upped their standards compliance a lot in recent years. Well, if you *do* want to create an updated version for MSVC 2019, please consider putting it on the repository and deleting the old ones. And maybe posting some notes on readme.win32 on how to build on it as well -- this might be useful even with a change to cmake, as we can use Nuget to get the dependencies on MSVC.

**Comment by wench** [comment]
This problem is more complex than i thought, I'm getting no problem with my mt32 or the windows gs wavetable synth. only seeing it with fmopl. @DominusExult what configuration were you seeing the problem with windows midi.

**Comment by marzojr** [comment]
Hm. I paid a bit more attention to the logs, and it indeed seems to only happen when FMOpl is selected. The times it happened with Windows Midi seems to be because it is failing for some reason and defaulting to FMOpl.

**Comment by wench** [comment]
Ok so the problem is with fmopl then. Looks like it doesn't support sustain too well. Hopefully an updated version of the code works better, if not i have a work around

**Comment by marzojr** [comment]
I do remember updating FMOpl from ScummVM somewhat recently; git says it was around 2016, and the description says it was mostly formatting (commit a3b1df11143fb00911eb255ca45ee0c7e23f8364).

**Comment by DominusExult** [comment]
Yes, when I mentioned Windows Midi I was refering to Marzo's observations ;)

Btw. all the rage these days is the so called "NukedOPL3" emulation (at a first glance ScummVM has code for that as well).

**Comment by wench** [comment]
I think I'll have to dig around in the scummvm source.

**Comment by DominusExult** [comment]
Many thanks for fixing this! It was an unexpected but very pleasant surprise. I did miss you :)

**Comment by marzojr** [comment]
For what is worth, the overall quality of FMOpl audio seems to have improved quite substantially with the new code.
