### ISSUE TITLE
Proposals for changes in Exult Audio

### ISSUE THREAD

**Issue by Dragon-Baroque** [exult/exult#88]
I have a few changes to offer, mostly in the Audio support for Exult.

- Fixes to the Timidity MIDI driver : Enhancement to the expected location and the parsing of the Configuration file ( all platforms ), Fix to the detection of Little Endian vs Big Endian ( Linux ),
- Enhancement to the ALSA MIDI driver : If the default - `alsa_port` or 65:0 - fails to connect, try to detect a valid MIDI output port. _Explanation_ : the port 65:0 come for MIDI synthesizer sound cards. Now, MIDI is provided by software synthesis, essentially by the three synthesizers natively supported by Exult : MT32Emu, Timidity, and FluidSynth. All three can register as ALSA servers at ports 128:0 and up, by time order of registration. My proposal, to avoid requesting the user to code an `alsa_port` in the configuration `exult.cfg`, is to ask ALSA to name the ALSA clients with available output MIDI and connect to the first that accepts.

I have a few questions :

- Would you like to discuss / review the code of the above proposal ?
- Is it acceptable to set the `alsa_port` in the `exult.cfg` to the detected MIDI server when the default port address failed - whether coming from `exult.cfg` or being 65:0, or is the setting of the `alsa_port` reserved to the human user ?
- Similarly for the FluidSynth MIDI : A recent accepted patch uses the default FluidSynth SoundFont when none is declared in the `fluidsynth_soundfont` tag of the `exult.cfg`. It it acceptable to record it _also_ in the `fluidsynth_soundfont` tag of the `exult.cfg` ?

I have also a pending change to the `exult.cfg` writer, which keeps each value tag in one like, reserving the indentation for nested tags : you now get :
```
 ...
 <audio>
  <disablepause>no</disablepause>
  <enabled>yes</enabled>
  <midi>
   <enabled>yes</enabled>
   <convert>gm</convert>
   <use_oggs>no</use_oggs>
   ...
```
All the changes are ready for review. Please tell me about an acceptable delivery format, I mean, one commit per item, or one commit for all of them...

Dragon-Baroque, March 1st, 2021

**Comment by DominusExult** [comment]
About exult.cfg I'm tentatively against autofilling alsa_port and fluidsynth soundfont location.
I think we don't add these tags by default on linux (or other OS), right?

So the autodetection is a great idea, but once these tags are in the cfg, their value shouldn't be overwritten IMO.

*sigh* I stillstrongly dislike the xml style of the cfg anyway ;)

**Comment by DominusExult** [comment]
It would make sense if we were to poll the ports and print which "devices" Exult finds at the ports. Same as being done for Windows Midi ports and Coremidi on macOS.
And THEN autoselect the first available one if 65:0 (or the alsa_port setting) is not available.

**Comment by marzojr** [comment]
I am actually tempted to maybe add it as a GUI option for it in Audio gump, with something similar for Windows midi drivers. And maybe something similar for OSX, but @DominusExult will have to let me know if this is needed. And with this GUI option being added, maybe it would be better to save the *name* of the chosen device (if it has one) instead of an ID/port -- so if the device ID/port changes, it can still be enabled (if it exists) by name.

The reasons:

1. you can install mt32emu MIDI driver in Linux as an ALSA device, or in Windows as a Windows MIDI device (and likely in OSX as a CoreMidi device or similar, but @DominusExult will have to correct me on that);
2. We currently require the user to supply both an ALSA device or a Windows MIDI device if you don't want the default; and the default is likely not going to be mt32emu driver;
3. Selecting by name when possible would allow adding/removing MIDI devices without having to fix the configuration option in Exult, as long as the device still exists.

The sequence for opening a MIDI device might be something like:
- query all MIDI device names and IDs/ports;
- search for device specified by new option, if it exists;
- if not found, try getting the device with ID/port specified by the old option, if it exists;
- if still not found, fetch the first entry in the list.

**Comment by Dragon-Baroque** [comment]
> sigh I still strongly dislike the xml style of the cfg anyway ;)

Switch to YAML ? And please, not JSON ...

**Comment by DominusExult** [comment]
> > sigh I still strongly dislike the xml style of the cfg anyway ;)
> 
> Switch to YAML ? And please, not JSON ...

Actually I'm pretty much a fan of the ini format. When people from exult started Pentagram, we went with that for ease of use.

OTOH, the strong reason not to switch was always that we *should* have as much as possible accessible via the GUI so people do not have to edit the cfg as much.

> I am actually tempted to maybe add it as a GUI option for it in Audio gump, with something similar for Windows midi drivers. And maybe something similar for OSX, but @DominusExult will have to let me know if this is needed. And with this GUI option being added, maybe it would be better to save the _name_ of the chosen device (if it has one) instead of an ID/port -- so if the device ID/port changes, it can still be enabled (if it exists) by name.

Having this in the GUI for macOS and Linux would be great. DOSBox is already polling the CoreMidi devices' name so you can use either port number or name (quick view in the svn2git repo at https://github.com/svn2github/dosbox/commit/3fd4c512eaf6c372d4a189e03cd2509d17b4f579).

I'm not sure when macOS changed this but at some point the MIDI network port was always turned on and at port 0, so the first port found is always that one, so you will *always* need to set a different one if you want to use a physical device or a virtual one like Munt. <- another reason a GUI option would be great.

Looking at the logging, Exult could also need to print out which port it uses if the one in the cfg is not available (in the screenshot below I had entered the device name and I guess Exult used 0 but you never know :))
![coremidi](https://user-images.githubusercontent.com/3313896/109525498-dd910180-7ab1-11eb-8397-2aedab695555.png)

**Comment by marzojr** [comment]
Regardless of cfg file format, @Dragon-Baroque any code you already have would be welcome.

**Comment by DominusExult** [comment]
> Regardless of cfg file format, @Dragon-Baroque any code you already have would be welcome.

Yes, please disregard the cfg file format, I shouldn't have brought it up, it's just a distraction.

**Comment by Dragon-Baroque** [comment]
A status point, kind of.

I think now, after coding it, that my proposal of altering the `exult.cfg` upon the current successful connection was wrong, as I was facing nasty cases of having to _overwrite_ a value that I had no way of deciding whether it was written earlier by the code or by the user, and even nastier cases of having to _remove_ such values. I should have taken example on the present working : if the default is Alsa but the Alsa connection fails, and Exult connects to FMOpl, even then the configuration is left to default, not moved to FMOpl.

Listing the available devices and their names is quite possible, I wrote a piece of C code to do exactly that, and I extracted from it what I needed to detect _the next MIDI port_. Then the Alsa open in Exult tries to connect to the default port, and if this fails, tries one at a time _the next MIDI port_ until it connects ( I have also expanded the messages to include the MIDI port name ). But I have no proof in advance than an advertised MIDI port will accept the connection, or even that sound will come out. Searching them by name instead of by port is quite possible too. But where in the Audio Gump would I display all that ? I already overflows when the MIDI device button offers `UnixSeqDevice`...

Also I am wondering about the Use Cases of all that : If the user wants the non default Alsa port that looks like a MIDI Synthesizer, then it can name it directly without Alsa at all : the three Synthesizers are FluidSynth, MT32Emu and Timidity and all three are directly available. It might even be better to call them directly than to pass through Alsa, you could tell me whether the direct code might drive the Synthesizer better than the anonymous Alsa port. The case I was trying to solve with Alsa was like the FluidSynth SoundFont, no human action needed to get the default working for a MIDI Synthesizer ( Software or Hardware ) being connected by default as an Alsa port. So long ago that the user has forgotten the how, its name, ...

What I might like in the Audio Gump is an additional button for Alsa giving the current connected port, [ and a possible additional label to display its name ], and when clicked, tries to connect to _the next MIDI port_. I just don't know how to make the user understand that the effect of the button is to look for _the next MIDI port_ while the button displays _the current MIDI port_. I am not good at designing GUIs ...

I can publish the code as is, with the `exult.cfg` overwrites, but I would prefer to remove the overwrites unless you insist on having them. Removing them would be a small delay and an actual simplification...

**Comment by Dragon-Baroque** [comment]
Published in Dragon-Baroque/exult, Branch exult_audio.

**Comment by DominusExult** [comment]
As I messed with CoreAudio and SoundFonts, it would be really great if Exult were to parse the DATA folder for sf2 (and in the case of CoreAudio, additionally for dls) files and toggle them through a button. And if there is anything written in the <..._soundfont> tag first try if that is in the DATA folder and if not try whether it is a full path.

as for the questions above:
1. so far we could use just a button that enumerates the available ports/names and toggle through them (as we do with the MIDI drivers.
2. We do already list in stdout available ports/port names for Windows (WindowsMidiDriver.cpp:74) and CoreMidi (CoreMidiDriver.cpp:57). Can't see anything in the ALSA code.

**Comment by Dragon-Baroque** [comment]
> ... parse the DATA folder for sf2 ...

Can you alter the choice of SoundFonts in `CoreMidi` ? 
In Linux, you cannot in `Alsa`, only directly in `FluidSynth`.

And you should respect the default folders of FluidSynth, `/usr/share/soundfonts`.

> We do already list in stdout available ports/port names for Windows (WindowsMidiDriver.cpp:74) and CoreMidi (CoreMidiDriver.cpp:57). Can't see anything in the ALSA code.

True. I can add this to the code in `Dragon-Baroque/exult` branch `exult_audio`.

> So far we could use just a button that enumerates the available ports/names and toggle through them (as we do with the MIDI drivers.

Yes, but for Alsa, the proper enumeration should be `clientNumber:portNumber` and `clientName:portName`, which would quickly overflow the **gump width**, unless we can restrict to the `portName`. Here is a list from `aplaymidi -l` on my Linux, with my SB Audigy, with FluidSynth and TiMidity++ :
```
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
 24:0    SB Audigy 5/Rx [SB1550]          Audigy MPU-401 (UART)
 24:32   SB Audigy 5/Rx [SB1550]          Audigy MPU-401 #2
 25:0    Emu10k1 WaveTable                Emu10k1 Port 0
 25:1    Emu10k1 WaveTable                Emu10k1 Port 1
 25:2    Emu10k1 WaveTable                Emu10k1 Port 2
 25:3    Emu10k1 WaveTable                Emu10k1 Port 3
128:0    FLUID Synth (178130)             Synth input port (178130:0)
129:0    TiMidity                         TiMidity port 0
129:1    TiMidity                         TiMidity port 1
129:2    TiMidity                         TiMidity port 2
129:3    TiMidity                         TiMidity port 3
```

**Comment by DominusExult** [comment]
I honestly have no idea about ALSA and only about FluidSynth. Fluidsynth is also *special* in Exult as you can have multiple soundfonts that "stack".
For ALSA enumaration you would probably need to see what makes the most sense to display.

There is a difference between CoreAudio and CoreMidi. CoreMidi is only for connecting to an "external" MIDI device which are connected to a port. Can be both a real device like a Roland MT-32 or a virtual one like the Munt MT32emu. It doesn't make use of a soundfont.
CoreAudio is for using the builtin MIDI stuff using a soundfont (which you can change in exult.cfg).

**Comment by Dragon-Baroque** [comment]
I have a prototype change of the my `exult_audio` branch that lists the MIDI devices prior to the connection with Alsa :

```
Trying config specified Midi driver: `Alsa'
Listing midi devices:
14:0 : [ Midi Through : Midi Through Port-0 ], channels 0, used 0
24:0 : [ SB Audigy 5/Rx [SB1550] : Audigy MPU-401 (UART) ], channels 16, used 0
24:32 : [ SB Audigy 5/Rx [SB1550] : Audigy MPU-401 #2 ], channels 16, used 0
25:0 : [ Emu10k1 WaveTable : Emu10k1 Port 0 ], channels 16, used 0
25:1 : [ Emu10k1 WaveTable : Emu10k1 Port 1 ], channels 16, used 0
25:2 : [ Emu10k1 WaveTable : Emu10k1 Port 2 ], channels 16, used 0
25:3 : [ Emu10k1 WaveTable : Emu10k1 Port 3 ], channels 16, used 0
ALSAMidiDriver: Can't subscribe to default MIDI port [65:0], looking for other MIDI ports
ALSAMidiDriver: ALSA client initialised on MIDI port [25:0] [ Emu10k1 WaveTable : Emu10k1 Port 0 ]
Success!
Midi Output: Enabled
```

**Comment by DominusExult** [comment]
That's a very verbose but useful output :)
And yes, `Synth input port (491221:0)`, is long and doesn't even mention Fluidsynth.
