### ISSUE TITLE
BG: show congratulations screen after destroying the black gate

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#90]
After the endgame view you'd get the congratulations screen in the original. We don't show that.
I've managed to only show it when the endgame plays in game but not when you view the endgame from the menu via https://github.com/DominusExult/exult/commit/c40c5072862bc543af4e88d5f876a06c4936b3dc

But I'm not managing to get the time elapsed and I don't know how to display it.
First problem I'm having is that I can't make use of `clock->get_day()`

**Comment by marzojr** [comment]
Do you have any screenshots of the ending screen, so I can see what it is supposed to look like? Also, should we also display one for SI?

**Comment by DominusExult** [comment]
<img width="1268" alt="bgend2days" src="https://user-images.githubusercontent.com/3313896/109806343-e2c28d80-7c24-11eb-91a9-ce5c28396e6d.png">
<img width="1268" alt="bgend456days" src="https://user-images.githubusercontent.com/3313896/109806354-e6561480-7c24-11eb-9242-de461e6aa5fa.png">
(I think I set it to 456 days)

I was thinking of adding one for SI as well. But "congratulations" seems wrong :)
Maybe:
You have restored balance to Serpent Isle in .... Unfortunately the Guardian has kidnapped you! Please tell Lord British of your fate!"

And since LB is very active on Twitter to congratulate people, we should maybe change this all to "Please write Lord British, @RichardGarriott on Twitter, telling him of your accomplishments!"

**Comment by DominusExult** [comment]
I tested somewhat and if I didn't make a mistake Britannia has 13 months per year and only 28 days in a month. No leap year, no uneven months.

**Comment by DominusExult** [comment]
And to make matters complicated, from Morfin's venom sales book:
```

..July, 0359: 
        Sale - 3 vials - 300 
        Sale - 5 vials - 480 
    August, 0359: 
        Sale - 12 vials - 1100 
    October, 0359: 
        Sale - 9 vials - 880 
    December, 0359: 
        Sale - 10 vials - 1000 
        Sale - 5 vials - 500 
    February, 0360: 
        Sale - 6 vials - 590 
        Sale - 4 vials - 400 
        Sale - 5 vials - 500 
    April, 0360: 
        Sale - 6 vials - 620 
    September, 0360 
        Sale - 5 vials - 500 
        Sale - 5 vials - 480 
    November, 0360: 
        Sale - 10 vials - 990 
    January, 0361: 
        Sale - 12 vials - 1200...

```
So I guess they didn't talk this through :)

**Comment by DominusExult** [comment]
https://wiki.ultimacodex.com/wiki/Britannian_calendar <- it states Britannia had 12 months, with each month 28 days long.
Again a hard question: have it behave like the other Ultimas, like the original U7, or apply more Earth logic?
*OR* only show days :)

**Comment by Dreded** [comment]
easy answer would be offend nobody and only show months and days, or days only.. also having 13 months almost for sure would be because someone used 12 to represent the 12th month not 11(computers count from 0) so 13 can easily be considered a bug since a in game calendar from an earlier game states otherwise.

**Comment by Dreded** [comment]
I decided to go with 12 months in a year if it did seem to be 13 it was almost for sure a "bug" as earlier game confirms 12 months.
